danger/danger

lib/danger/ci_source/buildkite.rb, lib/danger/dangerfile_dsl.rb, spec/environment_manager_spec.rb, spec/sources/buildkite_spec.rb, spec/sources/github_spec.rb
Hey! I hope this PR is OK! I added support for Buildkite in the list of CI providers that danger works with.
Let me know if it's missing anything! :dancers:
=> Added support for pull requests on Buildkite

README.md
Improved capitalisation and added links - hope this one is OK too!
=> Updated CI provider names in the Readme

Dangerfile, lib/danger.rb, lib/danger/ci_source/buildkite.rb, lib/danger/ci_source/travis.rb, lib/danger/comment_generators/github.md.erb, lib/danger/dangerfile.rb, lib/danger/environment_manager.rb, lib/danger/request_sources/github.rb, lib/danger/runner.rb, spec/dangerfile_spec.rb, spec/environment_manager_spec.rb, spec/sources/github_spec.rb
=> [WIP] More tests

README.md, danger.gemspec, lib/danger.rb, lib/danger/available_values.rb, lib/danger/dangerfile.rb, lib/danger/dangerfile_dsl.rb, lib/danger/environment_manager.rb, lib/danger/runner.rb, spec/environment_manager_spec.rb, spec/sources/github_spec.rb, spec/spec_helper.rb
=> [WIP] More dynamic things

README.md
I copied  & pasted and got a build error :dancers:
=> ensure example in readme compiles

lib/danger/request_sources/github.rb, spec/sources/github_spec.rb
Previous changes went to a different branch
=> Edits => Master

CHANGELOG.md, Dangerfile, lib/danger/ci_source/circle.rb, spec/sources/circle_spec.rb
I realised that I made the Circle source work differently to the others, and it was the source of my confusion. 
In doing this PR I figured I'd improve our changelog and get Danger involved in making sure we keep it up to date ;)
=> Improve support on Circle CI

.travis.yml, CHANGELOG.md, Dangerfile, circle.yml
Adding support for Circle, and getting Travis back up and running.
=> [WIP] Support running danger on circle on CI

lib/danger/runner.rb
This can be used to fix #45 - it's hard to figure out the true answer to this. Perhaps the real solution is to get the full PR details and use the full JSON data from the PR. For now, this is a useful band-aid.
=> [WIP] Support options on danger run for specifying the head / base commit

CHANGELOG.md, README.md
Forgot to change these :sweat:
=> Updating README and CHANGELOG after pr_labels

CHANGELOG.md, Dangerfile
=> Enforce a changelog entry

circle.yml
OK, let's see where this goes.
=> Only run danger for circle on local PRs

CHANGELOG.md, danger.gemspec, lib/danger/available_values.rb, lib/danger/ci_source/local_git_repo.rb, lib/danger/commands/local.rb, lib/danger/commands/runner.rb, lib/danger/scm_source/git_repo.rb, spec/sources/git_spec.rb
Needs more tests - looks more stable now. I have to understand how git works though, tradeoff.
=> Switch to rugged for git integration

danger.gemspec, lib/danger.rb, lib/danger/dangerfile.rb
:dancers: 
Fixes https://github.com/danger/danger/issues/62
=> Updated PR summary to use terminal-table

CHANGELOG.md, danger.gemspec, lib/danger/ci_source/local_git_repo.rb, lib/danger/scm_source/git_repo.rb, spec/sources/git_spec.rb
Alright - awesome this fixes my biggest issue with Danger! Now it works, and it can run on a mac.
=> Woo - switch to using grit for git diffs - fixes #79

README.md
Closes #60 
Migrates us to my new baseline for new, big, projects.
=> Officiate working as a Moya Contributor's Guidelines / CoC project #trivial

CHANGELOG.md, README.md, danger.gemspec, lib/assets/DangerfileTemplate, lib/danger/commands/init.rb, lib/danger/commands/init_helpers/interviewer.rb
=> Change `danger init` to be a wizard that guides you though the setup process

lib/danger/ci_source/local_git_repo.rb, spec/sources/local_git_repo_spec.rb
Merges in @dbgrandi's changes, and makes the git path dynamic.
Closes #92
=> Fix CI for #92 #trivial

README.md
- No space after `(`
- 2 spaces
- No space after ```
=> Fixed Ruby code style #trivial

.travis.yml, CHANGELOG.md, lib/danger/commands/init.rb, lib/danger/commands/runner.rb, lib/danger/version.rb
Preparing for a release. Added the init function to CI so that we can test if it breaks.
=> Merge #100 & #97

lib/danger/commands/runner.rb
Fixes https://github.com/danger/danger/issues/96 
Thanks @alloy :+1:
=> Don't require Dangerfile for `danger init`

lib/danger/commands/init.rb
=> Update spelling and wording mistakes in init wizard #trivial

.rspec, CHANGELOG.md, lib/danger/circle_api.rb, lib/danger/dangerfile_dsl.rb, lib/danger/plugins/protect_files.rb, spec/danger_spec.rb, spec/dangerfile_spec.rb, spec/environment_manager_spec.rb, spec/sources/buildkite_spec.rb, spec/sources/circle_api_spec.rb, spec/sources/circle_spec.rb, spec/sources/git_spec.rb, spec/sources/github_spec.rb, spec/sources/jenkins_spec.rb, spec/sources/travis_spec.rb
Fixes #72
and fixes https://github.com/danger/danger/issues/74
and more
=> Added protect_files method and plugins and more

lib/danger/commands/init.rb
=> Replaced … with ... #trivial

lib/danger/commands/init.rb
=> Added missing space after `--verbose` #trivial

lib/danger/commands/init.rb
- Added `-` when showing inline
- Made use of variable when printing out in code block
=> Improved circle output #trivial

CHANGELOG.md, lib/danger/request_sources/github.rb
Fixes https://github.com/fastlane/fastlane/pull/3654
=> Fixed null title / body in PRs

lib/danger/ci_source/local_git_repo.rb, spec/sources/local_git_repo_spec.rb
=> [LocalGitRepo] Fixing repo slug when it contains .git #trivial

lib/danger/commands/local.rb
=> Fail gracefully, instead of throwing stack traces #trivial

CHANGELOG.md, Dangerfile, README.md, lib/danger/available_values.rb, lib/danger/plugins/protect_files.rb, lib/danger/scm_source/git_repo.rb, spec/sources/git_spec.rb
This increases readability, proposal in #137.
=> Rename file-change related DSL attributes

.gitignore, CHANGELOG.md, lib/danger/ci_source/local_git_repo.rb, lib/danger/commands/local.rb, lib/danger/request_sources/github.rb, spec/sources/github_spec.rb, spec/sources/local_git_repo_spec.rb
Needs some passing specs before it's a wizard.
<boop>
=> Adding support for enterprisey GitHub

lib/danger/ci_source/local_git_repo.rb
Did a little code cleanup to make the code a little more readable, and DRY it up a little.
=> Tried to simplify the code a little #trivial

lib/danger/dangerfile.rb
This will allow us to see it, without messing up the layout in CI.
Long text for demo:
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
=> Show full PR body, wrapping at 80 characters #trivial

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 0.6.5 release #trivial

Dangerfile
=> Added check for gemspec file for external contributors #trivial

README.md
=> Added Slack to README #trivial

CHANGELOG.md, danger.gemspec, fastlane/Fastfile, lib/danger/commands/init_helpers/interviewer.rb, lib/danger/scm_source/file_list.rb, lib/danger/scm_source/git_repo.rb, lib/danger/standard_error.rb, lib/danger/version.rb, spec/file_list_spec.rb, spec/sources/git_spec.rb
Fixes https://github.com/danger/danger/issues/82
=> Added new modified_files.include?("pattern*") method

Dangerfile
=> Fixing gemspec warning #trivial

lib/danger/ci_source/local_git_repo.rb
Show an actual error message if there haven't been any PRs yet
=> Fixed danger local crash when there are no recent PRs #trivial

lib/danger/request_sources/github.rb
=> Prevent snake_cased_variables to be parsed as emphasis #trivial

lib/danger/version.rb
=> Version bump #trivial

CHANGELOG.md
=> Updated changelog for release #trivial

CHANGELOG.md, lib/danger/dangerfile_dsl.rb
=> [Ready] Added auto-follow of http redirects

CHANGELOG.md, Dangerfile, lib/danger/ci_source/xcode_server.rb, spec/sources/xcode_server_spec.rb
Feature request from issue #171 
This will only work if use [Buildasaur](https://github.com/czechboy0/Buildasaur) to build PR on Xcode Server.
=> Add xcode_server ci_source;

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 0.7.2 release #trivial

CHANGELOG.md, lib/danger/commands/init.rb
I ran though `danger init` with Danger to try and get her feel for the copy, this makes it feel more like her words and she spotted a bunch of typos.
=> Danger's feedback on init #trivial

lib/danger/plugin.rb
Object#send will call method_missing internally if necessary
=> [Plugin] Clean up method_missing #trivial

CHANGELOG.md, lib/danger/scm_source/git_repo.rb, spec/sources/git_spec.rb
Add a commit accessor in the git scm source
=> Add `commits` for the Git SCM source

Dangerfile
Was requested in https://github.com/danger/danger/pull/181#issuecomment-211677536.
=> Allow checking pr_body for #trivial tag

lib/danger/core_ext/string.rb, lib/danger/request_sources/github.rb, spec/string_spec.rb
=> Message pluralisation #trivial

CHANGELOG.md, lib/danger/version.rb
=> Preparation for 0.7.3 release #trivial

VISION.md
Tried to codify a little bit of the private conversations, and the public conversations about where Danger is and where it feels like she's heading. Would love opinions, you don't see my title as "Vision Dictator" for Danger ;)
/cc @KrauseFx  @dbgrandi @jeroenvisser101 @marcelofabri @Antondomashnev
=> Initial work on VISION file #trivial

README.md
=> Add section about integrations #trivial

CHANGELOG.md, lib/danger/commands/runner.rb
=> Support CLAide-based Danger plugins

CHANGELOG.md, lib/danger/ci_source/local_git_repo.rb, lib/danger/version.rb
Usual bits and pieces, and I caught a bug when testing. Tests pass cause it was looking for an error 👯
=> Prepare to Release 0.7.4

README.md
This info was duplicated, so I grouped it and added some polish.
=> [README] CI notes

README.md
Unintentional deletion in https://github.com/danger/danger/pull/199.
=> [README] Readd Xcode CI builds

README.md
Fixes https://github.com/danger/danger/issues/202
=> Fixed dead links in README #trivial

README.md
Should help people with similar issues as described in #206.
@daniel-beard @dbgrandi can you confirm that with this documentation, one would be able to set this up?
=> Add section about GitHub Enterprise #trivial

README.md
Danger is gendered in `README.md` several times as female, but then subsequently as neuter. Let's be consistent 🙆
=> [README] Corrected metaphysics

fastlane/README.md
Updates some of the auto-generated files from Fastlane
=> Updated fastlane URLs

CHANGELOG.md, README.md, lib/danger/ci_source/drone.rb, spec/sources/drone_spec.rb
Almost identical to Travis CI, I just replaced variable names with the ones from http://readme.drone.io/usage/variables/
=> Add Drone CI support

Dangerfile
=> Added @dbgrandi to Dangerfile #trivial

Dangerfile
Builds on top of #222 to let us look up existing members.
=> Use GitHub to check for org members

CHANGELOG.md, lib/danger/ci_source/semaphore.rb, spec/lib/danger/ci_sources/semaphore_spec.rb
=> Support Semaphore CI

.travis.yml, CHANGELOG.md, lib/danger/danger_core/dangerfile.rb
=> Add ruby 2.3 support

lib/danger/commands/local.rb, lib/danger/version.rb
=> Prepare for 0.8.0

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 0.8.1

lib/danger/request_source/github.rb, spec/lib/danger/ci_sources/github_spec.rb
Fixing a small bug that was introduced on #247 when using a custom danger_id 😬
=> Fix deleting old comment when using custom danger_id #trivial

lib/danger/commands/runner.rb
We can eventually make it fancier if we want - #trivial
=> [Runner] more friendly error reporting via CLAide

lib/danger/ci_source/ci_source.rb, lib/danger/danger_core/environment_manager.rb
Basically the same thing that was done for #221 #trivial
=> Use inherited hook for CISource instead of enumerating symbols

CHANGELOG.md, README.md, lib/danger/ci_source/teamcity.rb, spec/lib/danger/ci_sources/teamcity_spec.rb
This pull request adds basic support for TeamCity CI
=> Add support for TeamCity

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 0.8.2

CHANGELOG.md, lib/danger/request_source/github.rb, spec/lib/danger/request_sources/github_spec.rb
Fix for #264, I'd say it's #trivial
=> Fix commit status updating

CHANGELOG.md, lib/danger/request_source/github.rb, lib/danger/scm_source/git_repo.rb, spec/lib/danger/commands/runner_spec.rb
Resolves #266
Not really sure we need a changelog entry for that ¯\_(ツ)_/¯
=> Assume the local HEAD is the PR's head commit

CHANGELOG.md, danger.gemspec, lib/danger.rb, lib/danger/commands/init.rb, lib/danger/commands/init_helpers/interviewer.rb, lib/danger/commands/local.rb, lib/danger/commands/new_plugin.rb, lib/danger/commands/runner.rb, lib/danger/danger_core/dangerfile.rb, lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb, spec/lib/danger/danger_core/dangerfile_spec.rb, spec/lib/danger/import_spec.rb, spec/spec_helper.rb
fixes https://github.com/danger/danger/issues/132
=> Use Cork for output

CHANGELOG.md, lib/danger/danger_core/dangerfile.rb, lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb, spec/lib/danger/danger_core/dangerfile_spec.rb
=> Print a list of results

lib/danger/ci_source/ci_source.rb
#271 but with feedback ;)
#trivial
=> Adds a require for set in the ci_source at the top - fixes #271

lib/danger/commands/init.rb
=> Don't use local git repo CI source to get repo slug. #trivial

README.md
It seems obvious but folks like complete instructions...
=> Added bundle install step

.travis.yml, CHANGELOG.md, danger.gemspec, lib/danger/version.rb, spec/lib/danger/plugin_support/plugin_parser_spec.rb
=> Release for 0.8.3

README.md
=> Updated wording.

CHANGELOG.md, lib/danger/commands/init.rb, lib/danger/version.rb
=> Prepare for 0.8.3

CHANGELOG.md, lib/danger/plugin_support/plugin_parser.rb, spec/lib/danger/plugin_support/plugin_parser_spec.rb
=> Adds method params to the parser, removes some methods we don't want

CHANGELOG.md, lib/danger/danger_core/plugins/dangerfile_git_plugin.rb, lib/danger/danger_core/plugins/dangerfile_github_plugin.rb, lib/danger/danger_core/plugins/dangerfile_import_plugin.rb, lib/danger/plugin_support/plugin_parser.rb, spec/lib/danger/plugin_support/plugin_parser_spec.rb
Docs / Ref look great, so it was time to make the inline docs 100%.
=> Documentation  Audit

CHANGELOG.md, lib/danger/commands/local.rb, lib/danger/request_source/github.rb, spec/lib/danger/commands/runner_spec.rb
Uses the environment manager's class functions for the commit references
=> Fix wrong head base commits (fixes #304)

CHANGELOG.md, lib/danger/version.rb
Mainly cause I want @justMaku's work out there asap.
=> Prepare for 0.8.5

CHANGELOG.md, lib/danger/commands/init.rb
=> [Init] Warn about storing Access Tokens in the repo

CHANGELOG.md, lib/danger/commands/init.rb
Make link instructions in onboarding OS aware
=> Make link open message OS-agnostic

CHANGELOG.md, lib/danger/version.rb
=> Update for 0.9.0

CHANGELOG.md, lib/danger/ci_source/local_git_repo.rb, lib/danger/scm_source/git_repo.rb, spec/lib/danger/ci_sources/git_spec.rb, spec/lib/danger/ci_sources/local_git_repo_spec.rb, spec/lib/danger/request_sources/request_source_spec.rb
This pull request addresses #331.
After applying this PR, Danger passes all tests on Windows.
=> Remove GNU utilities

appveyor.yml
Should get the windows CI green with this.
=> Add Appveyor file for CI

lib/danger/ci_source/buildkite.rb, lib/danger/ci_source/circle.rb, lib/danger/ci_source/drone.rb, lib/danger/ci_source/jenkins.rb, lib/danger/ci_source/local_git_repo.rb, lib/danger/ci_source/semaphore.rb, lib/danger/ci_source/surf.rb, lib/danger/ci_source/teamcity.rb, lib/danger/ci_source/travis.rb, lib/danger/ci_source/xcode_server.rb
Mainly so that I can make the README / danger.systems use these programmatically to link to their respective pages.
#trivial
=> Add urls to the classes for CI types

CHANGELOG.md, lib/danger/request_source/github.rb
Fixes https://github.com/danger/danger/issues/106
=> Don't mention that Danger needs write access if the repo is OSS.

Rakefile
=> Removed fastlane rake tasks #trivial

README.md
=> Add org Dangerfile docs #trivial

CHANGELOG.md, lib/danger/version.rb
Wanted to get 0.10.1 out, so that the docs aren't out of date 👯
=> Prepare for the release of 0.10.1

CHANGELOG.md, lib/danger/danger_core/plugins/dangerfile_github_plugin.rb, spec/lib/danger/plugins/dangerfile_github_plugin_spec.rb
=> Adding html_link to the GitHub plugin

lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
Will probably have conflicts with https://github.com/danger/danger/pull/359 - but I was going to ask for some examples anyway 👍
=> Add some more examples to the github plugin #trivial

CHANGELOG.md, lib/danger/commands/plugins/plugin_readme.rb
Shame, could have caught this with some command tests pretty easily. This might be an easy one to cover in the future.
=> README generator fix

README.md
=> Add link to plugin guide #trivial

README.md
=> Remove spaces before pry sample code #trivial

README.md
=> Remove bully in README #trvial

danger.gemspec
Updated the gemspec gem description
=> Update gem description #trivial

CHANGELOG.md, lib/assets/DangerfileTemplate
Looks like it currently is old syntax.
=> Add support for 2.0 in the init template

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 2.0.1

CHANGELOG.md, lib/danger/helpers/comments_helper.rb, spec/lib/danger/helpers/comments_helper_spec.rb, spec/lib/danger/request_sources/github_spec.rb
=> \n now works in HTML tables

CHANGELOG.md, lib/danger/version.rb
=> Prepare for release of 2.1.0

lib/danger/ci_source/jenkins.rb, lib/danger/ci_source/semaphore.rb, lib/danger/ci_source/teamcity.rb, lib/danger/ci_source/travis.rb, lib/danger/ci_source/xcode_server.rb
Makes the inline docs consistent 👍
=> Improve the docs for the site #trivial

README.md
I don't think this is very English, but I could have given be wrong.
=> Fix: removed extra have.

CHANGELOG.md, danger.gemspec, lib/danger/commands/plugins/plugin_readme.rb, lib/danger/helpers/comments_helper.rb, spec/lib/danger/helpers/comments_helper_spec.rb, spec/lib/danger/request_sources/github_spec.rb
relates to: https://github.com/danger/danger/issues/394
=> replaces redcarpet with kramdown, to avoid jruby foo

CHANGELOG.md, lib/danger/version.rb
=> Prepare for a release

CHANGELOG.md, lib/danger/commands/init.rb
Fixes a few minor annoyances around the `init` feature.
=> Improvements to danger init - fixes #341 #389 #239

.editorconfig
#trivial
Improve consistency of styles and conventions
from all contributors. See http://editorconfig.org/
=> [Project] Add .editorconfig

CHANGELOG.md, lib/danger/ci_source/circle.rb
https://github.com/danger/danger/issues/410 and https://github.com/danger/danger/issues/408
Lets it use just the environment variables if they exist, instead of always relying on the API too.
=> Add some more validations to the circle CI checking

CHANGELOG.md, lib/danger/version.rb
=> Prepare for release

lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
=> Update link for pr_json fixture #trivial

lib/danger/comment_generators/github.md.erb
Previous message was missing a `td`
=> Fix html in truncating message #trivial

lib/danger/request_source/github.rb
Just removed a tiny bit of duplication and fixed an insignificant typo 😇 I don't quite get the `issues` naming in there, aren't we talking about `comments` here?
=> Hk tiny GitHub fixes #trivial

CHANGELOG.md, lib/danger/version.rb
Smallish release, but should be useful.
=> prepare for 2.1.3

CHANGELOG.md, lib/danger/version.rb
Lets give these circles a chance.
=> Prepare for 2.1.4

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 2.1.5

lib/danger/request_source/github.rb, spec/lib/danger/request_sources/github_spec.rb
I was fairly confused about the `issues` variables, as danger creates a `comment` as far as I come to experience it :) I hope I didn't miss anything, gotta catch 'em all haha.
=> Rename "issues" to "comments" in github context #trivial

CHANGELOG.md, README.md, VISION.md
This PR copy edits the readme and vision statement.
=> Copyedit the readme and vision statement

lib/danger/commands/init.rb
=> Fix crash in init #trivial

CHANGELOG.md, lib/danger/version.rb
I think #442 is important enough to do a release
=> Prepare for 2.1.6

CHANGELOG.md, lib/danger/request_source/github.rb, lib/danger/request_source/gitlab.rb, spec/lib/danger/commands/runner_spec.rb, spec/lib/danger/request_sources/github_spec.rb, spec/lib/danger/request_sources/gitlab_spec.rb
Sister PR for danger.systems incoming
=> K0nserv consolidate api env variables

CHANGELOG.md, lib/danger/ci_source/buildkite.rb, lib/danger/ci_source/jenkins.rb, lib/danger/ci_source/teamcity.rb, spec/lib/danger/ci_sources/buildkite_spec.rb, spec/lib/danger/ci_sources/jenkins_spec.rb, spec/lib/danger/ci_sources/teamcity_spec.rb
Also cleans up the tests a bit and expands them
to test a larger surface area.
closes: #447
=> [#447] Update CI Sources that support GitLab

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 3.0 release

CHANGELOG.md, lib/danger/version.rb
Cool cool - thanks @hanneskaeufler for the patch
=> Prepare for 3.0.1

CHANGELOG.md, lib/danger/ci_source/jenkins.rb, spec/lib/danger/ci_sources/jenkins_spec.rb, spec/lib/danger/ci_sources/teamcity_spec.rb
Feel free to squash this down into just one commit.
=> Spelling and grammar

spec/support/github_helper.rb
=> [Specs] Fix carless copying #trivial

CHANGELOG.md, lib/danger/commands/local.rb
=> Remove the global dangerfile lookup in danger local - fixes #461

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 3.0.2

CHANGELOG.md, lib/danger/ci_source/jenkins.rb, spec/lib/danger/ci_sources/jenkins_spec.rb
=> Uses ghprbPullId as the env var key again

lib/danger/ci_source/circle.rb, lib/danger/ci_source/local_git_repo.rb, lib/danger/ci_source/semaphore.rb, lib/danger/ci_source/surf.rb, lib/danger/ci_source/travis.rb, lib/danger/ci_source/xcode_server.rb, lib/danger/scm_source/git_repo.rb, spec/lib/danger/ci_sources/circle_spec.rb, spec/lib/danger/ci_sources/local_git_repo_spec.rb, spec/lib/danger/ci_sources/semaphore_spec.rb, spec/lib/danger/ci_sources/surf_spec.rb, spec/lib/danger/ci_sources/travis_spec.rb, spec/lib/danger/ci_sources/xcode_server_spec.rb, spec/lib/danger/plugins/dangerfile_gitlab_plugin_spec.rb, spec/support/github_helper.rb, spec/support/gitlab_helper.rb
This PR increases test coverage for CI Sources and improves the structure of the tests a bit by introducing some more grouping and use of describe/context.
*Coverage before*
*Coverage after*
=> [CISource] Improve tests coverage and structure #trivial

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 3.0.3

lib/danger/commands/init.rb
also should be lower case danger
=> Remove new-line after repo slug #trivial

CHANGELOG.md, lib/danger/ci_source/bitrise.rb, spec/lib/danger/ci_sources/bitrise_spec.rb
:tada::warning: **This is my first ever Ruby PR** :warning::tada:
We use Bitrise for our CI, and we’d love to use Danger!
I’m a Ruby n00b. In fact this is my first go at writing Ruby code for something real, so please let me know if I missed anything or something seems wrong :smile:.
=> Adding support for Bitrise

CHANGELOG.md, lib/danger/version.rb
Got a bunch of useful small fixes, and the Bitrise support coming in.
=> Prepare for 3.1.0

CHANGELOG.md, lib/danger/version.rb
Gotta fix those import dangerfiles
=> Prepare for 3.1.1

CHANGELOG.md, lib/danger/helpers/comments_helper.rb
Tiny patch to this ✨ awesome project 👍 
Also my editor cleans up some trailing spaces in CHANGELOG.md.
=> One less variable assignment in comments_helper.rb

CHANGELOG.md, lib/danger/scm_source/git_repo.rb, spec/lib/danger/scm_source/git_repo_spec.rb
Proposed change form #476. Need to test the change though, I'll give it a try tomorrow on a Travis machine.
=> [Git] Set env variable to en_US-UTF8

CHANGELOG.md
Mainly documentation, will need to do some work in http://Danger.systems afterwards.
=> Prepare for 3.2.0

CHANGELOG.md
Mistakenly removed, this PR adds it back 😊
=> Add back the master section of CHANGELOG.md [ci skip]

danger.gemspec
Change homepage url to https 🔒
=> Use https homepage url on rubygems.org

CHANGELOG.md, lib/danger.rb, spec/danger_spec.rb
- Move gem name to a constant
- if + empty? over unless + any?
- Add a spec
=> Minor improvements to Danger.gem_path

lib/danger/danger_core/plugins/dangerfile_bitbucket_server_plugin.rb, lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
No API method, so that Bitbucket example doesn't actually work.
=> Remove impossible Bitbucket example, fix some terms in GitLab docs #trivial

CHANGELOG.md, lib/danger/request_source/request_source.rb
This PR:
- upadte comment
- the repo_slug is not being used, remove it
=> Update comment and remove unused referred name in RequestStore base

CHANGELOG.md, lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
=> CHANGELOG update for 321

lib/danger/danger_core/dangerfile.rb, spec/danger_spec.rb
#trivial @orta this simplifies some code I didn't have a change to review before you merged
=> [Dangerfile] Simplify text wrapping code

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 3.2.2

.editorconfig
Follow up of https://github.com/danger/danger/pull/544#r78943729, 💅 /cc @dblock
=> Enable trim_trailing_whitespace for all files [ci skip]

CHANGELOG.md, lib/danger/core_ext/string.rb, spec/lib/danger/core_ext/string_spec.rb
🏡 This method is not in used, remove?
=> Remove unused danger_class method

CHANGELOG.md, lib/danger/core_ext/string.rb
Add docs for two String methods + ❄️ strings
=> Add docs for String #danger_pluralize & #danger_underscore

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 3.3.0

lib/danger/ci_source/support/merged_pull_request_finder.rb
=> Fix instance variable copypasta typos #trivial

lib/danger/danger_core/executor.rb, spec/lib/danger/danger_core/executor_spec.rb
Add a spec for `Executor#post_results` 🍬
=> Add a spec for Executor#post_results #trivial

CHANGELOG.md
I was about to amend and re-push the changelog but got merged too fast 💨
=> Fix changelog for #564

CHANGELOG.md, lib/danger/version.rb
3.3.1 all credit goes to @JuanitoFatas while I've been doing CocoaPods stuff
=> 3.3.1 - Prepare for release

CHANGELOG.md, lib/danger/request_sources/bitbucket_cloud.rb, lib/danger/request_sources/bitbucket_server.rb, spec/lib/danger/request_sources/bibucket_cloud_spec.rb, spec/lib/danger/request_sources/bibucket_server_spec.rb
Fixes #573. I wonder why tests did not catch this 🤔 => Tests added.
=> Add missing require statements in bitbucket cloud and server

README.md
Add Travis CI badge to README.md:
✨✨✨
=> Add Travis CI badge to README.md #trivial

CHANGELOG.md, lib/danger/request_sources/github.rb, spec/lib/danger/request_sources/github_spec.rb
This PR simplifies the init of Octokit client 🎋
=> Simplify initialization of Octokit client in request_sources/github.rb

lib/danger/danger_core/environment_manager.rb, lib/danger/request_sources/request_source.rb, spec/lib/danger/danger_core/environment_manager_spec.rb, spec/lib/danger/request_sources/request_source_spec.rb
@orta I made some refactorings for #579.
=> Patch/setup error #trivial

CHANGELOG.md, Rakefile, lib/danger/commands/local.rb, lib/danger/danger_core/environment_manager.rb, lib/danger/danger_core/executor.rb, lib/danger/request_sources/bitbucket_cloud.rb, lib/danger/request_sources/bitbucket_server.rb, lib/danger/request_sources/github.rb, lib/danger/request_sources/gitlab.rb, lib/danger/request_sources/request_source.rb, spec/lib/danger/danger_core/environment_manager_spec.rb, spec/lib/danger/request_sources/request_source_spec.rb, spec/spec_helper.rb
Danger is sleeping, so I don't have too much time, but this is the start of improving the no token setup error messaging. Will finish tomorrow.
=> Improving the no token error during setup

lib/danger/commands/init.rb
`s/privilidged/privileged/` and nothin' more. 🐴
=> Fixes typo in init.rb #trivial

.vscode/settings.json, CHANGELOG.md, lib/danger/commands/init.rb, lib/danger/commands/runner.rb, lib/danger/danger_core/dangerfile.rb, lib/danger/danger_core/executor.rb, lib/danger/scm_source/git_repo.rb, spec/lib/danger/commands/runner_spec.rb, spec/lib/danger/danger_core/dangerfile_spec.rb, spec/lib/danger/danger_core/executor_spec.rb, spec/lib/danger/request_sources/github_spec.rb, spec/lib/danger/request_sources/gitlab_spec.rb, spec/spec_helper.rb, spec/support/executor_helper.rb
OK, so, Danger 🙆  is almost done up getting changed, don't have time to finish this - it actually is _done_ feature wise, but I'm starting to get my head wrapped around what it takes to actually make the executor testable - feel like it's getting there.
WIP till tests.
=> Support for failing on errors

CHANGELOG.md, lib/danger/version.rb
Usual changelog + version bump
=> Prepare for 3.4.0 🎉

.rspec
Let's remove the duplication 🌎
=> Remvoe duplicate RSpec CLI option #trivial

CHANGELOG.md, lib/danger/version.rb
Usual changelog + version bump
=> Prepare for 3.4.1 🎉

Dangerfile
Release should be CHANGELOG.md + version.rb?
=> Is version bump Should be CHANGELOG.md + lib/danger/version.rb #trivial 

CHANGELOG.md, lib/danger/version.rb
/3//////2//////////K//⚡///////////////////
////4/////////O//////⚡///////////////////
=> Prepare for 3.4.2

CHANGELOG.md, lib/danger/version.rb
/th//re///ee/////fi////ft//// y ///////////////////
=> Update to 3.5.0

CHANGELOG.md, lib/danger/version.rb
⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡
⚡⚡⚡3⚡5⚡1⚡⚡⚡
⚡⚡⚡⚡⚡⚡⚡⚡⚡⚡
=> Prepare for v3.5.1

.travis.yml, Gemfile, bin/chandler
I don't want more process on releases, so this let's travis and Chandler do everything for us 👍
=> Adds Chandler to run on every tag

CHANGELOG.md
=> Typo in CHANGELOG #trivial

.travis.yml, CHANGELOG.md, lib/danger/version.rb
✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ 
///🚫3////5🚫///🚫3/////////⚡//////////////////
✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨ ✨
=> Prepare for v3.5.3

CHANGELOG.md
[Preview new CHANGELOG.md](https://github.com/danger/danger/blob/105cafc20d9feddc1cce3f3a26004a9a2c747046/CHANGELOG.md).
Missing git tags:
| Missing tag| introduced commit |
|------------|-------------------|
| v0.6.0     | be16fdb0          |
| v0.6.5     | bf4cfead          |
| v0.7.0     | 3a6a212f          |
| v0.7.1     | 917113db          |
| v0.7.2     | 0b0e428b          |
=> Add Full Changelog to CHANGELOG.md #trivial

CHANGELOG.md, lib/danger/version.rb
💨 💨 💨 💨 💨 💨 💨 💨 💨 💨 💨 
/////////⚡//⚡3/////5⚡////⚡4/////////⚡////
💨 💨 💨 💨 💨 💨 💨 💨 💨 💨 💨 
[Full Changelog](https://github.com/danger/danger/compare/v3.5.3...v3.5.4)
=> Release v3.5.4

CHANGELOG.md, lib/danger/version.rb
🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 
//⚡///////⚡//3/////5//⚡//5///⚡//////⚡////
🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰 🇭🇰
=> Release v3.5.5

.github/issue_template.md
so that helps us to better debug the issue.
=> Ask Dangerfile when reporting an issue #trivial

CHANGELOG.md, lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb, lib/danger/request_sources/github.rb, lib/danger/request_sources/gitlab.rb, lib/danger/request_sources/support/get_ignored_violation.rb, spec/lib/danger/request_sources/support/get_ignored_violation_spec.rb
Fixes #650.
Fixes doc missing double quote:
=> Improves Danger ignore parsing

CHANGELOG.md, lib/danger/version.rb
/❤/❤/❤/❤/❤/❤/////❤////////⚡////////❤//////❤/////❤
❤ THANKS FOR H❤LPING O❤T
❤ 3.6.0
////❤/❤/////❤/////////⚡///❤/////////////❤///❤
=> Version bump for 3.6.0

CHANGELOG.md, Gemfile, circle.yml, danger.gemspec, lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb, lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb, lib/danger/request_sources/gitlab.rb, lib/danger/version.rb, spec/lib/danger/danger_core/dangerfile_spec.rb
Planning on only being https://github.com/danger/danger/issues/506 and https://github.com/danger/danger/pull/483 / https://github.com/danger/danger/issues/482
Will need subsequent docs updates too.
=> Work for 4.0

lib/danger/danger_core/dangerfile.rb
Fixes rubocop offense mentioned in https://github.com/danger/danger/pull/657#issuecomment-257561740.
=> Fix an rubocop offense #trivial

CHANGELOG.md, lib/danger/request_sources/bitbucket_cloud.rb, lib/danger/request_sources/bitbucket_server.rb
This adds the missing support for —new-comment on Bitbucket
=> --new-comment support for Bitbucket

CHANGELOG.md, lib/danger/version.rb
It's the release train Choo-choo
```
/4/////4//0/////0//1////1⚡///////////////////
///4/4//////0/0/////1/1//⚡///////////////////
```
=> Prepare for v4.0.1

.rubocop.yml, CHANGELOG.md, danger.gemspec, lib/danger/plugin_support/gems_resolver.rb, lib/danger/plugin_support/plugin_file_resolver.rb, spec/fixtures/gemspecs/danger-rubocop.gemspec, spec/lib/danger/plugin_support/gems_resolver_spec.rb, spec/lib/danger/plugin_support/plugin_file_resolver_spec.rb
This PR:
- Improves a Rubocop FIXME: Metrics/BlockLength
- Add a spec for testing part of the functionality of plugin_file_resolver.rb
=> Improves PluginFileResolver #trivial

lib/danger/commands/init.rb
include `#trivial` in the title or the body of the PR and this is skipped.
We also request that you fill in the body of your PR, a title should be tweet length, but
ideally you can explain the PRs reasoning in the …
=> Remove extra space #trivial

CHANGELOG.md, lib/danger/version.rb
🎉 Release 4.0.3 🎉 
✨ ✨ ✨ Highlight
Prints an error when we failed to post comment on Bitbucket server, awesome work by @Buju77
=> Release v4.0.3

circle.yml
Fixes the build failure from external contributors on Circle 👍
=> Don't run danger on external PRs in Circle

CHANGELOG.md, lib/danger/version.rb
=> Prepare for release 4.0.5

CHANGELOG.md, lib/danger/danger_core/plugins/dangerfile_github_plugin.rb, lib/danger/version.rb
=> Prepare for 4.1.0

CHANGELOG.md
=> Minor Docs fix

CHANGELOG.md, lib/danger/version.rb
=> 4.1.1: Prepare for release

CHANGELOG.md, danger.gemspec, lib/danger.rb
Handles the same transition seen in https://github.com/CocoaPods/Xcodeproj/pull/463
=> Use colored2 instead of colored

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 420

CHANGELOG.md, lib/danger/comment_generators/github.md.erb, spec/lib/danger/helpers/comments_helper_spec.rb
This PR fixes a small issue with #716
=> Fix for #716

lib/danger/request_sources/github/github.rb, spec/lib/danger/helpers/comments_helper_spec.rb
Reduces knowledge about that particular string in the codebase
=> Use the Comment#generated_by_danger? method #trivial

lib/danger/commands/runner.rb
=> Fix spelling mistake #trivial

CHANGELOG.md, lib/danger/version.rb
=> Prepare for v4.2.2

lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb
Updates the docs about file and line - fixes #741
=> Add a note about file:line: #trivial

.rubocop.yml, CHANGELOG.md, Gemfile, danger.gemspec, lib/danger/commands/init.rb
This should fix the suspicious issues with rubocop, it wasn't in the Gemfile at all.
Also updates some forks now that all PRs are merged.
=> Updates Gemfile

CHANGELOG.md, lib/danger/version.rb
=> Prepare for v4.3.0

CHANGELOG.md, lib/danger/version.rb
=> Prepare for v4.3.1

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 4.3.2

.rubocop.yml, .travis.yml, Rakefile, lib/danger/commands/runner.rb, lib/danger/danger_core/dangerfile.rb, lib/danger/danger_core/plugins/dangerfile_github_plugin.rb, lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
Force us to use the bundle'd rubocop
=> [Fix] Try make sure we use bundled rubocop #trivial

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 4.3.4

CHANGELOG.md, lib/danger/request_sources/github/github.rb
Simple PR to fix an undefined method call.
Fixes #775
=> Fixed undefined method call String#start_with

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 4.3.5

CHANGELOG.md, lib/danger/version.rb
I know, major version bump, but it's a breaking change and we are doing real semver.
=> Prepare for v5.0.0

CHANGELOG.md, lib/danger/request_sources/bitbucket_server_api.rb, spec/lib/danger/request_sources/bibucket_server_spec.rb, spec/lib/danger/request_sources/bitbucket_server_api_spec.rb
Added fix for https://github.com/danger/danger/issues/784.
I am not a ruby expert so I am not sure if this code will work 💯%.
=> added url scheme in host name. Added support for backword compatibility

CHANGELOG.md, lib/danger/version.rb
=> Update for 5.0.1

CHANGELOG.md, lib/danger/version.rb
=> Update for 5.0.2

.vscode/settings.json, CHANGELOG.md, lib/danger/request_sources/bitbucket_server_api.rb
Adds a check before running the includes - thank #790
=> Adds a fix for #790

CHANGELOG.md, lib/danger/version.rb
=> Prepare for v5.0.3

lib/danger/commands/init.rb
Fixes https://github.com/danger/danger/issues/734
=> Update init.rb #trivial

CHANGELOG.md, lib/danger/ci_source/drone.rb, spec/lib/danger/ci_sources/drone_spec.rb
This reinstates the support for version pre 0.6 while still
maintaining support for version 0.6.
=> [Drone] Support old and new version

CHANGELOG.md, lib/danger/version.rb
=> Prepare for v5.1.0

CHANGELOG.md, lib/danger/version.rb
=> Prepare for v5.1.1

CHANGELOG.md, lib/danger/version.rb
=> Release 5.2.1

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 5.2. release

.rubocop.yml, spec/lib/danger/commands/init_helpers/interviewer_spec.rb, spec/lib/danger/danger_core/dangerfile_spec.rb, spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb, spec/lib/danger/helpers/array_subclass_spec.rb, spec/lib/danger/plugin_support/plugin_parser_spec.rb, spec/lib/danger/request_sources/bitbucket_server_api_spec.rb
=> Fix rubocop offenses #trivial

CHANGELOG.md, lib/danger/danger_core/plugins/dangerfile_git_plugin.rb, spec/lib/danger/danger_core/dangerfile_spec.rb, spec/lib/danger/danger_core/plugins/dangerfile_git_plugin_spec.rb
Exposes `diff` object to Dangerfile dsl. Resolves #814 .
```
p git.diff 
=> 
#<Git::Diff:0x007fcb8f9a1ae8
@base=
#<Git::Base:0x007fcb8fa27080
@index=
#<Git::Index:0x007fcb8fa26c70
@path="/Users/sleekybadger/code/danger_test/.git/index">,
@lib=
#<Git::Lib:0x007fcb8f99dc18
@git_dir="/Users/sleekybadger/code/danger_test/.git",
@git_index_file="/Users/sleekybadger/code/danger_test/.git/index",
@git_system_env_variables=
{"GIT_DIR"=>nil,
"GIT_WORK_TREE"=>nil,
"GIT_INDEX_FILE"=>nil,
"GIT_SSH"=>nil},
@git_work_dir="/Users/sleekybadger/code/danger_test",
@logger=nil,
@path=nil>,
@logger=nil,
@repository=
#<Git::Repository:0x007fcb8fa26d88
@path="/Users/sleekybadger/code/danger_test/.git">,
@working_directory=
#<Git::WorkingDirectory:0x007fcb8fa26e28
@path="/Users/sleekybadger/code/danger_test">>, …
```
=> Add ability to get whole diff

lib/danger/ci_source/jenkins.rb
Adds some extra documentation to Jenkins so that less people are likely to his https://github.com/danger/danger/issues/828
=> Update jenkins.rb #trivial

CHANGELOG.md, lib/danger/request_sources/github/github.rb
This isn't _super well_ tested code: the detection of existing comments for deletion or updating. So I wanted to get a sense of CI etc.
If it's all green I'm OK with giving it a shot. It reads to me to be 👍
=> Look at fixing accidental dupes - re: #835

CHANGELOG.md, lib/danger/request_sources/github/github.rb, lib/danger/version.rb
=> Prepare for 5.3.1

CHANGELOG.md, lib/danger/version.rb
=> Prepare for v5.3.2

CHANGELOG.md, lib/danger/ci_source/teamcity.rb
Give details on how to provide the environment variables necessary to run Danger on TeamCity.
=> Add to documentation for TeamCity CI setup

CHANGELOG.md, lib/danger/ci_source/buddybuild.rb
#trivial Update buddybuild doc to include link to tutorial
=> #trivial Update buddybuild doc to include link to tutorial

lib/danger/ci_source/bitrise.rb
Fix for broken code sample at http://danger.systems/guides/getting_started.html for Bitrise
Should I also indent the block with spaces? https://github.com/danger/danger/blob/master/lib/danger/ci_source/travis.rb#L13 is indented, but probably that's not required as e.g. https://github.com/danger/danger/blob/master/lib/danger/ci_source/teamcity.rb#L27 is not indented inside the tripple-backtick block.
What's the preferred format?
=> #trivial Formatting fix for Bitrise setup

CHANGELOG.md, lib/danger/version.rb
🏭 🍂 🏎 🌵 📲 
I don't have a mouse hooked up, so I can't copy image URLs.
=> Prepare for v5.3.4

CHANGELOG.md, lib/danger/commands/init.rb
Fixes #872. Not a biggie, but hey.
=> Consolidates pronoun use in `danger init`

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 5.3.5

CHANGELOG.md, lib/danger/version.rb
=> Version bump

CHANGELOG.md, lib/danger/version.rb
=> 542 Version bump

CHANGELOG.md, lib/danger/version.rb
[![543](https://user-images.githubusercontent.com/1000669/30410730-38283468-990d-11e7-9286-b5445178d79f.png)](https://en.wikipedia.org/wiki/Maryland_Route_543)
=> Release v5.4.3

CHANGELOG.md, lib/danger/version.rb
=> Prepare for release of 5.5.0

lib/danger/ci_source/circle.rb, spec/lib/danger/ci_sources/circle_spec.rb
Paired with https://github.com/danger/danger-js/pull/382
=> Take @sean-clayton's work from Danger JS to improve Circle CI support back to Ruby

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 5.5.2

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 5.5.3

lib/danger/danger_core/plugins/dangerfile_bitbucket_cloud_plugin.rb
This should have happened with my first PR regarding this issue on BitBucket Server, unfortunately I have overseen the same issue on BitBucket Cloud.
Verified the same issue existed on BitBucket Cloud and fixed it there as well.
Sorry for missing it on the first PR, at least it's fixed now I guess?
=> #trivial: Fixes Reviewers Example for BitBucket Cloud

README.md
It's about time we get some people in there?! :blush:
=> Add Spectrum badge to readme

CHANGELOG.md, lib/danger/version.rb
=> Prepare for 5.5.4

CHANGELOG.md, lib/danger/version.rb
[![book](https://user-images.githubusercontent.com/1000669/32705836-8c83092a-c85b-11e7-9bc1-dd1c56ad1613.gif)](https://en.wikipedia.org/wiki/555_timer_IC)
=> Release v5.5.5

CHANGELOG.md, lib/danger/commands/local.rb, lib/danger/commands/pr.rb, spec/lib/danger/commands/pr_spec.rb
From the feedback in #931 
I think the CLI could give a better example of what is up with local, and that pr won't post to the PR.
=> Improve the CLI docs for local/pr

CHANGELOG.md, lib/danger/version.rb
=> Prepare for the next release

CHANGELOG.md
- this shipped with 5.5.7, not 5.5.6 :)
=> Move TeamCity/Bitbucket CHANGELOG entry to 5.5.7

.rubocop.yml, CHANGELOG.md, danger.gemspec, spec/lib/danger/ci_sources/bitrise_spec.rb, spec/lib/danger/ci_sources/ci_source_spec.rb, spec/lib/danger/ci_sources/teamcity_spec.rb, spec/lib/danger/danger_core/dangerfile_spec.rb, spec/lib/danger/danger_core/plugins/messages_spec.rb, spec/lib/danger/request_sources/gitlab_spec.rb, spec/support/vsts_helper.rb
Fix GitHub security warnings, and style fixes after upgraded rubocop.
=> Security Updates for rubocop and yard

.rubocop.yml, CHANGELOG.md, lib/danger/ci_source/jenkins.rb, spec/lib/danger/ci_sources/jenkins_spec.rb
=> Better error handle when no env coming from Jenkins

CHANGELOG.md, lib/danger/ci_source/bitrise.rb, spec/lib/danger/ci_sources/bitrise_spec.rb
Initially reported in #980
Adds support for bitbucket cloud.
=> Adds support for bitbucket cloud

README.md
=> Missing apostrophe

CHANGELOG.md, lib/danger/ci_source/code_build.rb, spec/lib/danger/ci_sources/ci_source_spec.rb
=> Add CodeBuild support

CHANGELOG.md, lib/danger/request_sources/github/github.rb, spec/lib/danger/request_sources/github_spec.rb
My PR https://github.com/danger/danger/pull/1046 included wrong test related with backslash.
So the implementation is not correct.
This PR fix it.
=> Fix wrong test

appveyor.yml
Looks like appveyor is reding for #1085  and #1086 - this might fix it
=> Try get appveyor green

Dockerfile
=> Optimize dockerfile labels into 1 layer

CHANGELOG.md, lib/danger/ci_source/cirrus.rb, spec/lib/danger/ci_sources/ci_source_spec.rb
=> Add Cirrus CI support

CHANGELOG.md, lib/danger/ci_source/jenkins.rb
when use jenkins + gitlab + danger , jenkins.rb not have ‘project_url’，
=> Add project URL to Jenkins if available

CHANGELOG.md, lib/danger/ci_source/bitbucket_pipelines.rb, lib/danger/ci_source/teamcity.rb, lib/danger/request_sources/bitbucket_cloud.rb, lib/danger/request_sources/bitbucket_cloud_api.rb, spec/fixtures/bitbucket_cloud_api/oauth2_response.json, spec/lib/danger/request_sources/bitbucket_cloud_api_spec.rb, spec/support/bitbucket_cloud_helper.rb
Adds support for Bitbucket cloud authentication
=> Support Bitbucket cloud oath

.circleci/config.yml, .travis.yml, Gemfile, appveyor.yml
We should stay up to date on this
=> Update bundler gem

CHANGELOG.md, lib/danger/ci_source/codefresh.rb, spec/lib/danger/ci_sources/ci_source_spec.rb, spec/lib/danger/ci_sources/codefresh_spec.rb, spec/lib/danger/danger_core/executor_spec.rb, spec/support/ci_helper.rb
This PR introduces support of [Codefresh CI/CD](http://codefresh.io) system. 
The code was heavily inspired (I would even say ported) with TypeScript version of Danger - https://github.com/danger/danger-js/blob/master/source/ci_source/providers/Codefresh.ts
=> feat(codefresh): Codefresh Provider

CHANGELOG.md, lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb, lib/danger/version.rb
I spent longer than necessary figuring out how to include a Dangerfile from a gitlab repo, so here's an update to the error message and to the example :)
Thank you for the great tool!
=> Fix error message for dangerfile import #trivial

CHANGELOG.md, lib/danger/request_sources/bitbucket_cloud_api.rb
include `#trivial` in the title or the body of the PR and this is skipped.
We also request that you fill in the body of your PR, a title should be tweet length, but
ideally you can explain the PRs reasoning in the …
=> Bitbucket cloud api, migrating to 2.0

CHANGELOG.md, lib/danger/ci_source/azure_pipelines.rb, spec/lib/danger/ci_sources/ci_source_spec.rb
Pretty much the same environment variables as AppCenter
=> add support for azure pipeline

lib/danger/danger_core/plugins/dangerfile_local_only_plugin.rb
`+` string should be escaped on the regex
=> Fix wrong added lines regex

CHANGELOG.md, lib/danger/ci_source/bitrise.rb
Added a few lines of notes to help others setting up Danger with Bitrise and Bitbucket Server that might be using the Bitrise Close step a little out of the norm, like for firewall/vpn access from Bitrise to Bitbucket server.
=> Add docs to bitrise.rb for help in setup with stash and bitrise

CHANGELOG.md, lib/danger/ci_source/semaphore.rb, spec/lib/danger/ci_sources/semaphore_spec.rb, spec/support/ci_helper.rb
Updated the Semaphore CI strategy to version 2.0.
This is a breaking change, so I am not sure how to proceed.
=> Updated Semaphore to support 2.0

CHANGELOG.md, lib/danger/ci_source/bamboo.rb, spec/lib/danger/ci_sources/bamboo_spec.rb, spec/lib/danger/ci_sources/ci_source_spec.rb, spec/lib/danger/danger_core/environment_manager_spec.rb, spec/lib/danger/danger_core/executor_spec.rb, spec/support/ci_helper.rb
Hi there,
This PR adds support for Bamboo CI to Danger. 
Currently, it is only integrated with Bitbucket Server, as this is what I could test it against.
=> #985 Add Bamboo support

CHANGELOG.md, lib/danger/ci_source/bitbucket_pipelines.rb
- Typo fix on password env variable
- Fix Token Setup title
=> Fix Bitbucket Pipelines documentation

CHANGELOG.md, lib/danger/commands/runner.rb, lib/danger/commands/staging.rb, spec/lib/danger/commands/staging_spec.rb
Since until now `local` and `pr` require a working remote git, this adds the ability to run the current branch against a local master. [#1179](https://github.com/danger/danger/issues/1179).
=> adds staging command for local only run

Dockerfile, Gemfile, lib/danger/ci_source/github_actions.rb
I tried Danger in github actions workflow using this repository, then failed danger. https://github.com/duck8823/duci/runs/521732441#step:4:5
This is because the GitHub Actions command runs in a different directory than the WORKDIR in the Dockerfile.
So I changed it to specify the location of the Gemfile in the container.
https://github.com/duck8823/duci/runs/526090395?check_suite_focus=true#step:4:5
And update document..
Thanks.
=> #trivial Specify Gemfile location in Docker container

CHANGELOG.md, lib/danger/commands/local.rb, lib/danger/commands/pr.rb
=> Follow GitHub redirects

.github/workflows/CI.yml, Dangerfile
This should add a GitHub Action CI run for Danger on PRs
=> Adds a run on github actions to Danger

lib/danger/ci_source/teamcity.rb
Adds additional documentation for setting of GITHUB_PULL_REQUEST_ID
=> Teamcity GITHUB_PULL_REQUEST_ID docs update

README.md, lib/danger/ci_source/appcenter.rb, lib/danger/ci_source/appveyor.rb, lib/danger/ci_source/azure_pipelines.rb, lib/danger/ci_source/bitbucket_pipelines.rb, lib/danger/ci_source/buildkite.rb, lib/danger/ci_source/circle.rb, lib/danger/ci_source/concourse.rb, lib/danger/ci_source/drone.rb, lib/danger/ci_source/github_actions.rb, lib/danger/ci_source/gitlab_ci.rb, lib/danger/ci_source/screwdriver.rb, lib/danger/ci_source/teamcity.rb
This should fix code blocks showing up on one line on the website.
=> Fix incorrect code blocks #trivial

docs/guides/troubleshooting.md, docs/guides/what_does_danger_do.md
This is just a small typo fix.
Thank you.
=> Small typo fix in guides #trivial

.github/workflows/CI.yml
=> Run test on GH CI

.github/issue_template.md
This PR fixes a minor typo in issue_template.md.
=> Fix minor typo in issue_template.md #trivial

CHANGELOG.md, lib/danger/ci_source/gitlab_ci.rb, spec/lib/danger/ci_sources/gitlab_ci_spec.rb, spec/lib/danger/danger_core/plugins/dangerfile_danger_plugin_spec.rb
This addresses https://github.com/danger/danger/issues/1351.
=> Don't save environment as an instance variable in GitLabCI

CHANGELOG.md, Dockerfile
=> Docker image has an outdated ruby version

lib/danger/ci_source/bitrise.rb, lib/danger/ci_source/circle.rb, lib/danger/ci_source/gitlab_ci.rb, lib/danger/ci_source/jenkins.rb, lib/danger/comment_generators/gitlab_inline.md.erb, lib/danger/danger_core/plugins/dangerfile_local_only_plugin.rb, lib/danger/request_sources/vsts_api.rb, spec/fixtures/github_api/inline_comments_pr_diff.diff, spec/lib/danger/ci_sources/dotci_spec.rb, spec/lib/danger/ci_sources/jenkins_spec.rb, spec/lib/danger/request_sources/gitlab_spec.rb
Several typos were corrected in this PR.
=> Fix a few typos #trivial

CHANGELOG.md, lib/danger/ci_source/appcircle.rb, spec/lib/danger/ci_sources/appcircle_spec.rb, spec/lib/danger/ci_sources/ci_source_spec.rb, spec/lib/danger/danger_core/environment_manager_spec.rb, spec/lib/danger/danger_core/executor_spec.rb, spec/support/ci_helper.rb
- Added support for [Appcircle](https://appcircle.io/)
- Added tests same as the other providers
- Modified CHANGELOG.md
=> Appcircle Support

.circleci/config.yml
This PR is fix an indentation for YAML file.
=> Fix an indentation for YAML file #trivial

lib/danger/danger_core/plugins/dangerfile_git_plugin.rb
=> Fix example for checking merge commit

CHANGELOG.md, lib/danger/commands/local.rb, spec/lib/danger/commands/local_spec.rb
Close https://github.com/danger/danger/issues/1362
=> Pass danger_id to danger local

danger.gemspec
Update gemspec to support octokit 7.x.
=> Support octokit 7.x

.github/workflows/CI.yml
This PR is add Ruby 3.3 to test matrix.
=> Add Ruby 3.3 to test matrix

lib/danger/ci_source/buildkite.rb, lib/danger/helpers/comments_helper.rb, lib/danger/request_sources/vsts.rb, spec/lib/danger/ci_sources/circle_spec.rb, spec/lib/danger/commands/local_helpers/pry_setup_spec.rb, spec/lib/danger/commands/runner_spec.rb, spec/lib/danger/request_sources/github_spec.rb
Several typos were corrected in this PR.
=> Fix some typos #trivial 

.circleci/config.yml, .rubocop.yml, .travis.yml, CHANGELOG.md, Dockerfile
Close #1472 and close #1473
Thank you for opening the original pull request @okatatuki. Let me take over the rest tasks.
=> Update ruby version in Dockerfile to 3.2

spec/lib/danger/plugin_support/plugin_parser_spec.rb
Close https://github.com/danger/danger/issues/1509
=> Do not compare JSON as string

CHANGELOG.md, danger.gemspec
Close https://github.com/danger/danger/issues/1507
=> Support ruby-git 2.x

CHANGELOG.md, danger.gemspec
Close https://github.com/danger/danger/issues/1504
=> Bump kramdown to 2.5.1

spec/danger_spec.rb
To avoid https://github.com/danger/danger/issues/1518
=> Add test to ensure Danger runs without gitlab gem
