danger/danger

.travis.yml

Not sure if I added the:
```
- gem update --system
- gem install bundler
```
If I did, they can go, if you did, you can choose.

Use bundler caching in CI

---

lib/danger/environment_manager.rb
lib/danger/request_sources/github.rb
spec/sources/github_spec.rb

I was getting fails due to not having `DANGER_GITHUB_API_TOKEN` in my personal env. CI wouldn't register this, as it has it set up.

Fix tests for GitHub failing

---

lib/danger/request_sources/github.rb
spec/sources/github_spec.rb

Note this goes to #29 in order to keep the PR sane.
Rather than creating a new issue each time, look up whether we can edit an existing issue.

Support issue editing instead of new issue creation

---

CHANGELOG.md
lib/danger/ci_source/circle.rb
spec/sources/circle_spec.rb

This PR https://github.com/artsy/eigen/pull/1076 totally threw me for a loop, I have no idea why we're being passed such a funky URL, but now we [don't crash](https://circleci.com/gh/artsy/eigen/1389).

Add support for GitHub compare URLs that don't conform to URI

---

CHANGELOG.md
Rakefile
lib/danger/ci_source/circle.rb
lib/danger/request_sources/github.rb
spec/sources/github_spec.rb

in #32 I wondered if there were x amounts of comments being downloaded, looks like 30 are downloaded. It's definitely possible that a PR can get that many comments, so I think it's worth letting danger deal with all of them.

Make sure we grab all comments for github

---

danger.gemspec

Danger can't be used on a project with CLAide 1.0, as there are no breaking API changes it's fine to allow both.

Remove the specifity of claide as there's now cp 1.0

---

circle.yml

- fixes CI for circle in #52 
Not optimal, but this is the equivalent of giving someone free reign to an empty account ( it has no special access to danger's repos )

Support circle forks

---

CHANGELOG.md
lib/danger/ci_source/jenkins.rb
spec/sources/buildkite_spec.rb
spec/sources/jenkins_spec.rb

This will only work if using [this plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin) to build PR on Jenkins, but that seems to be the most used one.

Adding Jenkins provider

---

CHANGELOG.md
danger.gemspec
lib/danger/comment_generators/github.md.erb
lib/danger/request_sources/github.rb
spec/sources/github_spec.rb

Fixes #37, keeping the ability to use markdown in message (the markdown is parsed to HTML with redcarpet)

Use 100% width tables for messages

---

CHANGELOG.md
lib/danger/commands/init.rb
lib/danger/commands/local.rb
lib/danger/commands/runner.rb

```
✗ danger --help     
Usage:
$ danger COMMAND
Run the Dangerfile.
Commands:
+ init                       Creates a Dangerfile.
+ local                      Run the Dangerfile locally.
Options:
--base=[master|dev|stable]   A branch/tag/commit to use as the base of the diff
--head=[master|dev|stable]   A branch/tag/commit to use as the head
--version                    Show the version of the tool
--verbose                    Show more debugging information
--no-ansi                    Show output without ANSI codes
--help                       Show help banner of specified command
```

Fix commands help

---

CHANGELOG.md
danger.gemspec
lib/danger/request_sources/github.rb
spec/sources/github_spec.rb

Fixes #63.
It seems that `nap` wasn't really used (just imported) or I missed something here :grin: 
I also imported `faraday` in the Gemfile, as we're now using it directly.

Removing nap dependency

---

Dangerfile
lib/danger/comment_generators/github.md.erb
spec/spec_helper.rb

fixes #69
I needed to `require 'JSON'` in my local specs to get them to run. I wonder if circle/travis are on a different ruby to me.

Ensure the messages have no preceding tabs #trivial

---

README.md

Using an active voice instead of passive. Also, `being` was misspelled.

Syntax improvement. #trivial

---

danger.gemspec
lib/danger/version.rb

By using an older ( like by 2 weeks or something :P ) version of Fastlane, my Gemfile resolved our grit version to be a version many versions ago, and so https://github.com/artsy/eigen/pull/1188 failed. I've locked grit to the latest build and made everything else pretty flex

Lock dependencies #trivial

---

lib/danger/commands/init.rb

Lets us provide real links for travis/circle in the init wizard.

Pull the repo slug out for Danger init via the LocalGitRepo class #trivial

---

lib/danger/commands/init.rb

Fixes
```
In order to expose an environment variable, go to:
/Users/felixkrause/Developer/danger/lib/danger/commands/init.rb:234:in `circle_token': undefined local variable or method `repo_slug' for #<Danger::Init:0x007f9cfcdfc208> (NameError)
from /Users/felixkrause/Developer/danger/lib/danger/commands/init.rb:159:in `setup_danger_ci'
```

Fixed crash on `danger init`

---

CHANGELOG.md
Dangerfile

I've moved your CHANGELOG notes to master, and started improving the Dangerfile. Now PRs to non-app parts don't have to be declared trivial, and we only warn when there are no tests and app code has been changed.

Update CHANGELOG + Dangerfile

---

lib/danger/commands/init.rb

[There isn't a GitHub access right called `public_info`]

Renamed public_info to public_repo #trivial

---

lib/danger/commands/local.rb

On GitHub, `/pulls` refers to the index, whereas `/pull/:id` is the show
action.

Correct url to PR #trivial

---

spec/dangerfile_spec.rb

As highlighted in https://github.com/danger/danger/pull/124, in ruby 2.3.0, `expect(actual).to be(expected)` works differently, since it's a different instance of the object it asserts it's different, while it's value is still exactly the same.
Error as shown in 2.3.0:
```
1) Danger::Dangerfile keeps track of the original Dangerfile
Failure/Error: expect(dm.defined_in_file).to be file.path
expected #<String:70180931302200> => "/var/folders/8f/wnyyflm90jqdw6nygmv5z4yr0000gn/T/dangefile_tests20160309-28419-1gv8xnp"
got #<String:70180931302880> => "/var/folders/8f/wnyyflm90jqdw6nygmv5z4yr0000gn/T/dangefile_tests20160309-28419-1gv8xnp"
Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care …
```

Fix comparison issue with Ruby 2.3.0

---

CHANGELOG.md
lib/danger/ci_source/local_git_repo.rb
spec/sources/local_git_repo_spec.rb

As highlighted in the hub documentation (https://hub.github.com/), hub
adds remotes with `git://` prefix, instead of what github.com uses
(`git@` as prefix).
Danger should now support both.
Along with that, the logic has been simplified with a regular expression for all types of urls.

Add support for git:// remote urls

---

lib/danger/ci_source/local_git_repo.rb

git-ruby doesn't require that anymore. Fixes #140

Fix leftover from refactor to git-ruby #trivial

---

circle.yml

I ran `bundle -v` before and after the `gem install bundler` on Circle CI. Both reported `1.9.5` despite having just installed bundler 1.11.2. This meant to me that the RVM Ruby environment on Circle wasn't aware of the new bundler binary which had just been installed.
I looked around for RVM answers a bit and wound up on this page: https://rvm.io/integration/bundler
Versions of RVM later than 1.11.0 should include this functionality already, but despite Circle having a much later one (1.26?) I found that doing the `gem install rubygems-bundler` mentioned there made the difference in the system picking up on the new version of bundler.

Use `rubygems-bundler` to fix Circle CI builds

---

CHANGELOG.md
README.md
lib/danger/comment_generators/github.md.erb
lib/danger/dangerfile_dsl.rb
lib/danger/request_sources/github.rb
lib/danger/violation.rb
spec/dangerfile_spec.rb
spec/fixtures/comment_with_error.html
spec/fixtures/comment_with_error_and_warnings.html
spec/fixtures/comment_with_non_sticky.html
spec/fixtures/comment_with_resolved_violation.html
spec/sources/github_spec.rb

Crossing out issues

---

lib/danger/request_sources/github.rb

The word `token` was omitted from the error message.

Fix typo #trivial

---

CHANGELOG.md
lib/danger/available_values.rb

I'll handle updating all the CHANGELOGs once #195  and this is merged, and make a `0.7.4` release - should un-block https://github.com/CocoaPods/CocoaPods/pull/5227

Moves the commits reference to be public in the DSL

---

CHANGELOG.md
README.md
lib/danger/ci_source/local_git_repo.rb
lib/danger/commands/local.rb
lib/danger/commands/new_plugin.rb
spec/sources/local_git_repo_spec.rb

I'm on the side of  we shouldn't support arbitrary repos e.g. `danger local --pr=artsy/eigen#11` as the file system isn't going to match the expectations of danger, a merged PR at least will have an approximation of the current file system ( though, obviously it may have changed since then, but that should be pretty obvious to the user. ) 
So this just adds a way to pass a single id along via `danger local --use-merged-pr=11`
Fixes https://github.com/danger/danger/issues/134

Adds a command-line argument to support choosing a specific merged PR

---

lib/danger/commands/runner.rb
spec/commands/runner_command_spec.rb

Fixes the issue where `danger --version` prints out an empty line.

fix danger --version doesn't print out version [#151] #trivial

---

CHANGELOG.md
lib/danger/commands/local.rb

Had a crash when running `danger local` due to the DSL changes.
```
Users/dbgrandi/watched/danger/danger/lib/danger/commands/local.rb:59:in `run': undefined method `dsl' for #<Danger::CISource::LocalGitRepo:0x007f7fbd110848> (NoMethodError)
from /Users/dbgrandi/.rvm/gems/ruby-2.2.4/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
from bin/danger:5:in `<main>'
```
#nottested

fix a crash where ci_source.dsl is not available with danger local

---

CHANGELOG.md
danger_plugins/protect_files.rb
danger_plugins/work_in_progress_warning.rb
lib/danger/commands/local.rb
lib/danger/commands/runner.rb
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/dangerfile_dsl.rb
lib/danger/plugin_support/plugin.rb
spec/dangerfile_spec.rb
spec/fixtures/plugins/example_exact_path.rb
spec/fixtures/plugins/example_globbing.rb
spec/import_spec.rb
spec/plugin_spec.rb

- disabled old style plugins
- create `Danger::Plugin`, that is a base class for plugins (look at https://github.com/dbgrandi/danger-proselint/blob/master/lib/danger_plugin.rb for what it should look like, but be aware that it has not been tested/integrated yet)
- added `init_plugins` method to `Dangerfile` that adds plugins as instance variables to a Dangerfile, allowing them to extend the DSL
- added some specs
- disabled some other specs
Rubocop will fail because some of the commented out specs have emoji, and it does not allow emoji in comments. This is known and should be okay.
Note: this will break all existing plugins.

initial work on migrating to new plugins

---

lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb

I had thought they were violations, but they weren't. Types.` /shrug`. I should improve the tests around this.
#trivial

Messages don't need mapping when presenting status reports

---

CHANGELOG.md
Dangerfile
danger.gemspec
lib/danger/plugin_support/plugin_parser.rb
spec/fixtures/plugins/example_full_plugin.rb
spec/fixtures/plugins/example_remote.rb
spec/lib/danger/ci_sources/circle_spec.rb
spec/lib/danger/plugin_support/plugin_parser_spec.rb

@KrauseFx was correct to be suspicious when I introduced the revised plugin support ( #223 ) it was a significant change from all of our exist discussion about what a plugin could look like.
If there's anything I've learned from 90k CocoaPods versions and from managing CocoaPods, it's that the initial expectations will stick with you for years. I need Danger to stay small, because I don't have time to product manage another project as big as Danger could become. So, Danger needs to be _extremely_ easy to build a plugin for. 
I think there's two spaces for plugins, private plugins ( like we have in Danger - [protect_files](https://github.com/danger/danger/blob/dfa3fe611ef331955a2cf7a2ab9b8a99981fbcf0/danger_plugins/protect_files.rb) and some of the things …

Created a plugin documentation parser in Danger

---

Dangerfile
lib/danger/commands/local.rb
lib/danger/commands/runner.rb

"Fixes" #231 #trivial
Also included: danger will now clean up after itself when running in local mode.

Show a helpful warning if danger can not access a local repo on GitHub

---

CHANGELOG.md
lib/danger/commands/runner.rb
spec/lib/danger/commands/runner_spec.rb

Resolves #219 
Add `--dangerfile=<path/to/dangerfile>` option to override the default `Dangerfile` location.

Allow Dangerfile path to be configured

---

lib/danger/danger_core/dangerfile.rb
lib/danger/plugin_support/plugin.rb
spec/lib/danger/commands/runner_spec.rb

Fixes #235 and adds an end-to-end test that covers every messaging aspect of the DSL. #trivial

Ensure that we don't break sticky on Dangerfiles due to the new syntax

---

README.md

Removes the slack link, as the auto-inviter wasn't being maintained.

Removed the slack link

---

CHANGELOG.md
lib/danger/ci_source/buildkite.rb
lib/danger/ci_source/ci_source.rb
lib/danger/ci_source/circle.rb
lib/danger/ci_source/drone.rb
lib/danger/ci_source/jenkins.rb
lib/danger/ci_source/local_git_repo.rb
lib/danger/ci_source/semaphore.rb
lib/danger/ci_source/travis.rb
lib/danger/ci_source/xcode_server.rb
lib/danger/commands/runner.rb
lib/danger/danger_core/environment_manager.rb
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
lib/danger/request_source/github.rb
lib/danger/request_source/request_source.rb
lib/danger/scm_source/git_repo.rb
rake/dsl_generator.rb
spec/lib/danger/ci_sources/ci_source.rb
spec/lib/danger/ci_sources/github_spec.rb
spec/lib/danger/commands/runner_spec.rb
spec/lib/danger/request_sources/github_spec.rb
spec/lib/danger/request_sources/request_source_spec.rb
spec/spec_helper.rb

This PR to implement #221 and establishes a base upon which support for other services (like BitBucket or GitLab) could be build. This doesn't solve the problem of #226, just separates it a little bit better. 
I tried to decouple current GitHub requirement as much as possible, but there still some parts of the code that will only work with GitHub (most notably: running danger locally). 
**Important note**: I'm not fluent in Ruby so there might be some beginner mistakes :)

Support for other code collaboration tools than GitHub

---

CHANGELOG.md
lib/danger/ci_source/buildkite.rb
lib/danger/ci_source/ci_source.rb
lib/danger/ci_source/circle.rb
lib/danger/ci_source/drone.rb
lib/danger/ci_source/jenkins.rb
lib/danger/ci_source/semaphore.rb
lib/danger/ci_source/travis.rb
lib/danger/ci_source/xcode_server.rb
lib/danger/danger_core/environment_manager.rb
spec/lib/danger/ci_sources/buildkite_spec.rb
spec/lib/danger/ci_sources/circle_spec.rb
spec/lib/danger/ci_sources/drone_spec.rb
spec/lib/danger/ci_sources/semaphore_spec.rb
spec/lib/danger/ci_sources/travis_spec.rb
spec/lib/danger/danger_core/environment_manager_spec.rb

There's no point in creating a CI Source only to dismiss it later on because it doesn't contain all of the information required. This PR makes sure we catch those situations early.

Fail CI Source validation early

---

README.md

Like in the rest of the `README`. 💯

Ruby should be uppercased

---

CHANGELOG.md
lib/danger/commands/new_plugin.rb
lib/danger/commands/plugin_abstract.rb
lib/danger/commands/plugin_lint.rb
lib/danger/commands/runner.rb
lib/danger/danger_core/dangerfile.rb
lib/danger/plugin_support/plugin.rb
lib/danger/plugin_support/plugin_parser.rb
spec/lib/danger/commands/plugin_lint_spec.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/spec_helper.rb

Adds a command `danger plugin lint` which can take the following types of args:
* a list of file paths
* a list of gems
* no arguments, which will parse lib/**/**/* to lint your local plugins
The website danger.systems will be using the list of gems to generate all of the up-to-date documentation. The list of file paths is good for testing, and no arguments is good for building plugins ( e.g. it'll be something you want on travisCI )

Adds plugin lint

---

CHANGELOG.md
lib/danger/commands/init.rb

I followed every single `init` step and I really like the way the `init` is "communicating" with me, but it somehow failed to mention that I also have to add the GitHub Bot Account as an collaborator to my private repo and I ran into an error, when the PR got built by travis. 
I know that I could have inferred this from the fact that my repo is private, but if the installation instructions are so detailed, it should just work after following every step 😉
And since you already ask if it is an open or closed repo, I added one sentence to notify the user to add the new GitHub user as collaborator.

Improve init description

---

CHANGELOG.md
lib/danger/plugin_support/plugin_parser.rb

The yard gem is required by [`plugin_parser.rb`](https://github.com/danger/danger/blob/254b78975417fd3d2a03e87d956c1e20e7d61a7f/lib/danger/plugin_support/plugin_parser.rb#L1) but is only a [development dependency(https://github.com/danger/danger/blob/254b78975417fd3d2a03e87d956c1e20e7d61a7f/danger.gemspec#L39). This leads to the following error when running `bundle exec danger local` without yard as part of the bundle:
```
bundler: failed to load command: danger (/usr/local/lib/ruby/gems/2.2.0/bin/danger)
LoadError: cannot load such file -- yard
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/danger-254b78975417/lib/danger/plugin_support/plugin_parser.rb:1:in `require'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/danger-254b78975417/lib/danger/plugin_support/plugin_parser.rb:1:in `<top …
```

Moves yard require inside parse method

---

CHANGELOG.md
lib/danger/ci_source/circle.rb
spec/lib/danger/ci_sources/circle_spec.rb

So that we can ask for the metadata a bit later.
I think I'd rather move the API check into the validation, so this is WIP until I get to a computer to do that.
/cc @ashfurrow

Allow Circle CI to pass validation without a PR check

---

Dangerfile

Removes all the implicit plugin usage. Post 1.0 this is the normal syntax.

Convert the Danger Dangerfile to the new syntax

---

CHANGELOG.md
lib/danger/plugin_support/plugin_file_resolver.rb

`plugin lint` doesn't work well with the relative links passed back from `Dir.glob`.

Support plugin lint on plugins

---

CHANGELOG.md
lib/danger/ci_source/buildkite.rb
spec/lib/danger/ci_sources/buildkite_spec.rb
spec/lib/danger/commands/runner_spec.rb

Hello all,
This fixes https://github.com/danger/danger/issues/309. It ensures that danger only runs on pull request builds and not just on any build by using the relevant environment variable.
I am going to be honest, I have no idea what I am doing really when it comes to ruby dev so hopefully this is somewhat correct. I wasn't sure if the empty? check was needed or not but put it in just to be safe. If its not required or there is a better way let me know.
Happy to make implement any suggestions.

Fix #309 Use BuildKite pull request repo environment variable

---

CHANGELOG.md
lib/danger/commands/plugins/plugin_readme.rb

Turns out if you want to use ERB, you should require it 👍

Fix for danger plugins readme crash

---

CHANGELOG.md
build.sh
lib/danger/ci_source/surf.rb
spec/lib/danger/ci_sources/surf_spec.rb

This PR adds CI support for [Surf](https://github.com/surf-build/surf), a toolkit for folx to create local build servers.
Refs https://github.com/surf-build/surf/pull/32, which adds Danger support for Surf (i.e. projects that have a Dangerfile will automatically be run if CI status will be posted)

Add CI support for the Surf CI server

---

CHANGELOG.md
danger.gemspec
lib/danger/commands/local.rb
lib/danger/commands/local_helpers/http_cache.rb
spec/lib/danger/commands/local_helpers/http_cache_spec.rb

- You can clear the cache with the `--clear-http-cache` command line arg.
- The cache TTL is 5 minutes
Still have 2 or 3 non-cached calls to GitHub, but it used to be around 8 when I was testing locally.

add http caching on GitHub API calls when running danger local [#198]

---

CHANGELOG.md
Dangerfile
lib/danger/version.rb

I wanna hold off on the big 2.0 release for a few days, should just be these two issues https://github.com/danger/danger/milestone/1 - pretty trivial to do, but I wanna time it with the website being ready.
Updates the Dangerfile because now it's shown on Danger.systems

Prepare for 0.10.0

---

CHANGELOG.md
lib/danger/commands/local.rb
lib/danger/plugin_support/plugin.rb

Drops into a Pry shell after evaluating the Dangerfile. Great way to explore how Danger works and what tools you have to use in your Dangerfile.
Removed a reference that created `@dangerfile_path` because it's a duplicate of logic in the parent class.

Add `danger local --pry`

---

lib/danger/commands/local.rb

`Faraday::Builder` is now `Faraday::RackBuilder`.
This stops the error:
```Ruby
Faraday::Builder is now Faraday::RackBuilder
```
From appearing during Danger runs.

Updated Faraday Builder class name - #trivial

---

CHANGELOG.md
README.md
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
lib/danger/request_source/github.rb
spec/fixtures/pr_diff_response.diff
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/spec_helper.rb

Add a property to access Github's unified diff of the PR:
```
if pr_diff.string.include? "fdescribe"
warn("Don't include an fdescribe in your tests")
end
```

expose the unified diff for PR through the github plugin

---

CHANGELOG.md
Dangerfile
danger_plugins/protect_files.rb
lib/danger/danger_core/dangerfile.rb
spec/lib/danger/ci_sources/git_spec.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/import_spec.rb

This has big ramifications for Dangerfiles. It scopes the git, github, and import plugins.
```
modified_files -> git.modified_files
added_files -> git.added_files
deleted_files -> git.deleted_files
lines_of_code -> git.lines_of_code
deletions -> git.deletions
insertions -> git.insertions
commits -> git.commits
pr_title ->  github.deleted
pr_body -> github.body
pr_author -> github.author
pr_labels -> github.labels
branch_for_base -> github.branch_for_base
branch_for_head -> github.branch_for_head
base_commit -> github.base_commit
head_commit -> github.head_commit
env.request_source.pr_json -> github.pr_json
env.request_source.api -> github.api
import -> plugin.import
```
This should be the last big breaking change before the major release.

Breaking - Remove git, github, and import from the internal plugins list

---

CHANGELOG.md
Dangerfile
Gemfile
Rakefile
lib/danger/commands/plugins/plugin_lint.rb
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
lib/danger/plugin_support/plugin_file_resolver.rb
lib/danger/plugin_support/plugin_linter.rb
lib/danger/plugin_support/plugin_parser.rb
spec/fixtures/plugin_json/example_fully_doc.json
spec/fixtures/plugin_json/example_remote.json
spec/lib/danger/plugin_support/plugin_linter_spec.rb
spec/lib/danger/plugin_support/plugin_parser_spec.rb

It's tough to provide some useful bits of information on danger.system - notably the Plugin <-> Gem  bits. As a gem can contain multiple plugins, and with just the raw class metadata it's not enough. Now each plugin links to a gem, and we have file metadata for all the pieces.
As the file/location data is now in the parser, I've exposed it to the linter, and fixed #354

Improvements to the Parser and the Linter

---

CHANGELOG.md
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/messages/markdown.rb
lib/danger/danger_core/messages/violation.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/spec_helper.rb

Print out the file and line on the summary if present.
```markdown
Results:
Warnings:
```

when outputing the summary, consider file and line

---

lib/danger/request_source/github.rb
spec/fixtures/comment_with_file_link.html
spec/lib/danger/request_sources/github_spec.rb

Add a link to the file & line the message is for in GitHub. Like: `https://github.com/danger/danger/blob/744eefaf2f9338ef373e06d5156dda9d51375390/lib/danger/request_source/github.rb#L5`.
I've added a test around the parsing of this new messages. I'm not sure if more tests would be useful. @orta does it seem right to you?

show a link to the line when setting inline comments

---

lib/assets/DangerfileTemplate

I cheered a bit too early in #374, the 2.0.1 release solved the crashers, but still didn't produce an error-free `Dangerfile` when running `danger init`.
```shell
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
```
This PR removes one space and one dquote to get rid of the shell warnings. The output then becomes something more along the lines of:
```shell
Results:
Errors:
```

Correct formatting of the fdescribe/fit grep calls #trivial

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_git_plugin.rb
spec/lib/danger/plugins/dangerfile_git_plugin_spec.rb

I wanted a way to get file level diff info so I could inspect the changes to our `.xcodeproj` to make sure nobody adds a specific setting.
May also use it to add a Danger message anytime a `TODO` comment is added to source files.

Add git.diff_for_file("some/file.txt") to get a Git::Diff::DiffFile

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
spec/lib/danger/plugins/dangerfile_github_plugin_spec.rb

Also fixes a bug - it wouldn't work if you gave a path which began with a `/`

Adds an option for only showing the filename for a path with `html_link`

---

CHANGELOG.md
lib/danger/plugin_support/templates/readme_table.html.erb

There was an extra `<tr>`left over
Also there is now a check for the methods before showing the headline. Can't _easily_ see a use for attributes only, but sure.

Shows attributes correctly in `danger plugins readme`.

---

CHANGELOG.md
lib/danger/ci_source/buildkite.rb
spec/lib/danger/ci_sources/buildkite_spec.rb

Check that `BUILDKITE_PULL_REQUEST_REPO` is both present and not the empty string, as noted [here](https://github.com/danger/danger/issues/426#issuecomment-239886660).

Require BUILDKITE_PULL_REQUEST_REPO to not be the empty string

---

lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb

This PR fixes a minor typo in the documentation of the messaging plugin.

Fix a typo in messaging-plugin docs #trivial

---

CHANGELOG.md
lib/danger/scm_source/git_repo.rb

Re: #160 #316
This applies the fix in https://github.com/jamtur01/ruby-git/commit/6f0b644d24d9e061a852ba2f18a3c78c4ec1a0e4 / inline. 
Considering the amount of tests we have where we create a real repo and exec some commits, I'm happy this isn't breaking anything, what I'm not 100% sure of is whether it fixes the problem. I rarely would see it.

Find the common merge commit, before looking for a diff in git

---

CHANGELOG.md
lib/danger/ci_source/circle.rb
spec/lib/danger/ci_sources/circle_spec.rb

Circle CI should check if a PR IS a PR via the `CI_PULL_REQUEST`
environment variable. If it's empty then it's NOT a PR.

Circle CI checking for PR status

---

danger.gemspec

There was a breaking name change between faraday 0.8 and 0.9. Danger won't work with faraday 0.8.
```
$ bundle exec danger local --use-merged-pr=191
/Users/michele/.rvm/gems/ruby-2.3.0/gems/danger-2.1.5/lib/danger/commands/local.rb:64:in `run': uninitialized constant Faraday::RackBuilder (NameError)
Did you mean?  Faraday::Builder
from /Users/michele/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
from /Users/michele/.rvm/gems/ruby-2.3.0/gems/danger-2.1.5/bin/danger:5:in `<top (required)>'
from /Users/michele/.rvm/gems/ruby-2.3.0/bin/danger:23:in `load'
from /Users/michele/.rvm/gems/ruby-2.3.0/bin/danger:23:in `<main>'
from /Users/michele/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
from /Users/michele/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks: …
```

Update faraday minimum version to 0.9 to fix a crash when using 0.8

---

spec/lib/danger/request_sources/gitlab_spec.rb

This test does not have an expectation. Funny how that test even works, magic of lazily evaluated rspec `let`s.

Gitlab test is missing an expectation #trivial

---

lib/danger/helpers/comments_helper.rb
lib/danger/request_source/github.rb
lib/danger/request_source/gitlab.rb

Trying to have only one source of truth for the `"generated_by#{danger_id}"`. Not 100% sure on this refactoring, feel free to close if you guys don't like this. The more pragmatic thing would be a `generated_by_danger(body, danger_id)` method on `CommentsHelper`. But I like wrapper object so much 😈

Hk extract comment identification #trivial

---

CHANGELOG.md
lib/danger/request_source/github.rb
spec/lib/danger/danger_core/environment_manager_spec.rb

Previously, Github would be used for danger local runs.
Since 5f505b9 however danger local would crash because the
github ci source wouldn't "validate_as_api_source". Fixes #454

Restore danger local behaviour to use Github

---

lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb

The examples list a `gitlab.branch_for_base` which failed for us and it should be `gitlab.branch_for_merge`.

Fix typo in gitlab.branch_for_merge documentation #trivial

---

lib/danger/ci_source/semaphore.rb

I was not seeing working builds when adding Danger, running `printenv` did not give the results that we see across forks.

Update Semaphore docs #trivial

---

CHANGELOG.md
lib/danger/ci_source/gitlab_ci.rb
lib/danger/commands/plugins/plugin_json.rb
lib/danger/commands/plugins/plugin_lint.rb
lib/danger/commands/plugins/plugin_readme.rb
lib/danger/plugin_support/plugin_file_resolver.rb
spec/lib/danger/commands/plugin_json_spec.rb
spec/lib/danger/commands/plugins/plugin_lint_spec.rb

So, this is tricky. 
As a part of an upcoming Danger.Systems PR, I'm moving to separately running `bundler` per Danger plugin, this has the downside of being _slow_ -  I can look into vending the dependencies better, but I have to run it all twice to get the gem metadata and the plugin metadata. 
This is because if any plugin breaks danger.systems everything breaks, and more importantly - there can be conflicting dependencies in the plugins. We'd get nothing if two plugins update and have different deps.
Not gonna fly when it takes more than 10m to generate the files. Better to migrate the two types of data into one, and pass that around the system.

Integrate the Gem metadata with the Plugin JSON for external plugins

---

CHANGELOG.md
lib/danger/commands/runner.rb
lib/danger/danger_core/executor.rb
spec/lib/danger/danger_core/executor_spec.rb

When not in a CI environment, this would previously fail because
of an undefined variable. Fixes #472 
Testing on these classes is not a solved story yet I think.

fixes crash when running `bundle exec danger`

---

CHANGELOG.md
lib/danger/ci_source/buildkite.rb
spec/lib/danger/ci_sources/buildkite_spec.rb

Fixes #473 .
Danger would 404 when trying to run against a Pull Request on a Forked Repository with Buildkite.
It was using the PR URL to generate the Slug, instead it should be using the main repo URL.
Danger should continue to skip if the commit is not a PR as per #310 .
- Danger still uses the environment variable BUILDKITE_PULL_REQUEST_REPO to perform PR validation. I've just made the change so it uses BUILDKITE_REPO for generating the Slug used to grab the PR itself from Github.
- I've also tweaked the tests slightly, to ensure it gets out a correct repo slug from a git+ssh repo and a https repo.
- I ran Danger pointing at my feature/buildkite-env-var version of Danger with these changes, and the PR build ran exactly as expected.
- I also ran a build on the Merge commit of my sample …

[Buildkite] Use BUILDKITE_REPO for repo slug

---

lib/danger/ci_source/local_git_repo.rb
spec/lib/danger/danger_core/executor_spec.rb

validates_as_pr? must be implemented by each ci source, even the local
git repo.
This fixes a possible crash when running with `DANGER_USE_LOCAL_GIT` env var. Considering as #trivial since this is not happening to anyone?

local_git_repo ci source must implement method #trivial

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_danger_plugin_spec.rb

I've extracted code from https://github.com/ruby-grape/danger/blob/master/Dangerfile into the https://github.com/dblock/danger-changelog gem. If I update the https://github.com/ruby-grape/danger project's Dangerfile to use that via `changelog.check` I will break pull requests in all projects that use Danger in that org. I must update half a dozen repositories at once. For each repository I have to modify `Gemfile` to include `danger-changelog`. If I don't do that, it just breaks because the org projects don't know anything about `danger-changelog`.
Pain and suffering. Chicken and egg.
Allow one to package Dangerfile in a versioned gem and be able to load it from another Dangerfile like this:
```ruby
import_dangerfile gem: 'ruby-grape-danger'
```
The `import_dangerfile(String)` method is …

Feature: import Dangerfile from path or gem.

---

lib/danger/version.rb

Version 3.1.1 has already been released. I'd like to increment master to 3.2.0 as #504 is a major change with a backward compatible deprecation, so I can lock the minimum danger version to something in https://github.com/ruby-grape/danger/pull/5.
#trivial

Incremented version for next development iteration.

---

lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_danger_plugin_spec.rb

Improves the docs for the core plugin, and the import dangerfile from a repo would work in GitLab as well as Bucket via the same code.
#trivial

Improve docs for the core Danger plugin

---

CHANGELOG.md
lib/danger/danger_core/dangerfile.rb
lib/danger/version.rb

#322 shows us that the tables can  be really long. 
We all talked about how keeping track of the window size can help, but these tables are built of the data. So now, when we have a string, that string is capped at 80 chars. Meaning the tables will always be this long:
I think that's a reasonable enough size to not close the issue.

Improve handling of tables

---

CHANGELOG.md
lib/danger/request_source/bitbucket_server_api.rb
spec/lib/danger/request_source/bitbucket_server_api_spec.rb

I saw [octokit.rb did this](https://github.com/octokit/octokit.rb/blob/efceb79b2d1db92d908abbe62d4fb0f436240002/lib/octokit/client.rb#L122), and think this is a good feature to add 🔒, just in case someone did the `inspect`🕵.

Mask password when inspect BitbucketServerAPI

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_danger_plugin_spec.rb
spec/support/bitbucket_server_helper.rb

Adds `scm_provider` to the DSL which will let users and plugins check
what the active scm_provider is. Example
```ruby
if scm_provider == :gitlab do
message("Running under gitlab")
end
```

[Core] Provide a way to check the active scm host

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb

Deprecated `branch_for_merge` in favour of `branch_for_base` and
add `branch_for_head`.

[GitLab] Update branch accessors

---

CHANGELOG.md
lib/danger/danger_core/messages/markdown.rb
spec/lib/danger/request_source/github_spec.rb

In my head, all message types were `Violation` but not Markdowns, they're a different class. Now they both have the same function determining if it's an inline object or not.
I made sure that existing tests cover this case, rather than adding a specific test for the crash.

Fix for markdown crashing DM - fixes #520

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_bitbucket_server_plugin.rb
spec/lib/danger/plugins/dangerfile_bitbucket_server_plugin_spec.rb

I check if Bitbucket server supports inline HTML in comments: Unfortunately not.
For that reason I added `markdown_link` for the Bitbucket Server plugin.

Add `markdown_link` for the Bitbucket Server plugin

---

CHANGELOG.md
lib/danger/ci_source/bitrise.rb

Correction to using App Env Vars as apposed to Secret Env Vars, as mentioned in #493.

Updating bitrise docs

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb

Ja, my take at the gitlab html link bug. there was no test for this, so this could fall through. Thanks @ort for the `env` hint :)

Hk issue 543

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_git_plugin.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_git_plugin_spec.rb

This is very closely modeled on the `diff_for_file` support (read: code search and copy/paste).

Add per-file info (insertions, deletions, before/after contents)

---

CHANGELOG.md
lib/danger/danger_core/messages/markdown.rb
lib/danger/danger_core/messages/violation.rb
lib/danger/helpers/comments_parsing_helper.rb
spec/lib/danger/helpers/comments_helper_spec.rb
spec/spec_helper.rb

Reading danger/danger code before goes to 😴 , pondering what these `nil`s are. So let's set nil-defaults for them and remove some calls 🔪

Remove unknown passings of nils

---

CHANGELOG.md
lib/danger/helpers/comment.rb
lib/danger/helpers/comments_helper.rb
lib/danger/request_source/github.rb
lib/danger/request_source/gitlab.rb
spec/danger/helpers/comment_spec.rb

This PR extracts `Comment` from `CommentsHelper`, benefits:
- Decouple from module
- More tests coverage
My future goal is to make:
- `lib/danger/request_source/github.rb`
- `lib/danger/request_source/gitlab.rb`
them be easily tested.
This is part of the work 🚧 to achieve the goal along the way 🛤.

Save Comment class out of CommentsHelper

---

CHANGELOG.md
lib/danger/ci_source/jenkins.rb
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/plugins/dangerfile_bitbucket_cloud_plugin.rb
lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb
lib/danger/request_source/bitbucket_cloud.rb
lib/danger/request_source/bitbucket_cloud_api.rb
spec/fixtures/bitbucket_cloud_api/pr_response.json
spec/lib/danger/request_source/bitbucket_cloud_api_spec.rb
spec/lib/danger/request_sources/bibucket_cloud_spec.rb
spec/spec_helper.rb
spec/support/bitbucket_cloud_helper.rb

- Duplicates bitbucket_server RequestSource and Plugin and adapts them for bitbucket cloud REST API.
- Dangerfile support is the same as for bitbucket_server but uses bitbucket_cloud name.
- Basic Auth via username/password is used and needs to be set via DANGER_BITBUCKETCLOUD_USERNAME and DANGER_BITBUCKETCLOUD_PASSWORD environment vars

Adds support for bitbucket cloud

---

spec/lib/danger/ci_sources/bitrise_spec.rb
spec/lib/danger/ci_sources/local_git_repo_spec.rb
spec/lib/danger/ci_sources/xcode_server_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_danger_plugin_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_git_plugin_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb
spec/lib/danger/request_source/github_spec.rb
spec/lib/danger/scm_source/git_repo_spec.rb
spec/spec_helper.rb
spec/support/bitbucket_cloud_helper.rb
spec/support/bitbucket_server_helper.rb
spec/support/github_helper.rb
spec/support/gitlab_helper.rb

`with_git_repo` was kinda duplicates across different spec_helpers. pulled it up and made the origin more specific in the tests where it actually mattered.
Also removed all of the `switched to branch 'new'` logs in the spec output. That backwards compatibility test in `github_spec.rb` was passing without invoking anything, because the url would be set from the previous test already.

Hk spec improvements #trivial

---

.rubocop.yml
CHANGELOG.md
danger.gemspec
lib/danger/ci_source/local_git_repo.rb
lib/danger/ci_source/support/merged_pull_request_finder.rb
lib/danger/ci_source/support/remote_finder.rb
spec/fixtures/ci_source/support/danger-git.log
spec/fixtures/ci_source/support/enterprise-remote.log
spec/fixtures/ci_source/support/remote.log
spec/fixtures/ci_source/support/swiftweekly.github.io-git.log
spec/lib/danger/ci_sources/local_git_repo_spec.rb
spec/lib/danger/ci_sources/support/merged_pull_request_finder_spec.rb
spec/lib/danger/ci_sources/support/remote_finder_spec.rb

Before this PR,
`danger local` can only find PR like `Merge pull request #42` from **merge commits**.
After this PR,
`danger local` can find PR like `Merge pull request #42` and `Summary (#42)` from [50 recent **commits**](https://github.com/danger/danger/blob/ccfbd83f289e716766161dd9802f0ff979fc51f3/lib/danger/ci_source/local_git_repo.rb#L49).
--
- Add pry-byebug for debugging.
- Target Rubocop for >= Ruby 2.0
--
<details>
<summary>Merge commits v.s. commits</summary>
The commit logs given to find merged Pull Request changed from:
`git log --merges --oneline` to `git log --oneline -50`
</details>
<details>
<summary>Merge pull request v.s. squash and merge</summary>
`Merge pull request #42` is great old git merge, which we are using at …

Improves "danger local" Pull Request finding

---

CHANGELOG.md
circle.yml
lib/danger/ci_source/bitrise.rb
lib/danger/ci_source/buildkite.rb
lib/danger/ci_source/circle.rb
lib/danger/ci_source/drone.rb
lib/danger/ci_source/gitlab_ci.rb
lib/danger/ci_source/jenkins.rb
lib/danger/ci_source/local_git_repo.rb
lib/danger/ci_source/semaphore.rb
lib/danger/ci_source/surf.rb
lib/danger/ci_source/teamcity.rb
lib/danger/ci_source/travis.rb
lib/danger/ci_source/xcode_server.rb
lib/danger/danger_core/environment_manager.rb

* [danger/danger #1484 - CircleCI](https://circleci.com/gh/danger/danger/1484?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
* [Job #2334.1 - danger/danger - Travis CI](https://travis-ci.org/danger/danger/jobs/160656761)
* [Job #2339.3 - danger/danger - Travis CI](https://travis-ci.org/danger/danger/jobs/160682667)
* [Job #2337.2 - danger/danger - Travis CI](https://travis-ci.org/danger/danger/jobs/160680408)
They all cannot find their `supported_request_sources`, I think they need to require files they need in order to reference them.
#trivial

Add missing require statements to CI subclasses

---

CHANGELOG.md
lib/danger/ci_source/local_git_repo.rb

This size affects how many commits can `danger local` search for `--use-merged-pr`.
50 is too small (my fault in #559 😭). Let's increase to 1000000.
I did memory experiments against some repos to see if this size is too big:
```ruby
require "objspace"
ObjectSpace.trace_object_allocations_start
pid = Process.pid; puts "Process: #{pid}"
before = Time.now
before_rss = `ps -eo pid,rss | grep #{pid} | awk '{print $2}'`.to_i
commits = `git log --oneline -n1000000`
after_rss = `ps -eo pid,rss | grep #{pid} | awk '{print $2}'`.to_i
puts "Elapsed time: #{Time.now - before} seconds"
difference = after_rss - before_rss
if difference >= 1024
puts "Memory consumed: #{(after_rss-before_rss)/1024.0} MB"
else
puts "Memory consumed: #{after_rss-before_rss} KB"
end
commits = nil
```
Use `ruby measure.rb` …

Increase number of commits danger local can search for merged PR

---

CHANGELOG.md
lib/danger/plugin_support/plugin_linter.rb

This PR fixes rubocop warnings.

Fix rubocop offenses and add parentheses to avoid Ruby emit warnings

---

CHANGELOG.md
lib/danger/request_sources/github.rb
spec/lib/danger/request_sources/github_spec.rb

This uses the danger_id to set the context of Github status. Should allow multiple status for multiple execution of danger cli.
See #570

Danger id as context of Github status

---

lib/danger/danger_core/plugins/dangerfile_git_plugin.rb

- Following the example on [danger.systems](http://danger.systems) confused me for a while.
- Does this text exist anywhere else for the website generation or just here?

Example for diff_for_file is incorrect #trivial

---

lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/executor.rb
spec/lib/danger/danger_core/dangerfile_spec.rb

This method used `dangerfile` 3 times, it is jealous of `Dangerfile` ([feature envy](https://sourcemaking.com/refactoring/smells/feature-envy)), so this method should belong to `Dangerfile`.

The post_results method belongs to Dangerfile #trivial

---

lib/danger/ci_source/teamcity.rb

Probably copy-pasta 🍝, this PR removes this duplicate check.

Remove duplicate env check in TeamCity's GitHub env check #trivial

---

CHANGELOG.md
lib/danger/ci_source/local_git_repo.rb
lib/danger/ci_source/support/merged_pull_request_finder.rb
spec/fixtures/ci_source/support/two-kinds-of-merge-both-present.log
spec/lib/danger/ci_sources/local_git_repo_spec.rb
spec/lib/danger/ci_sources/support/merged_pull_request_finder_spec.rb

This Pull Request improves `danger local` finding merged Pull Request logic.
I was trying to use `danger local` against my repo and found this bug 😢 
--
<details>
<summary>Implementation Details</summary>
- Feed in PR ID correctly to `MergedPullRequestFinder`:
Given `LOCAL_GIT_PR_ID="2"`
Before
`env["LOCAL_GIT_PR_ID"] || "" # => ""`
After
`env.fetch("LOCAL_GIT_PR_ID") { "" } # => "2"`
- Handle case that both merged and squash-and-merged (same as rebase merge) PR both presents
* `Something (#2)`
* `Merge pull request #2`
Pick the most recent one in these two.
- Improves the RegExp for finding merged pull request and
squash-and-merged pull request.
* Merged PR:
- Before: `"Merge pull request #2"`
- After: `"Merge pull request #2 from"`
* Squash-and-merged PR:
- Before: `"#2"`
- After: …

Improves `danger local` merged Pull Request finding logic

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_danger_plugin_spec.rb

This PR adds a feature that if plugin file doesn't contain any class inherits from `Plugin` then raises an error message: `"danger-orta-plugin.rb doesn't contain any valid danger plugin."`

Raises error if plugin file doesn't contain any plugin

---

CHANGELOG.md
lib/danger/commands/local.rb
spec/lib/danger/commands/local_spec.rb

This PR removes unused options from `danger local` command. Fixes #593.
And move class method above instance methods.

Remove unused options for `danger local`

---

CHANGELOG.md
lib/danger/commands/runner.rb
spec/lib/danger/commands/runner_spec.rb
spec/support/matchers/have_instance_variables_matcher.rb

I think these pending tests should belongs to the executor specs. Will do in following PRs.
- Test no Dangerfile present
- Test instance variables' default values
- Test default CLI options
- Test correctly sending messages to Executor
- Introduce new RSpec matcher: `have_instance_variables` (similar to have_attributes, but for instance variables)

Add some specs for Runner

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_danger_plugin_spec.rb

Having a centralized `Dangerfile` for several projects inside an organization. As the branch and path where hardcoded to `master` and `Dangerfile` respectively, achieving this goal demanded too many repositories to be created, making it hard to mantain and a hassle hard to test changes on `Dangerfile`s without needing to create new repositories or risking breaking all builds.
`import_dangerfile_from_github` receives the repo `slug` to create the download URL, so 2 new optional parameters were added for the `branch` and `path` be set, keeping `master` and `Dangerfile` as the default values.

Added option to run a Dangerfile from a `branch` and/or `path` when using a remote repo

---

CHANGELOG.md

Previous PR had the 'import_dangerfile' `Changelog.md` entry added to `3.4.0` version instead of `master`.

Changelog Fix - 'import_dangerfile' entry previously added to release instead of master #trivial

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb
spec/fixtures/plugins/example_not_broken.rb
spec/lib/danger/danger_core/plugins/dangerfile_danger_plugin_spec.rb

Some users may not use `module Danger` on outer namespace. This PR fixes it.
If the regexp is not reliable, we can use Ruby [parser](https://github.com/whitequark/parser) gem.

Not raises error if plugin that inherits from Danger::Plugin

---

CHANGELOG.md
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/environment_manager.rb

Just a quick API change, makes the Cork instance the most default it could be.
closes #585

Bring backwards API compaatbility for dangerfile and env manager

---

CHANGELOG.md
lib/danger/ci_source/jenkins.rb
spec/lib/danger/ci_sources/jenkins_spec.rb

Capture `GIT_URL_1` if user's Jenkins has multiple remotes.
Fixes #474.
https://wiki.jenkins-ci.org/pages/viewpage.action?pageId=69273545 (`⌘-F` for `GIT_URL_N` docs)

Multiple remotes support for Jenkins

---

CHANGELOG.md
lib/danger/scm_source/git_repo.rb
spec/lib/danger/request_sources/github_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb

The current check just verifies that a commit hash is a valid hash rather than verifying that the commit exists in the repo. This may create problems as described in #609.

Fix commitish exists check

---

spec/lib/danger/request_sources/bibucket_cloud_spec.rb
spec/lib/danger/request_sources/bibucket_server_spec.rb

✨ 💖 
Notice when running the specs:
```
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives,
since literally any other error would cause the expectation to pass, including those raised
by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are
intending to test may not even get reached. Instead consider using `expect {}.not_to raise_error`
or `expect { }.to raise_error(DifferentSpecificErrorClass)`. This message can be suppressed by
setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. 
```

Fix ability to have false positives specs #trivial

---

spec/lib/danger/commands/plugin_json_spec.rb

There was a bunch of json being outputted while running specs. Rspec makes it easy to capture that.
The assertion is pretty unspecific on purpose because the actual json is verified in another spec.

remove stout output in spec and be more specific #trivial

---

spec/lib/danger/scm_source/git_repo_spec.rb
spec/spec_helper.rb

Felt like a lot of duplication even where the spec didn't specificly care about the exact commits/files in the repo.

use `with_git_repo` helper where applicable #trivial

---

spec/lib/danger/ci_sources/buildkite_spec.rb
spec/lib/danger/ci_sources/circle_api_spec.rb
spec/lib/danger/ci_sources/drone_spec.rb
spec/lib/danger/ci_sources/jenkins_spec.rb
spec/lib/danger/commands/local_helpers/http_cache_spec.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb
spec/lib/danger/plugins/dangerfile_bitbucket_server_plugin_spec.rb
spec/lib/danger/request_sources/bibucket_cloud_spec.rb
spec/lib/danger/request_sources/bibucket_server_spec.rb
spec/lib/danger/request_sources/github_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb
spec/lib/danger/scm_source/git_repo_spec.rb

We probably want `eq` and it is 1 character less.

Replace eql to eq in specs #trivial 

---

CHANGELOG.md
Gemfile
lib/danger/danger_core/dangerfile.rb
spec/lib/danger/danger_core/dangerfile_spec.rb

Also relates to #622 
-- 
Simplifies the table'd output when Danger shows the table, the diff can be really long and not too useful in that table - so I've removed it, and to add some extra paranoia, all metadata from plugins is not encoded into utf8

Ensure that PR/MR diffs don't break the verbose table output

---

.gitignore
Gemfile

So that the test suite won't emit a lot of scary stuff. If anyone want to checkout those failures, can see  this file [`.xml_dump_failures`](https://github.com/JuanitoFatas/rspec_junit_formatter/commit/95e7c7ffb7c5f35a26120f3d48d5bb1356162417) after tests ran.

Dump RSpec JUnit Formatter failures to a local .xml_dump_failures file #trivial 

---

CHANGELOG.md
lib/danger/scm_source/git_repo.rb
spec/lib/danger/request_sources/github_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb
spec/lib/danger/scm_source/git_repo_spec.rb

This PR changes the behavior of ensure commit exists. Fixes #185 /cc @KrauseFx @jeroenvisser101
Before we failed untill [we are finding the merge base](https://github.com/danger/danger/blob/50afd1743d1228b1c7031eb7e32eeda91aad526b/lib/danger/scm_source/git_repo.rb#L13-L15) for commits that not exists.
```ruby
ensure_commitish_exists!(from)
ensure_commitish_exists!(to)
merge_base = repo.merge_base(from, to) # <--- failed here *before* this PR
```
Now we fail fast:
```ruby
ensure_commitish_exists!(from) # <--- failed here *after* this PR
ensure_commitish_exists!(to)
merge_base = repo.merge_base(from, to) 
```
--
<details>
<summary>Cases that commits not exist happened</summary>
- Run `danger pr https://github.com/artsy/eigen/pull/1811` on `danger/danger`
```
Running your Dangerfile against …
```

Fail fast if still cannot find the commit after fetch

---

CHANGELOG.md
lib/danger/danger_core/environment_manager.rb
spec/lib/danger/danger_core/environment_manager_spec.rb

I stumbled on this over at https://github.com/danger/danger-plugin-template/pull/10#issuecomment-252731193 when `EnvironmentManager` was trying to output errors to screen, but had no `ui` to output with. Not ideal.
This PR fixes that.
I couldn't find a particularly friendly way to test this. The bug is obvious enough, but preventing regressions would be nice. Passing in bad `env` params meant that it would fail to trigger the bug (it would bail beforehand), so I'm not sure :)

EnvironmentManager constructor forwards self.ui, not ui method arg

---

CHANGELOG.md
lib/danger/commands/pr.rb
spec/lib/danger/commands/pr_spec.rb

This Pull Request adds `--dangerfile` support to `danger pr` command.
Implements #637.

Add --dangerfile support to `danger pr` command

---

CHANGELOG.md
lib/danger/request_sources/github.rb
spec/lib/danger/request_sources/github_spec.rb

So when danger failed a build, it would output a comment if it was unable to update the PR status. However, when the danger run was not containing any errors, it would fail silently to update the PR status. Reported in #587

Hk status update improvements

---

.rubocop.yml
danger.gemspec

Bump rubocop version constraint so locally will resolve to `0.44.1` and hide these offenses for now:
```
Inspecting 134 files
C................................................................C.....C..............................................................
Offenses:
danger.gemspec:6:1: C: Block has too many lines. [37/25]
Gem::Specification.new do |spec| ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/danger/plugin_support/plugin_file_resolver.rb:21:9: C: Block has too many lines. [27/25]
Bundler.with_clean_env do ...
^^^^^^^^^^^^^^^^^^^^^^^^^
lib/danger/request_sources/github.rb:263:25: C: Block has too many lines. [31/25]
submit_inline = proc do |m| ...
^^^^^^^^^^^
```

Bump rubocop and hide offenses for now #trivial

---

CHANGELOG.md
lib/danger/scm_source/git_repo.rb
spec/lib/danger/request_sources/github_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb
spec/lib/danger/scm_source/git_repo_spec.rb

Will this solve #634 I am not sure 😞 .
But I find `git merge-base --all` can find multiple common ancestors 🎩 as the docs said:
> Output all merge bases for the commits, instead of just one.
> -- [git merge-base](https://git-scm.com/docs/git-merge-base)
--
The tests were wrong 😱, should exercise in the created tmp folder:
```
@dm = testing_dangerfile
@dm.env.scm.diff_for_folder(dir, from: "master", to: "new")
expect(@dm.git.deleted_files).to eq(["file"])
```

Use `git-merge-base` instead of ruby-git to find more merge bases

---

CHANGELOG.md
lib/danger/commands/runner.rb
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/executor.rb
lib/danger/request_sources/github.rb
spec/lib/danger/commands/runner_spec.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/request_sources/github_spec.rb

As mentioned on [#641](https://github.com/danger/danger/issues/641):
- Made --new-comment work with a single danger_id, so now we only get one, pretty Danger checkmark on your PR instead of multiple ones.
- Danger now always retrieves it's last comment (used to be the first one since it never had more than one showing up at the same time), so removing the argument on a subsequent build will now make it edit the right comment.

--new-comment improvements

---

CHANGELOG.md
lib/danger/ci_source/jenkins.rb
spec/lib/danger/ci_sources/jenkins_spec.rb

Added support for [Jenkins pipelines](https://jenkins.io/solutions/pipeline/).
Pipelines is a new way of configuring your jobs and is the preferred way in Jenkins 2.0+.
Unfortunately the old env vars isn't supported but on the other hand the vars should be uniform regardless of scm provider.
Currently works with:

Support for Jenkins pipelines

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb
spec/lib/danger/request_sources/gitlab_spec.rb

Implemented `new_comment` parameter support in GitLab request source. Test included, I'm pretty sure test will go red without my change.
Fixes #648.

Add new_comment parameter to GitLab request source

---

lib/danger/commands/init_helpers/interviewer.rb

Not sure how this one has not been fixed so far, please correct me if it's an intended behavior.
However, right now if you provide an answer to the `interviewer` question, you'll see `You need to provide an answer.` and in a case of an empty string, it will work.

Fix the issue with interviewer ask method; #trivial

---

CHANGELOG.md
lib/danger/comment_generators/github.md.erb
spec/lib/danger/helpers/comments_helper_spec.rb

Addresses https://github.com/danger/danger/issues/663 — specifically, GitHub's using a CommonMark-compliant parser now, so there are some stricter rules around HTML blocks in Markdown.
One thing I don't really like about this PR is the location of the new spec — so far everything in `comments_helper_spec` is about the helper itself and not about any particular `comment_generator`. Do you think maybe this would be better placed in a new spec file for comment generators? Feel free to push directly to this branch with adjustments!

No blank lines in GitHub output

---

CHANGELOG.md
lib/danger/request_sources/bitbucket_server_api.rb

Print out an error when posting a comment to BitBucket Server fails

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb

A regular expression isn't a very reliable way of detecting whether or not a file will register a plugin. Prior to this commit, Danger would run a regular expression against the file and validate that the file includes `< Plugin`. In the case of subclasses, this is very likely to fail.
Closes https://github.com/danger/danger/issues/682

Better detection of plugin registration

---

CHANGELOG.md
lib/danger/plugin_support/gems_resolver.rb
spec/lib/danger/plugin_support/gems_resolver_spec.rb

Fixes https://github.com/danger/danger/issues/688
And un-blocks Danger.Systems from deploying. This is obviously not the most elegant answer 👯 - but I'm happy enough, I did experiment with putting th return inside the chdir, but figured that was way more likely to break everything.
thanks @barbosa - who did the hard work on digging what was causing it

Fixes the plugin JSON parser -

---

CHANGELOG.md
lib/danger/request_sources/github.rb

Fixes #692 
`range_start` and `range_end` are integers. The comparison between two different `message.line`s are working because both are strings declared in the `Violation` [model](https://github.com/danger/danger/blob/master/lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb#L94-L95). But it doesn't for `message.line` and these ranges.
These two lines are raising an `ArgumentError`:
```ruby
break if message.line < range_start
next unless message.line >= range_start && message.line <= range_end
```
```
/home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.0.4/lib/danger/request_sources/github.rb:356:in `<': comparison of String with 1 failed (ArgumentError)
```
I don't know if `Violation#line` is really supposed to be a string, but changing it would affect the whole feature. So I …

Inline Comments: Transform `line` into an int before comparing it with ranges

---

CHANGELOG.md
lib/danger/ci_source/support/pull_request_finder.rb
spec/lib/danger/ci_sources/support/pull_request_finder_spec.rb

Fixes #691.
After this PR, can specify API host by the following command:
```
$ DANGER_GITHUB_API_HOST=https://foo.bar.com https://foo.bar.com/org/repo/pulls/111
```
/cc @mtitolo

Fix danger pr command cannot specify API host

---

CHANGELOG.md
lib/danger/comment_generators/github.md.erb
lib/danger/helpers/comments_helper.rb
lib/danger/helpers/find_max_num_violations.rb
spec/lib/danger/helpers/comments_helper_spec.rb

Fixes #698.
In [generated github markdown](https://github.com/danger/danger/blob/bf55d62f1847f8b45c356125163db7a582d156d2/lib/danger/comment_generators/github.md.erb#L17), we take a [static number of violations (700)](https://github.com/danger/danger/blob/bf55d62f1847f8b45c356125163db7a582d156d2/lib/danger/comment_generators/github.md.erb#L17) assume each message looks like `"warning #{i}"`.
In reality the warning is not fixed length, so we should adjust, and take dynamic number of violations within the length limit.

Improve handling of long comment

---

CHANGELOG.md
danger.gemspec
lib/danger/ci_source/bitrise.rb
lib/danger/ci_source/buildkite.rb
lib/danger/ci_source/circle.rb
lib/danger/ci_source/drone.rb
lib/danger/ci_source/jenkins.rb
lib/danger/ci_source/local_git_repo.rb
lib/danger/ci_source/semaphore.rb
lib/danger/ci_source/surf.rb
lib/danger/ci_source/teamcity.rb
lib/danger/ci_source/travis.rb
lib/danger/ci_source/xcode_server.rb
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
lib/danger/request_sources/github/github.rb
lib/danger/request_sources/github/github_review.rb
lib/danger/request_sources/github/github_review_resolver.rb
lib/danger/request_sources/github/octokit_pr_review.rb
spec/fixtures/github_api/pr_review_response.json
spec/fixtures/github_api/pr_reviews_response.json
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/request_sources/github/github_review_resolver_spec.rb
spec/lib/danger/request_sources/github/github_review_spec.rb
spec/lib/danger/request_sources/github_spec.rb
spec/lib/danger/request_sources/request_source_spec.rb

Hi, there this PR addresses an issue I opened a while ago #684. 
The status is kinda work in progress, but there is already functionality that can be potentially used.
The changes in this PR:
* new module `GitHubSource` to combine the only GitHub related features;
* new class `Review` under the `GitHubSource` module, which represents the pull request review object;
* extension to `octokit` which I think will be used until the API is not final and then I will create a PR to octokit itself with extension for pr reviews;
Here is an example of how it looks like in `Dangerfile`:
```ruby
github.review.start
github.review.fail("I can fail your PR in a moment")
github.review.warn("I'm warning yo")
github.review.message("100 message")
github.review.submit
```
You can check how it looks in a PR …

GitHub pull request review

---

CHANGELOG.md
lib/danger/comment_generators/github.md.erb
lib/danger/core_ext/string.rb
lib/danger/helpers/comments_helper.rb
spec/lib/danger/core_ext/string_spec.rb
spec/lib/danger/helpers/comments_helper_spec.rb

I totally like the idea of this html comment summary to show up in for example slack. As proposed in #701 and available in danger/danger-js#101.  This PR will add a 
```html
<!--
1 Error: This is an error
1 Warning: Violations that are very very ...
1 Message: This is a message
1 Markdown
--!>
```
comment to the top of dangers comment. What do you guys think?

Hk comment preview summary

---

CHANGELOG.md
lib/danger/ci_source/jenkins.rb
spec/lib/danger/ci_sources/jenkins_spec.rb

The [Bitbucket Branch Source Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Bitbucket+Branch+Source+Plugin) for Jenkins returns `CHANGE_URL` in format:
```
https://bitbucket.example.com/projects/PROJECT_NAME/repos/REPO_NAME/pull-requests/1/overview
```
Currently this url generates repo slug as `repos/REPO_NAME` which is incorrect and produce an issue with Bitbucket Server API because it cannot find project `repos`. This PR should fix this behaviour.

Improved support for Bitbucket Branch Source Plugin (Jenkins)

---

lib/danger/ci_source/support/local_pull_request.rb
lib/danger/ci_source/support/pull_request_finder.rb
lib/danger/helpers/comments_helper.rb
lib/danger/helpers/comments_parsing_helper.rb
spec/lib/danger/helpers/comments_helper_spec.rb

More feature-irrelevant cleanup. Looks like a bad merge long time ago duplicated the `parse_comment` method, which should really only live in the `comments_parsing_helper.rb`. Funny enough the methods diverged by now :)
This should sort things out. Rucocop is kinda awesome btw and told me we can now re-enable the ModuleLength check, ha! I am kinda confident in the test suite to delete rigorously, I think thats good, right ❓ 🎲

Hk misc cleanups #trivial

---

CHANGELOG.md
lib/danger/commands/local.rb
lib/danger/commands/local_helpers/pry_setup.rb
lib/danger/commands/pr.rb
spec/lib/danger/commands/local_helpers/pry_setup_spec.rb
spec/spec_helper.rb

Well after #729 I learned that `dange pr` and `danger local` do basically exactly the same thing except for setting one ENV var differently. This means I could apply the same refactoring to `danger pr` as well as remove further duplication in both those commands by extracting the `PrySetup` stuff.
The code is extracted with only those two changes I believe:
* I removed the following line, it appears `FileUtils.cp` does not care if the file exists already.
```ruby
File.delete "_Dangerfile.tmp" if File.exist? "_Dangerfile.tmp"
```
* I went from `require "pry"` to `Kernel.require "pry"` so I could stub it in the unit test.
*this branch*
2231 / 2777 LOC (80.34%) covered
*master*
2218 / 2799 LOC (79.24%) covered

Hk danger pr remove duplication

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb
lib/danger/request_sources/github/github_review_unsupported.rb
spec/lib/danger/request_sources/github_spec.rb

The review api is in beta and only available on github.com. As all of a
request sources methods are called once in danger local, this would try
to make a request to the review api which would fail. This pr provides a noop
review object incase the call to the review api fails with a 404.
Fixes #725

Fix support for github enterprise, no review possible

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb

https://github.com/NARKOZ/gitlab/pull/253 changed encoding behaviour, and we depend on master branch of the gem. So we need to run after it 💃 This is whats failing in #735. And alternative approach to fixing this was taken in #737, though I think I prefer this one here 🍡

Gitlab project names dont need to be urlencoded

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb

what did i do:
- move `file_header_regexp` check to the beginning of `each` block. 
- make `file_header_regexp` more strict to avoid unexpected match.
For the following code:
https://github.com/danger/danger/blob/master/lib/danger/request_sources/github/github.rb#L360-L364
` line.match file_header_regexp` will never be matched since the `line`  must match to `range_header_regexp `. to reach this line of code.
And then `find_position_in_diff` will fall down to other files to find the diff line. when the other files happened to has a range just match the message's line number, a wrong inline comment will be created and finally caught an error from github.

only find diff position in current file

---

CHANGELOG.md
lib/danger/ci_source/jenkins.rb
spec/lib/danger/ci_sources/jenkins_spec.rb

Fix Issue when GitHub repo's name contains dot.
`repo_slug` became `nil` when the repo's name has a dot in it. (e.g.  johnlinvc/test-2.0)
Handle repo name with dot correctly in `CISource::Jenkins#initialize`

fix nil repo_slug when repo name contains dot

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb

The inline comment seems to use a fixed `https://github.com/` url regardless the `DANGER_GITHUB_HOST` setting, when using github enterprise, the inline comment fails and the link in comment is broken.
Try to use `host` in the url instead of `https://github.com/`

Fix inline comment url

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb
spec/lib/danger/request_sources/github_spec.rb

Fix two bugs with inline comment:
- when violations is all inline comment, those message which is out of range will not shown  in main comment due to the wrong check of `main_violations`
- when there is only makrdowns inline comment, it won't be post as inline.

fix inline comment's fall back bugs

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
lib/danger/request_sources/github/github.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/request_sources/github_spec.rb

a simple approach for #742.
since the inline message is currently only available in github, add an property for `github request_source` and an interface in `github plugin` to set it.

Only show inline in diff

---

Gemfile
spec/fixtures/gitlab_api/merge_request_593728_comments_existing_danger_comment_response.json
spec/fixtures/gitlab_api/merge_request_593728_comments_no_stickies_response.json
spec/fixtures/gitlab_api/merge_request_593728_comments_response.json
spec/lib/danger/request_sources/gitlab_spec.rb
spec/support/gitlab_helper.rb

This PR fixes the build (Follow up of https://github.com/danger/danger/pull/738).
- There are some more places no need to be escaped slug
<details>
<summary>Error</summary>
```
WebMock::NetConnectNotAllowedError:
Real HTTP connections are disabled. Unregistered request: GET https://gitlab.com/api/v3/projects/k0nserv/danger-test/merge_requests/593728/notes with headers {'Accept'=>'application/json', 'Private-Token'=>'a86e56d46ac78b'}
You can stub this request with the following snippet:
stub_request(:get, "https://gitlab.com/api/v3/projects/k0nserv/danger-test/merge_requests/593728/notes").
with(:headers => {'Accept'=>'application/json', 'Private-Token'=>'a86e56d46ac78b'}).
to_return(:status => 200, :body => "", :headers => {})
registered request stubs:
stub_request(:delete, …
```

Fix build: The slug of gitlab url no need to be escaped now #trivial

---

CHANGELOG.md
lib/danger/commands/local.rb
lib/danger/commands/pr.rb
spec/lib/danger/commands/local_spec.rb
spec/lib/danger/commands/pr_spec.rb

Because CLAide doesn't support short switch at the moment (https://github.com/CocoaPods/CLAide/pull/60), so `danger pr -h` errors out. This PR fixes part of https://github.com/danger/danger/issues/744. `danger pr -h` will now print help text instead of error out. Also add this for `danger local`.
Before
```
$ danger pr -h
/Users/juanito-fatas/.gem/ruby/2.3.2/gems/danger-4.2.2/lib/danger/ci_source/local_git_repo.rb:61:in `raise_error_for_missing_remote': danger cannot find your git remote, please set a remote. And the repository must host on GitHub.com or GitHub Enterprise. (RuntimeError)
from /Users/juanito-fatas/.gem/ruby/2.3.2/gems/danger-4.2.2/lib/danger/ci_source/local_git_repo.rb:43:in `initialize'
from /Users/juanito-fatas/.gem/ruby/2.3.2/gems/danger-4.2.2/lib/danger/danger_core/envi …
```

Make danger pr & local commands recognize -h to print help

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb

in `find_position_in_diff`, the diff hunk's `range_end` should not contain the last line.
when a inline comment happened to be found at the `range_end` line, it get an invalid position which is out of the diff.
like this:
the range is 9 - 15, not 9 - 16(which is `match[:start] + match[:end]`).

fix wrong inline comment position at last line

---

lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb

In import_dangerfile, opts `file:` does not work, but `path:` works.

Fix a wrong doc in dangerfile_danger_plugin

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb

With the `dismiss_out_of_range_messages` options, only comment within the diff's range will shown as inline comment.
But in diff's range does not mean it's a change since diff contains unchanged lines. so also ignore those comments at unchanged line too when `dismiss_out_of_range_messages` is enabled.

Add inline comments to changed lines only

---

CHANGELOG.md
lib/danger/ci_source/buddybuild.rb
spec/lib/danger/ci_sources/ci_source_spec.rb

Hey guys! 🎉
So this is my first PR here, and first in ruby, so I'm sorry for everything wrong here :D
Basically, Danger can be used with buddybuild and it is pretty easy! But on the website there was no info about it, so I've decided to make a new `ci_source` just with documentation. Dunno if the ruby code is correct here, so I'd love a review for that. I've also added a caveat that you can change the bot that is used by Danger (simply by adding a new token to the ENV vars), but I had the chance of testing it only using GitHub project - but you can also create projects using GitLab and Bitbucket. If anyone has any info about these two, it would be awesome as well.
Cheers! 
**Edit:** Also I'm not sure, should I write test spec for this class?

Add buddybuild documentation.

---

.rubocop.yml
CHANGELOG.md
Dangerfile
danger.gemspec
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/plugins/dangerfile_bitbucket_cloud_plugin.rb
lib/danger/danger_core/plugins/dangerfile_bitbucket_server_plugin.rb
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
lib/danger/request_sources/bitbucket_cloud.rb
lib/danger/request_sources/bitbucket_cloud_api.rb
lib/danger/request_sources/bitbucket_server.rb
lib/danger/request_sources/bitbucket_server_api.rb
lib/danger/request_sources/github/github.rb
lib/danger/request_sources/github/github_review.rb
lib/danger/request_sources/github/github_review_resolver.rb
lib/danger/request_sources/github/github_review_unsupported.rb
lib/danger/request_sources/github/octokit_pr_review.rb
lib/danger/request_sources/gitlab.rb
lib/danger/scm_source/git_repo.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb
spec/lib/danger/helpers/comments_helper_spec.rb
spec/lib/danger/plugin_support/plugin_parser_spec.rb
spec/lib/danger/request_sources/bibucket_cloud_spec.rb
spec/lib/danger/request_sources/bibucket_server_spec.rb
spec/lib/danger/request_sources/github_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb

Attempt to help #660.
Workaround steals from [git fetch --unshallow no longer working - travis-ci/travis-ci #4942](https://github.com/travis-ci/travis-ci/issues/4942).

Attempt to workaround the shallow fetch problem

---

lib/danger/commands/init_helpers/interviewer.rb
spec/lib/danger/commands/init_helpers/interviewer_spec.rb

#trivial
I executed `danger init` on latest danger. So this error was raised.
```
Step 2: Creating a GitHub account
In order to get the most out of Danger, I'd recommend giving her the ability to post in
the code-review comment section.
IMO, it's best to do this by using the private mode of your browser. Create an account like
DangerplaygroundBot, and don't forget a cool robot avatar.
Here are great resources for creative commons images of robots:
bundler: failed to load command: danger (/Users/giginet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bin/danger)
NoMethodError: undefined method `underline' for #<String:0x007fcf0ead95a0>
Did you mean?  underlined
underlined!
/Users/giginet/.ghq/github.com/danger/danger/lib/danger/commands/init_helpers/interviewer.rb:36:in `link' …
```

Use underlined instead of underline

---

.travis.yml
CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_git_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_git_plugin_spec.rb
spec/lib/danger/scm_source/git_repo_spec.rb

We've encountered a crash inside `git.diff_for_file` when PR/MR diff includes files moved to other folders.
It looks like [the code](https://github.com/danger/danger/blob/8e9a3ab12a78c518fac6dd917878fc3fc4f55b2a/lib/danger/danger_core/plugins/dangerfile_git_plugin.rb#L115) is not enough to handle moves, here's how moved files are represented in `git.modified_files`:
```
Whatever/Path/{<old subpath> => <new subpath>}/File.m
```
But [@git.diff](https://github.com/danger/danger/blob/8e9a3ab12a78c518fac6dd917878fc3fc4f55b2a/lib/danger/danger_core/plugins/dangerfile_git_plugin.rb#L115) doesn't have an entry for a such path, it contains an entry for the original path of the moved file.
The first idea was to detect such modified files, extract original file name and get the diff. The problem is, …

Fixing handling of files moved to other directories in git.diff_for_file

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_git_plugin.rb
spec/lib/danger/scm_source/git_repo_spec.rb

Looks like a previous change caused `git.diff_for_file(file)` to return `nil` if the file was an _added file_.

Fix diff_for_file for added files

---

.travis.yml
CHANGELOG.md
Gemfile
Rakefile
bin/chandler
spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb
spec/support/gitlab_helper.rb

Somehow the travis deploy script wasn't working, so now I've improved the `rake release` task to also run chandler if you have either one of those ENV vars in your shell.

Gitlab gem update + Make chandler run on `rake release`

---

CHANGELOG.md
lib/danger/ci_source/drone.rb
spec/lib/danger/ci_sources/drone_spec.rb
spec/lib/danger/danger_core/executor_spec.rb
spec/support/ci_helper.rb
spec/support/gitlab_helper.rb

Updating the drone CI source library to support versions 0.4+ because some syntax seems to have changed and more environment parameters are available.
- `spec/support/gitlab_helpers.rb` depends on DroneCI parameters. I think this is not a good practice. Maybe using a dedicated CI source for testing?
- There are 20 tests failing (both on master and my branch) from gitlab. Not sure if they are like that on purpose, but I think all of them were failed mock requests.
- I'm new to Ruby, if there's something that is not good practice or can be improved please tell me.
- It seems that DroneCI changes stuff on every minor release, so having backwards compatibility is going to be a pain.
Is there any gitter/irc channel to talk/ask questions about danger?

DroneCI 0.4+ support

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb
spec/support/gitlab_helper.rb

Previously we only fetched the first page which means
that when the danger comment is not on the first page it
adds new comments instead of updating the existing one.

[Gitlab] Fetch all MR comments

---

CHANGELOG.md
lib/danger/ci_source/dotci.rb
spec/lib/danger/ci_sources/ci_source_spec.rb
spec/lib/danger/ci_sources/dotci_spec.rb

- Used the Jenkins source as a starting point and went from there.
- Adds support for DotCi: https://github.com/groupon/dotci
- I've validated on a DotCi build.

Add support for DotCi CI source

---

CHANGELOG.md
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/standard_error.rb
spec/fixtures/dangerfile_with_error
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/danger_core/standard_error_spec.rb

Hi! These changes send errors occurred in `Dangerfile` to PR. Also I add specs for `DSLError` class.

Send DSLError to pull request

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_git_plugin.rb
lib/danger/scm_source/git_repo.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_git_plugin_spec.rb
spec/lib/danger/scm_source/git_repo_spec.rb

Hi. This add ability to access list of renamed files via `git.renamed_files`.
`git.renamed_files` will return Array with Hashes that have keys `:before` and `:after`.
```
[
{ before: "README", after: "README.MD" },
{ before: "some/path/file", after: "some/other/path/file" }
]
```
Unfortunately [git gem](https://github.com/schacon/ruby-git) that we are using, has tough limited api which don't provide ability to pass some options for diff output customization. 
So I decided to use `git diff  --diff-filter=R`, which returns something like this:
```
[
"diff --git a/README b/README.MD\n", 
"similarity index 100%\n", 
"rename from README\n", 
"rename to README.MD\n", 
"diff --git a/hello1 b/hello1_renamed\n", 
"similarity index 100%\n", 
"rename from hello1\n", 
"rename to hello1_renamed\n", …
```

Add ability to get list of renamed files

---

.rubocop.yml
CHANGELOG.md
lib/danger/request_sources/github/github.rb
spec/lib/danger/request_sources/github_spec.rb

This should fix https://github.com/danger/danger/issues/703. I rewrite `update_pull_request!`, `submit_inline_comments!`, `submit_inline_comments_for_kind!` to not mutate violations and to apply sort only for inline comments.
Root of evil was in sort proc:
```
cmp = proc do |a, b|
next -1 unless a.file
next 1 unless b.file
next a.line <=> b.line if a.file == b.file
next a.file <=> b.file
end
```
Ruby uses [Quicksort](https://en.wikipedia.org/wiki/Quicksort) algorithm, which is pretty fast but can be unstable with not correct usage as ruby doc [says](https://ruby-doc.org/core-2.2.0/Array.html#method-i-sort). For example:
```
:001 > [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].sort { -1 }
=> [10, 2, 3, 4, 5, 1, 7, 8, 9, 6]
```
So when sort proc receives array where all comments not inline, order blew to …

Fix broken violations order for github

---

CHANGELOG.md
appveyor.yml
lib/danger/core_ext/file_list.rb
lib/danger/helpers/array_subclass.rb
spec/lib/danger/danger_core/plugins/dangerfile_git_plugin_spec.rb
spec/lib/danger/helpers/array_subclass_spec.rb
spec/lib/danger/scm_source/git_repo_spec.rb

Fixes https://github.com/danger/danger/issues/155. This can't be done via normal subclassing without overriding a lot of methods, so i decided to do this in delegation way. 
Please note, that:
```
class List; include Danger::Helpers::ArraySublcass; end
class OtherList; include Danger::Helpers::ArraySublcass; end
List.new([1, 2, 3]) == OtherList.new([1, 2 ,3])
=> false
List.new([1, 2, 3]) == [1, 2 ,3]
=> false
List.new([1, 2, 3]) == List.new([1, 2, 3])
=> true
List.new([1, 2, 3]).is_a?(Array)
=> true
List.new([1, 2, 3]).is_a?(OtherList)
=> false
```
But this can be changed easily.

Fix FileList returning arrays

---

CHANGELOG.md
lib/danger/commands/init.rb
spec/lib/danger/commands/init_spec.rb

This improves remotes parsing for init command and resolves #821 .
```
git@github.com:author/repo.git => author/repo
https://github.com/author/repo.github.io.git => author/repo.github.io
http://example.com => [Your/Repo]
```

Improve remotes parsing for init command

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
lib/danger/request_sources/github/github.rb
spec/lib/danger/request_sources/github_spec.rb

issue : [Add ability to set dismiss\_out\_of\_range\_messages per each message kinds · Issue \#831 · danger/danger](https://github.com/danger/danger/issues/831)
Added the feature to set dismiss_out_of_range_messages per kind.
```ruby
dismiss_out_of_range_messages({
error: false,
warning: true,
message: true,
markdown: true
})
```
If it is set as above, all errors are commented and warnings out of ranges are dismissed.
Also, you can set boolean. it works same with prior.
```ruby
dismiss_out_of_range_messages(true)
```

Added feature to set dismiss_out_of_range_messages per kind

---

lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_github_plugin_spec.rb

Fix the problem of #832
#832 doesn't work fine. So I fixed in this PR. 🙇 
You can set like following on `Dangerfile`.
I tried this feature, it works fine for me.
```ruby
dismiss_out_of_range_messages({
error: false,
warning: true,
message: true,
markdown: true
})
```
I added tests for `Dangerfile`.

#trivial Fix the issue dismiss_out_of_range_messages

---

CHANGELOG.md
lib/danger/scm_source/git_repo.rb
spec/lib/danger/scm_source/git_repo_spec.rb

Resolves #838 . It turned out that `git.log` has implicit commits count param. Which [equal 30 by default](https://github.com/schacon/ruby-git/blob/master/lib/git/log.rb#L7).

Fix wrong commits count for PR's that have more than 30 commits

---

CHANGELOG.md
lib/danger/helpers/comments_helper.rb

This PR fixes a small typo that causes Danger to crash in my current setup (gitlab.com repo with GitLab CI runner to execute Danger).
The "original" version of the `markdown_link_to_message` method ([github.rb#L419](https://github.com/danger/danger/blob/master/lib/danger/request_sources/github/github.rb#L419)) also uses `message` and not `messages`.
```
$ if [ -n "${CI_MERGE_REQUEST_ID}" ]; then bundle exec danger --version && bundle exec danger; fi
5.2.2
bundler: failed to load command: danger (/Users/ci-user/builds/7e7afdcc/0/demo-app/ios/vendor/ruby/2.4.0/bin/danger)
NameError: undefined local variable or method `messages' for #<Danger::RequestSources::GitLab:0x007fef7899c1d0>
Did you mean?  message
/Users/ci-user/builds/7e7afdcc/0/demo-app/ios/vendor/ruby/2.4.0/gems/danger-5.2.2/lib/da …
```

Fix undefined local variable or method `messages'

---

CHANGELOG.md
lib/danger/ci_source/local_git_repo.rb
spec/lib/danger/ci_sources/local_git_repo_spec.rb

Git commit messages can contain non UTF-8 characters, which can cause exceptions in Ruby when the string is manipulated. This PR ensures the results of the git execution are explicitly encoded in UTF-8 by removing any invalid characters.

Explicitly Encode Git Execution in UTF-8

---

CHANGELOG.md
lib/danger/commands/runner.rb

Since the danger.systems is moved to gitlab, the `danger plugins list` should search list from gitlab instead of github.

update plugin list to gitlab

---

CHANGELOG.md
lib/danger/ci_source/xcode_server.rb
spec/lib/danger/ci_sources/xcode_server_spec.rb

Noticed that Bitbucket-Cloud is not available on XcodeServer.
I saw no reason why this wouldnt work now.
Please let me know if i missed something.

add bitbucket_cloud to xcode_server supported_request_sources

---

.rubocop.yml
CHANGELOG.md
lib/danger/request_sources/github/github.rb

Danger crashed and stopped CI Job because of Octokit::UnprocessableEntity when use github inline-comments.
This is maybe Danger's bug but the causes could not found because its error has no information.
So, it makes to show more detail for UnprocessableEntity, and not fail CI job.
See detail: https://github.com/danger/danger/issues/774

Show more detail for UnprocessableEntity

---

CHANGELOG.md
lib/danger/ci_source/buddybuild.rb
spec/lib/danger/ci_sources/buddybuild_spec.rb

[Buddybuild](https://buddybuild.com) will drop the native support we have for Danger to encourage people to use [custom build steps instead](https://www.buddybuild.com/blog/customizing-the-build-process)
This PR adds **actual** support for buddybuild. I will run some test on my side to make sure it works (so far it does), but in the meantime, is there anything else I need to do? I'm mostly curious about Github Enterprise and Bitbucket server.

Add buddybuild support

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb
spec/lib/danger/ci_sources/buddybuild_spec.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_messaging_plugin_spec.rb
spec/lib/danger/helpers/comments_helper_spec.rb
spec/lib/danger/request_sources/github_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb
spec/spec_helper.rb

This should resolve https://github.com/danger/danger/issues/856. 
I extended danger messaging plugin api a little bit, so now it supports such usage:
```
message 'Hello World!'
message 'Hello', 'World!', file: 'foo.rb', line: 1
message ['Hello', 'World!'], sticky: true
```
Also I renamed `violation` and `markdown` factory methods from `spec_helper.rb`, cause they conflicted with messaging file api and I did not find better way to solve this 😞 
And make rubocop green again 💚 💚 💚

Multiple messages

---

CHANGELOG.md
lib/danger/ci_source/gitlab_ci.rb
lib/danger/request_sources/gitlab.rb
spec/fixtures/gitlab_api/merge_request_593728_comments_existing_danger_comment_response.json
spec/fixtures/gitlab_api/merge_request_593728_comments_no_stickies_response.json
spec/fixtures/gitlab_api/merge_request_593728_comments_response.json
spec/fixtures/gitlab_api/merge_requests_response.json
spec/lib/danger/ci_sources/gitlab_ci_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb
spec/support/gitlab_helper.rb

This should resolve https://github.com/danger/danger/issues/860.
It turned out, that support for v4 doesn't require a lot of changes. But we need to check that everything works as expected, right now we support gitlab for:
- ~~[Bitrise](https://www.bitrise.io)~~ ✅ 
- ~~[Buddybuild](https://www.buddybuild.com)~~ ✅ 
- [Buildkite](https://buildkite.com)
- [Drone](https://github.com/drone/drone)
- [GitLabCI](https://about.gitlab.com/features/gitlab-ci-cd)
- ~~[Jenkins](https://jenkins.io)~~ ✅ 
- [TeamCity](https://www.jetbrains.com/teamcity)
So, I will appreciate any help in testing the remaining ci's 🙏 
You can do this via my danger fork:
```ruby
gem 'danger', github: 'sleekybadger/danger', 
branch: 'feature/gitlab-api-v4'
```
Right now, if you will use this PR, make sure that you have …

Support for gitlab api v4

---

CHANGELOG.md

Simple edit to CHANGELOG.md file. Pretty sure the latest was supposed to be `5.3.4` as per the commit https://github.com/danger/danger/commit/942420b85a76e6970e9eb3bc01e3e2d14091a673

Correct CHANGELOG title for latest version to 5.3.4

---

CHANGELOG.md
danger.gemspec
lib/danger/commands/pr.rb
spec/lib/danger/commands/pr_spec.rb

- Add tests for verify ssl
- Add no_proxy_fix gem to fix issue in Ruby 2.4.0/2.4.1
As discussed in https://github.com/danger/danger/issues/830
Done with the help of @winston

Add `verify_ssl` argument to skip ssl verification

---

lib/danger/ci_source/gitlab_ci.rb

This is a very simple PR, just change the `==` operator to `>=` according to [ruby doc](https://ruby-doc.org/core-2.2.0/Array.html#method-i-bsearch)

Fix implementation of bsearch in GitlabCI#determine_merge_request_id

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb
spec/lib/danger/request_sources/github_spec.rb

This is similar to #880, in that it allows toggling of Octokit's SSL Verification. In #880, only the `pr` command had an option to toggle SSL verification (e.g. `bundle exec danger pr --verify-ssl`). 
While that PR added the verification toggling for PR, danger (`bundle exec danger`) itself didn't have the option to toggle SSL Verification. After looking through `runner.rb` and how it passes arguments down to Octokit, I surmised that a clean way to allow toggling would be to simply read an environment variable (`DANGER_OCTOKIT_VERIFY_SSL`) that would be used by `Octokit` when starting up the Octokit client. 
This would prevent introducing a new argument in command line and having to pass that down several layers to get Octokit to use it from within `github.rb`. 
As should be expected, not …

Add support for toggling SSL Verification for Octokit

---

CHANGELOG.md
lib/danger/danger_core/messages/violation.rb
spec/lib/danger/danger_core/plugins/messages_spec.rb
spec/spec_helper.rb

It was showing file and line when they are empty and not showing when they are set.
Originally `spec/lib/danger/danger_core/plugins/messages_spec.rb` which I've added was failing like this.

Fix Violation#to_s

---

CHANGELOG.md
lib/danger/ci_source/codeship.rb
lib/danger/ci_source/semaphore.rb
lib/danger/request_sources/github/github.rb
spec/lib/danger/ci_sources/ci_source_spec.rb

Added [codeship](https://codeship.com/) as a new CI source. I mostly copied the style of the Semaphore CI source, and used the same logic that [danger.js uses](https://github.com/danger/danger-js/blob/master/source/ci_source/providers/Codeship.ts#L40) in getting a PR from a branch name.

Add support for Codeship CI

---

.travis.yml
Gemfile

I'm not really sure _why_ the `bundle exec` is  being ignored, so I want to first verify that it's using 0.50.x

Look at locking the rubocop version

---

CHANGELOG.md
lib/danger/commands/local_helpers/pry_setup.rb

Fix possible invalid `binding.pry` statement when Dangerfile does not have an empty new line at the end, when using `danger pr --pry`, by adding a newline manually.  
I discovered this bug when my Dangerfile ended with the keyword `end` and so the final line in the `_Dangerfile.tmp` was `endbinding.pry; File.delete("_Dangerfile.tmp")`, which resulted in an error.

Insert newline before binding.pry on _Dangerfile.tmp

---

CHANGELOG.md
lib/danger/ci_source/jenkins.rb
spec/lib/danger/ci_sources/jenkins_spec.rb
spec/lib/danger/danger_core/environment_manager_spec.rb
spec/lib/danger/danger_core/executor_spec.rb
spec/support/ci_helper.rb

Currently, it failed with 404 errors.
According to gitlab's API doc we should be use merge_request_iid instead of
merge_request_id.
ref: https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr
include …

Fix bug with gitlab v4 API

---

CHANGELOG.md
lib/danger/ci_source/bitrise.rb

The limitation of BitRise and Secret env vars in PRs that is pointed to in the documentation has just been [addressed by Bitrise 6 days ago](https://discuss.bitrise.io/t/secret-env-vars-and-generic-file-storage-files-control-whether-its-available-in-pull-request-builds/718/8).
This means that we can update the documentation accordingly now 🎉

Update Bitrise doc now that secret env vars are supported #trivial

---

lib/danger/request_sources/gitlab.rb
spec/fixtures/gitlab_api/merge_request_593728_no_commits_response.json
spec/lib/danger/request_sources/gitlab_spec.rb

#trivial GitLab API may return an empty list of commits and in this situation, danger fails with runtime error without explanation. This changes can process this kind of situations and raise danger error with a better explanation.

Fix empty commits list error on GitLab

---

CHANGELOG.md
lib/danger/ci_source/gitlab_ci.rb

`bsearch` can't be used on an array not sorted by `mr.sha`. See discussion: https://github.com/danger/danger/pull/883#issuecomment-334143581.

Use linear search to get GitLab MR ID in GitLab CI

---

lib/danger/request_sources/vsts.rb
spec/fixtures/vsts_api/danger_comments_response.json
spec/fixtures/vsts_api/no_danger_comments_response.json
spec/lib/danger/request_sources/vsts_spec.rb
spec/support/vsts_helper.rb

This fixes the VSTS commenting logic.
At this point, the VSTS module looks for the `new_comment` flag to decide if it should post a new comment or not - which is set to false.
It then tries to update the previous comment which doesn't exist for a new pull request.
The fix looks for any comment posted by danger to determine if a previous comment was posted and tries to update it.
If no comment added by danger is found, it adds a new comment.

Fix VSTS comments

---

lib/danger/ci_source/gitlab_ci.rb

I suppose this is the right environment variable. GitHub token doesn't make sense here for me.

#trivial Fix GitLab Setup — GitHub env variable to GitLab env variable

---

lib/danger/danger_core/plugins/dangerfile_bitbucket_server_plugin.rb

This closes the issue #915 that I opened yesterday.
Basically, the example shown in the documentation was off. Keys have to be clarified via colon and the logic on the warning was wrong:
You want to warn if there's no assignee to the PR, not if there is one assigned. 
Tested it internally fwiw.

#trivial: Fixed "Ensure that all PRs have an assignee" example logical error

---

CHANGELOG.md
lib/danger/core_ext/file_list.rb
spec/lib/danger/core_ext/file_list_spec.rb

I had a filename with some square brackets in them that `diff_for_file` was not properly finding in `(added_files + modified_files).include?(file)`.
It seems `File.fnmatch` recognizes brackets as special tokens and not literally. I suppose this might cause some extremely rare and subtle issues where we mistakenly capture a filename with asterisks (or other glob characters), but I think the case I ran into is more likely tbh.
Basically, I was seeing the following:
```ruby
filename = "file/with/bracket[].txt"
filenames = [ filename ]
filenames.include?(filename) == false
```
---
```
bundler: failed to load command: danger (/Users/distiller/.gem/ruby/2.3.4/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined method `patch' for nil:NilClass …
```

Fix filename comparisons that include brackets

---

CHANGELOG.md
lib/danger/ci_source/buildkite.rb
spec/lib/danger/ci_sources/buildkite_spec.rb

The PR corrects the regex that was used to extract the Github repo slug to handle repositories with periods (dots) in them.

Handle Github repos with dots in them

---

CHANGELOG.md

This PR fixes a few typos in CHANGELOG.md. It was created using https://github.com/tbroadley/github-spellcheck-cli.

docs: fix typos

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb
spec/lib/danger/request_sources/gitlab_spec.rb

Based on the experience and feedback in #926 
An error will be raised if you accidentally include the port number in `DANGER_GITLAB_HOST`.

Raise error if port number is included in DANGER_GITLAB_HOST

---

CHANGELOG.md
lib/danger/ci_source/bitrise.rb

Simply added Bitbucket Server to the `supported_request_sources` of the Bitrise CI source, see issue #939.
Tested it in one of our Bitrise workflows and it works. I'm not sure if I should add any tests and/or documentation for this. I didn't see specific tests for buddybuild - Bitbucket Server support for example.

Enable Bitbucket Server support for Bitrise CI

---

CHANGELOG.md
Dangerfile
lib/danger/ci_source/teamcity.rb
lib/danger/request_sources/bitbucket_cloud.rb
lib/danger/request_sources/bitbucket_cloud_api.rb
spec/fixtures/bitbucket_cloud_api/prs_response.json
spec/lib/danger/ci_sources/teamcity_spec.rb
spec/lib/danger/request_sources/bitbucket_cloud_api_spec.rb
spec/support/bitbucket_cloud_helper.rb

- this involves adding a little hack where we provide TeamCity with
the branch name and it asks the Bitbucket API for the corresponding
pull request id
- this assumes a 1:1 mapping from branchs to PRs
This approach could maybe be used to add Bitbucket Cloud support to other CI providers but TeamCity is what we're using so thats what I tested it with. Speaking of, I tested this on our project (which uses TeamCity x Bitbucket) and it works, which is awesome.
Are there docs I need to update somewhere? The feature matrix on http://danger.systems/ruby/ basically seems to imply that Bitbucket isn't supported?

Add Bitbucket Cloud support for TeamCity

---

CHANGELOG.md
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/messages/markdown.rb
lib/danger/danger_core/messages/violation.rb
spec/lib/danger/danger_core/dangerfile_spec.rb

Currently the `validations_reports` hash is a freezed map with messages/errors/etc. If we somehow have duplicated messages we end up having the exact same messages under a category.
In my case this occurs because I have a ton of test reports and the `danger-junit` gem posts the `'A test failed'` message for each. Since I cant operate over the `validation_reports` hash because its freezed, I ended up having N times the `'A test failed'` message
I will make later a PR to @orta in the `danger-junit` gem, but I thought this would be a desired logic for danger itself (whats the point of having twice the exact same message under a category?)

Use distinct on validations prior to publish

---

CHANGELOG.md
lib/danger/ci_source/teamcity.rb
lib/danger/request_sources/bitbucket_server.rb
spec/lib/danger/ci_sources/teamcity_spec.rb

Added support for Bitbucket Server to TeamCity CI. Because TeamCity doesn't setup all the required variables those need be added to the ENVIRONMENT variables.
Tested it on our TeamCity and Bitbucket Server setup and it is working if all the required variables are set. Also added support for older versions of Bitbucket Server API which provide latestChangeset instead of latestCommit.

Added support for Bitbucket Server to TeamCity CI

---

CHANGELOG.md
lib/danger/commands/local.rb
lib/danger/commands/pr.rb
lib/danger/commands/runner.rb
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/executor.rb
lib/danger/request_sources/bitbucket_cloud.rb
lib/danger/request_sources/bitbucket_server.rb
lib/danger/request_sources/github/github.rb
lib/danger/request_sources/gitlab.rb
lib/danger/request_sources/vsts.rb
spec/lib/danger/commands/runner_spec.rb
spec/lib/danger/danger_core/dangerfile_spec.rb

This PR adds `--remove-previous-comments` CLI flag. The flag can be used in order to get the new danger comments in the tail of the PR and remove previous comments, so the PR looks bot so spammy.
Closes #948

Add --remove-previous-comments functionality

---

.gitignore
CHANGELOG.md
lib/danger/ci_source/bitrise.rb
spec/lib/danger/ci_sources/bitrise_spec.rb

Applies the regex fix from #922 to the Bitrise CI initialization to support repository names with dots in them, like `artsy/artsy.github.io`.
This resolves #928.

Support dots in repo names for Bitrise

---

.rubocop.yml
CHANGELOG.md
Dangerfile
Gemfile
danger.gemspec
spec/lib/danger/helpers/comments_helper_spec.rb

I still see warnings while visit danger/danger:
that's because we specify two rubocop in gemspec and Gemfile. Let's specify all dev dependencies in Gemfile.
This PR:
- move dev dependencies to Gemfile, sort alphabatically
- Let's try turn the plugins lint back on, disabled in #942
- Rubocop updates for 0.49.1

Security Updates for rubocop, take 2

---

CHANGELOG.md
lib/danger/ci_source/circle.rb
spec/lib/danger/ci_sources/circle_spec.rb

Circle CI supports BitBucket Cloud.
For Danger, it should be as simple as adding it as a supported request source on Circle CI, as it is already checking the environment variables.

Enable BitBucket Cloud for Circle CI

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb

The url for GitLab repos follows the structure `https://{host}/{user}/{project_name}`.
Currently, when submitting a PR from an external repo, `html_link` creates a url like `https://{host}/{orig_repo_user}/{external_repo_user}` instead of `https://{host}/{external_repo_user}/{project_name}`.
This PR tries to fix it.

Fix GitLab "html_link" for external repos

---

CHANGELOG.md
lib/danger/scm_source/git_repo.rb

A patch for fixing
- https://github.com/danger/danger/issues/965
- https://github.com/danger/danger/issues/904
- https://github.com/danger/danger/issues/966
I've tried this patch in my environment and it solves all of the crashes.

Removing `--all` option for `git merge-base`

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb

Forks.
The problem is occurred when I use multistage `import_dangerfile` like this.
My Dangerfile
```ruby
danger.import_dangerfile(github: "tbrand/danger1")
```
Dangerfile at `tbrand/danger1`
```ruby
danger.import_dangerfile(github: "tbrand/danger2")
```
Dangerfile at `tbrand/danger2`
```ruby
message "hello"
```
When I execute `danger pr` for it, it falls into infinite loop.
After debugging, I've found that this line disturbs updating `@download_url`.
https://github.com/danger/danger/blob/dbfd46e6350ae5dd30ca3ebcc0872d6b68f1a6cf/lib/danger/request_sources/github/github.rb#L468
So `github.rb#file_url` always returns the same url even if the actual `@download_url` is updated.
The history of the line is here.
https://github.com/danger/danger/pull/772
I may know you've lost a motivation for …

Fix a multistage `import_dangerfile` error

---

CHANGELOG.md
lib/danger/core_ext/file_list.rb
lib/danger/helpers/array_subclass.rb
spec/lib/danger/helpers/array_subclass_spec.rb

Previously, the helper was named `ArraySublcass`. This renames it to `ArraySubclass`.

Fix array sublcass typo

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb

Initially reported in #924
Having multiple messages with the same file but at least one without line would cause sorting to crash as `nil <=> 1` is `nil`.
```ruby
warn("A warning", file: "A.file", line: nil) 
warn("A warning", file: "A.file", line: 1)
warn("A warning", file: "A.file", line: nil)
```

Fix crash on nil lines

---

CHANGELOG.md
lib/danger/danger_core/executor.rb
spec/lib/danger/danger_core/executor_spec.rb

Hiya 👋 
When danger runs and finds a valid CI environment, but does not find a valid PR, you end up with a failure message like `Not a Pull Request - skipping 'danger' run`
This PR injects the CI name into that error message. e.g. `Not a Travis Pull Request - skipping 'danger' run`, to add a little more context.
Handy for debugging on non-supported CIs. Yep, there are still a few of those left. :)

Notes which CI is used when exiting with an invalid PR

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_messaging_plugin_spec.rb

If `nil` is unexpectedly passed to `message|warn|fail`, Danger will crash. While the Dangerfile should resolve this so that it doesn't happen in the first place, it's probably safer to do nothing IMO.

Fix crash when messages are nil

---

CHANGELOG.md
lib/danger/ci_source/gitlab_ci.rb
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
spec/fixtures/gitlab_api/merge_requests_response.json
spec/lib/danger/ci_sources/gitlab_ci_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb
spec/spec_helper.rb
spec/support/ci_helper.rb
spec/support/gitlab_helper.rb

This fixes a few issues with the GitLab integration:
- In GitLab, `ENV["CI_PROJECT_ID"]` returns the project's ID, not its path/slug. `ENV["CI_PROJECT_PATH"]` should be used instead, see https://docs.gitlab.com/ee/ci/variables/README.html.
- Unfortunately, the stubbed environment was setting `ENV["CI_PROJECT_ID"]` with a project slug (e.g. `danger/danger`). That's why the specs passed even though the feature was broken. The environment stubbing is now fixed.
- `Danger::DangerfileGitLabPlugin#html_link` has been simplified to use `ENV["CI_PROJECT_URL"]`.
Fixes #969.

Fix Danger::GitLabCI to use CI_PROJECT_PATH instead of CI_PROJECT_ID for its #repo_slug

---

CHANGELOG.md
lib/danger/ci_source/screwdriver.rb
spec/lib/danger/ci_sources/screwdriver_spec.rb

SCM_URL usually include a branch name
Ex. `git@github.com:danger/danger.git#branch`
repo_slug -> `danger/danger`
repo_url -> `git@github.com:danger/danger.git`
with the current logic, Danger will pick up a wrong repo_slug which causes failure.

Update screwdriver ci initializer

---

.travis.yml
Dangerfile

Moves the doc checker from inside Danger evaluation, to on CI like normal. Might get better error messaging - which could disambiguate #1002

Move docs on the CI

---

CHANGELOG.md
lib/danger/ci_source/support/find_repo_info_from_url.rb
spec/lib/danger/ci_sources/support/find_repo_info_from_url_spec.rb

Fix for issue described in #968 - correct slug detection for repository with following url:
`https://git.myhost.com/ORGANISATION/TEAM/REPOSITORY_NAME` allowed by GitLab.
I cannot simply add new regexp group `(/[^/]+){1,2}` because then it will also match part of domain name, so I added `://[^/]+/` at the beginning to catch only url path.

Allow two slashes in URL slug

---

CHANGELOG.md
lib/danger/ci_source/bitrise.rb
spec/lib/danger/ci_sources/bitrise_spec.rb

Extension for #1002 Pull Request to support 2 slashes repo_slug also on Bitrise.io CI.

Update Bitrise CI to parse repo_slug with two slashes

---

.travis.yml
Rakefile
spec/lib/danger/ci_sources/bitrise_spec.rb
spec/lib/danger/ci_sources/circle_api_spec.rb
spec/lib/danger/ci_sources/circle_spec.rb
spec/lib/danger/ci_sources/gitlab_ci_spec.rb
spec/lib/danger/ci_sources/screwdriver_spec.rb

moves rubocop to a Rake task and autocorrects associated errors

Move rubocop to Rake task and autocorrect errors #trivial

---

danger.gemspec

I've fixed a bug on diff on `ruby-git/ruby-git` for danger.
It's occurred when diff contains multibyte chars.
Could you apply it?
It's release on v1.5.0.
- [the patch](https://github.com/ruby-git/ruby-git/pull/369)

Update `ruby-git/ruby-git` to 1.5

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_bitbucket_cloud_plugin.rb
lib/danger/danger_core/plugins/dangerfile_bitbucket_server_plugin.rb
lib/danger/danger_core/plugins/dangerfile_git_plugin.rb
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb
lib/danger/danger_core/plugins/dangerfile_vsts_plugin.rb
spec/lib/danger/danger_core/dangerfile_spec.rb

I ended up adding a dangerfile to one of our ruby apps, and obviously this was the right fit https://github.com/artsy/exchange/pull/168 - but the default rubocop settings don't want you writing `fail`. 
I originally aliased `raise` - like mentioned in https://github.com/danger/danger/issues/1006 but it didn't feel right, so I chatted with @yuki24 added `failure` as an option, and made it the default in all the docs.

Adds failure as the recommended way to express a blocking error in a Dangerfile

---

CHANGELOG.md
lib/danger/commands/runner.rb
spec/lib/danger/commands/runner_spec.rb

colored2 seems to be used as drop in replacement for colored. It works
great unless you want to disable ansi codes in output as `ansi` flag is
handled by CLAide and not by Danger. Added
`Danger::Runner#adjust_colored2_output` is called from initializer
as that is only place common for commands. Otherwise some wrapper of
Runner#run will be needed (which does not seems worth it).

fix `--no-ansi` behavior for commands

---

CHANGELOG.md
lib/danger/ci_source/local_only_git_repo.rb
lib/danger/commands/dry_run.rb
lib/danger/commands/runner.rb
lib/danger/danger_core/dangerfile.rb
lib/danger/danger_core/plugins/dangerfile_local_only_plugin.rb
lib/danger/request_sources/local_only.rb
spec/lib/danger/ci_sources/ci_source_spec.rb
spec/lib/danger/ci_sources/local_only_git_repo_spec.rb
spec/lib/danger/commands/dry_run_spec.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/request_sources/local_only.rb

motivation is ability to run danger against local only repo
in condition when there is no actual PR/MR created (or is not available
to danger).

Add dry_run command and associated ci_source and request_source

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb
spec/lib/danger/request_sources/gitlab_spec.rb

Implements the method `Danger::RequestSources::GitLab#file_url` such that importing a danger file from a GitLab repository works. Example: 
```ruby
danger.import_dangerfile(gitlab: "ruby-grape/danger")
```
This is documented at https://danger.systems/reference.html but currently doesn't work due to the missing implementation.
Fixes https://github.com/danger/danger/issues/877

Fix gitlab source for #import_dangerfile

---

CHANGELOG.md
lib/danger/ci_source/appveyor.rb
spec/lib/danger/ci_sources/appveyor_spec.rb
spec/lib/danger/ci_sources/ci_source_spec.rb

This PR adds AppVeyor support. You can now use Danger in AppVeyor(Both on Windows/Linux image).

Add AppVeyor support

---

lib/danger/danger_core/dangerfile.rb
spec/fixtures/dangerfile_with_error_and_path_reassignment
spec/lib/danger/danger_core/dangerfile_spec.rb

Move eval into seperate method to prevent local variable reassignment.
If the eval rescue is hit and path has been reassigned Danger will crash.
This doesn't address any concerns around a malicious Dangerfile rewriting methods.
#trivial

Protect against 'path' reassignment when evaling dangerfile

---

CHANGELOG.md
lib/danger/request_sources/bitbucket_server_api.rb

This PR updates the error message thrown by Danger when posting a comment to Bitbucket Server and receiving a 4XX or 5XX status code. 
---
We've been spinning up new projects left and right at Nike with Danger (thanks for the fantastic project BTW! 🍻 ). When spinning up new projects, we tend to have plugins like SwiftLint misconfigured a bit which can end up triggering large numbers of warnings in Danger. This generally results in the following error thrown by Danger:
```
Error posting comment to Bitbucket Server: 400 ()
```
As you can see, this doesn't give us much to go on. We have no idea why the 400 is being thrown. Room for improvement!
---
By appending the response body to the error message, we are able to see why Bitbucket Server is throwing the 400 status code:
```
Error posting …
```

BitbucketServerAPI Error Message

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb
spec/lib/danger/request_sources/github_spec.rb

I added the following line into my Dangerfile, and created a pull request including this change.
```rb
warn("foo", file: "Dangerfile", line: 1)
```
An inline-comment should be posted on the diff for Dangerfile#L1.
A normal comment was posted like this:
In many versions of GNU diff, each range can omit the comma and trailing value, in which case the value is 1. (See https://en.wikipedia.org/wiki/Diff for more details about this.)
Here is an example of the omission. Look at `@@ -1 +1,8 @@`.
I changed the regex pattern in Danger::RequestSources::GitHub#find_position_in_diff so that it supports the omitted format on the range for the original file too.
```rb
range_header_regexp = /@@ -([0-9]+),([0-9]+) \+(?<start>[0-9]+)(,(?<end>[0-9]+))? @@.*/
^^^^^^^^^
```
I think this case occurs when we …

Fix diff range detection logic

---

.travis.yml

This pull request updated ruby versions in travis.yml
The latest ruby version is 2.5.3.
ruby version reference: https://www.ruby-lang.org/en/downloads/releases/

Update ruby versions in travis.yml

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb
spec/lib/danger/request_sources/github_spec.rb

`find_position_in_diff` method returns wrong position when there are some addition codes after `No newline...` annotation in diff.
Because `find_position_in_diff` method doesn't consider about annotation.
Add extra position increments when the line is `No newline...` annotation.

Amend diff position caluculation

---

CHANGELOG.md
lib/danger/ci_source/local_git_repo.rb
lib/danger/ci_source/support/find_repo_info_from_url.rb
lib/danger/ci_source/support/pull_request_finder.rb
lib/danger/commands/local_helpers/local_setup.rb
lib/danger/request_sources/bitbucket_server_api.rb
spec/lib/danger/ci_sources/support/find_repo_info_from_url_spec.rb

This PR adds support for Bitbucket Server PRs in danger pr command. 
This is a highly desired feature in our team at Adidas, as some members wanted to test some changes in our Dangerfiles locally without being required to open new pull requests to test in our CI environment

Danger pr now supports Bitbucket Server Pull Requests

---

CHANGELOG.md
lib/danger/ci_source/jenkins.rb
lib/danger/version.rb
spec/lib/danger/ci_sources/jenkins_spec.rb

Fix #1049 
Add a custom ssh and https regex to jenkins ci to support multiple sub groups  (gitlab env).
Keep bitbucket regex for change url env.
Keep old regex as fallback - supports only one parent for the repository.

Extract repo_slug using ssh and http(s) regex on jenkins ci to fix #1049

---

CHANGELOG.md
lib/danger/ci_source/jenkins.rb
lib/danger/version.rb
spec/lib/danger/ci_sources/jenkins_spec.rb

Fix for PR detection logic in Jenkins lib.
I faced with the following issue:
```
18:02:14 /bundle_cache/gems/octokit-4.13.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://github.site_url/api/v3/repos/path/to/app/pulls/false: 404 - Not Found // See: https://developer.github.com/enterprise/2.14/v3/pulls/#get-a-single-pull-request (Octokit::NotFound)
```
This PR fixes the issue above ^^

Fix bug with jenkins PR detection

---

CHANGELOG.md
lib/danger/ci_source/local_git_repo.rb
lib/danger/ci_source/support/pull_request_finder.rb
lib/danger/commands/pr.rb
lib/danger/danger_core/plugins/dangerfile_bitbucket_cloud_plugin.rb
lib/danger/request_sources/bitbucket_cloud_api.rb
spec/fixtures/bitbucket_cloud_api/pr_response.json
spec/lib/danger/ci_sources/support/find_repo_info_from_url_spec.rb
spec/lib/danger/ci_sources/support/pull_request_finder_spec.rb
spec/lib/danger/commands/pr_spec.rb
spec/lib/danger/plugins/dangerfile_bitbucket_cloud_plugin_spec.rb
spec/lib/danger/request_sources/bitbucket_cloud_api_spec.rb
spec/lib/danger/request_sources/bitbucket_cloud_spec.rb

Adding changes to `danger pr` command in order to allow running on bitbucket cloud repositories.
There's a few things I was unsure, but since the tests still passed, I kept going. Also my ruby skills are not great, so feel free to criticise..
For example, file `lib/danger/danger_core/plugins/dangerfile_bitbucket_cloud_plugin.rb` seemed very buggy, mostly being a copy paste from the bitbucket_server equivalent.
The method `#find_scm_provider` is not great but I followed a similar technique to what was previously being done to detect bitbucket server urls. I suppose changing that would involve a bigger refactor on the `pr` command.
And that was it.. I was able to run this locally, so I suppose it works. Let me know if you need any other changes.

Run "danger pr" for Bitbucket Cloud

---

CHANGELOG.md
lib/danger/commands/runner.rb
lib/danger/danger_core/executor.rb
spec/lib/danger/commands/runner_spec.rb

Flag is disabled by default, but can be opted in which might be handy for Circle CI users, or any other CI system where you can't guarantee Danger will run for each PR. Fixes https://github.com/danger/danger/issues/1080

Add "Fail if no PR" flag

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb

gitlab: use CI_API_V4_URL from GitLab 11.7

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb
spec/lib/danger/request_sources/gitlab_spec.rb

Current implementation of GitLab request source does not create a new comment
when requested via the `--new-comment` CLI option, but rather updates the old
one.
This patch fixes the issue by checking whether new comment is requested
before updating Pull Request.
Preliminary discussion of this issue is here:
https://github.com/danger/danger/issues/1084

[GitLab] Create a new comment

---

CHANGELOG.md
lib/danger/danger_core/executor.rb

Had a few "what does skipping danger run mean?" comments from the team since https://github.com/danger/danger/pull/1081 got merged. The good news is this means https://github.com/danger/danger/pull/1081 is working as expected. The bad news is it's confusing people. This PR hopefully will result in less confusion.

Additional warning for CircleCI if danger doesn't get run

---

CHANGELOG.md
lib/danger/ci_source/appcenter.rb
spec/lib/danger/ci_sources/ci_source_spec.rb

Added Visual Studio App Center as a new CI source. It's a copy of #1057, but with resolved missing PR id. It's also heavily based on solution introduced in #892.
I haven't added any tests, because I have no clue how to do it in order to fake the networking and `DANGER_GITHUB_API_TOKEN` 😢
I hope this will be just a _temporary_ solution and soon we'd get a proper PR ID directly in App Center's environmental variables. I've created a [feature request in their repo](https://github.com/Microsoft/appcenter/issues/79).

Add support for App Center

---

README.md

`https` is better than `http`.

Secure code-of-conduct links in readme

---

.gitignore

Fixes mixed line endings and removes trailing whitespace.

Remove trailing whitespace from gitignore

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb
spec/fixtures/github_api/inline_comments_pr_diff.diff
spec/lib/danger/request_sources/github_spec.rb

- Fixes an issue where if a filename in the `+++` or `---` lines contains a space, an additional tab is appended to the end of the line before the newline character [reference to source](https://github.com/git/git/blob/6e0cc6776106079ed4efa0cc9abace4107657abf/diff.c#L1491)
- I believe this fixes #1010 #1042 and potentially https://github.com/ashfurrow/danger-ruby-swiftlint/issues/115

Fix inline github comments when diff has trailing tabs

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb
spec/lib/danger/request_sources/gitlab_spec.rb

This should fix #1097 
While I'm not clear on what cases it happens, the solution is similar to the one for GitHub: if we fail to submit an inline comment, the violation is kept and submitted as a regular one in the main comment.

Rescues from exceptions when submitting GitLab inline comments

---

.travis.yml
CHANGELOG.md
danger.gemspec
lib/danger/version.rb

Kramdown released [2.0.0](https://kramdown.gettalong.org/news.html#kramdown-200-released) on 2019/01/20, followed by [2.1.0](https://kramdown.gettalong.org/news.html#kramdown-210-released) on 2019/01/31.
For projects staying on the edge, it is important that Danger's dependency on Kramdown `~> 1.5` does not become a blocker.
As it is not possible to write a gemspec with conditions on the Ruby version, this is my final proposition:
This is a drastic change triggered by Kramdown 2.x requiring Ruby 2.3 and `kramdown-parser-gfm`. Danger 6.0+ will require:
- Ruby 2.3+
- kramdown gem 2.0+
- kramdown-parser-gfm gem
To keep using Ruby 2.0\~2.3 and kramdown gem 1.5\~2.0, you'll have to stick to Danger 5.x.
I'd like to suggest creating a `v5.x` branch on this repository, right before this PR gets …

Support Kramdown 2.0+ (requires Ruby 2.3)

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb

Fix for #1106 
include `#trivial` in the title or the body of the PR and this is skipped.
We also request that you fill in the body of your PR, a title should be tweet length, but
ideally you can explain the PRs …

Fixed error handling on GitLab inline comments

---

lib/danger/ci_source/gitlab_ci.rb

Otherwise content is rendered poorly:

Typo fixed in CI configuration #trivial

---

.travis.yml

This is so it doesn't clog up the main script logs.

Travis: move git commands

---

CHANGELOG.md
lib/danger/ci_source/gitlab_ci.rb
spec/fixtures/gitlab_api/commit_merge_requests.json
spec/lib/danger/ci_sources/gitlab_ci_spec.rb
spec/support/gitlab_helper.rb

Original code queries all open PRs for the project, iterating over them looking for the one that has the commit SHA.  This can take quite some time if there are a lot of MRs open.  For example https://gitlab.com/gitlab-org/gitlab-ce/merge_requests has ~800 open MRs, which causes (@ 20 per page) 40 API requests to fetch, each doing an HTTPS connection setup, plus run-time, which really adds up.
Since GitLab 10.7 there is an API which will directly find/return any MRs for a given commit; this takes one API call, and is speedy.  This PR uses this new API, if GitLab is new enough.

For GitLab >= 10.7, use a faster API to find the MR for a commit

---

CHANGELOG.md
lib/danger/helpers/comment.rb
lib/danger/request_sources/gitlab.rb
spec/lib/danger/request_sources/gitlab_spec.rb

fixed https://github.com/danger/danger/issues/1111
Fixed GitLab Discussions POST API params.
Although not in the GitLab API documentation, `old_line` and` old_path` seem to be required parameters when `new_path` and `new_line` were used.

fixed GitLab Discussions API request params

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb

Fixed missing Unified diff headers for `gitlab.mr_diff` due to a Gitlab API bug (See https://gitlab.com/gitlab-org/gitlab-ce/issues/53229).

Fixed missing Unified diff headers for `gitlab.mr_diff`

---

CHANGELOG.md
danger.gemspec

The version `2.0` of `faraday-http-cache` was released 3 years ago. Pinning Danger to the version `~> 1.0` of that gem makes it incompatible with other recent gems.

Update faraday-http-cache dependency from 1.0 to 2.0

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb
lib/danger/request_sources/gitlab.rb
spec/lib/danger/danger_core/plugins/dangerfile_danger_plugin_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb

Gitlab added restrictions for security reasons, and you can no longer download a raw file without going through their API (Cf: https://gitlab.com/gitlab-org/gitlab-ce/issues/54572#note_120858359)
Therefore, using `danger.import_dangerfile(gitlab: "repo", path: 'Dangerfile')` would fail.
To fix this, in this PR, I updated the `file_url` for Gitlab request source, and updated the tests

Update way to import Dangerfile from Gitlab

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_danger_plugin_spec.rb

This PR fixes a regression introduced in #1128, reported in #1130.
It also reverts from using
```
danger.import_dangerfile(gitlab_project_id: 42)
```
back to 
```
danger.import_dangerfile(gitlab: 42)
danger.import_dangerfile(gitlab: "org/repo")
```
So now old Dangerfiles using `danger.import_dangerfile(gitlab: "")` will work again.

Lets import dangerfiles on gitlab via its name again (instead of forcing a project_id)

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_bitbucket_cloud_plugin.rb
spec/lib/danger/plugins/dangerfile_bitbucket_cloud_plugin_spec.rb

`branch_for_head` and `branch_for_base` return a same value on Bitbucket cloud.
It is simple.
get the value from the same key in Json.

Fix branch_for_head api of Bitbucket cloud

---

CHANGELOG.md
lib/danger/danger_core/environment_manager.rb
lib/danger/danger_core/executor.rb
spec/lib/danger/danger_core/environment_manager_spec.rb

This PR addresses issue #1141 by exposing the value of danger_id via `EnvironmentManager`.
To access the value from inside a Dangerfile you can use `danger.env.danger_id`.
Unit tests have also been added to ensure the value passed is being set, and when none is provided that the default danger is used.

Exposes danger_id via EnvironmentManager

---

CHANGELOG.md
lib/danger/ci_source/vsts.rb
lib/danger/commands/dangerfile/init.rb
lib/danger/danger_core/executor.rb
lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb
lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb
lib/danger/helpers/comments_helper.rb
lib/danger/plugin_support/plugin_parser.rb
lib/danger/request_sources/github/github.rb
lib/danger/request_sources/gitlab.rb
spec/fixtures/github_api/inline_comments_pr_diff.diff
spec/lib/danger/ci_sources/circle_api_spec.rb
spec/lib/danger/danger_core/dangerfile_spec.rb
spec/lib/danger/request_sources/bitbucket_server_api_spec.rb

Fix typos across **danger repository**
```
danger/lib/danger/ci_source/vsts.rb:7:43: "definiton" is a misspelling of "definition"
danger/lib/danger/commands/dangerfile/init.rb:3:31: "strucutre" is a misspelling of "structure"
danger/lib/danger/danger_core/executor.rb:24:52: "enviroment" is a misspelling of "environment"
danger/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:5:25: "muliple" is a misspelling of "multiple"
danger/lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb:37:46: "happend" is a misspelling of "happened"
danger/lib/danger/helpers/comments_helper.rb:37:25: "comparision" is a misspelling of "comparison"
danger/lib/danger/plugin_support/plugin_parser.rb:59:53: "availablity" is a misspelling of "availability" …
```

Fix typos across danger repository

---

CHANGELOG.md
lib/danger/core_ext/file_list.rb
spec/lib/danger/core_ext/file_list_spec.rb

We were getting this crash when using danger with danger-jacoco on an Android project.
doing the check for `current.nil?` fixes it, couldn't find if there's a specific input in our project that was triggering the crash but adding this check fixes it.
```
Traceback (most recent call last):
28: from /Users/[redacted]/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
27: from /Users/[redacted]/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
26: from /Users/[redacted]/.rvm/gems/ruby-2.6.3/bin/danger:23:in `<main>'
25: from /Users/[redacted]/.rvm/gems/ruby-2.6.3/bin/danger:23:in `load'
24: from /Users/[redacted]/.rvm/gems/ruby-2.6.3/gems/danger-6.0.9/bin/danger:5:in `<top (required)>'
23: from /Users/[redacted]/.rvm/gems/ruby-2.6.3/gems/claide-1.0.2/lib/claide/command.rb …
```

Fix Danger crash in Filelist include.

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb

This commit adds another example to [https://danger.systems/reference.html](https://danger.systems/reference.html).
Currently there is no example for the gitlab.api method. 
This is solved with this example.

Adds complex gitlab.api example

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb

for creating links.
We use Teamcity in combination with a self hosted gitlab. While using the`danger-xcode_summary` gem we discovered that the `html_links` method of `dangerfile_gitlab_plugin.rb` would throw, due to `env.ci_source.project_url` not being defined for `Danger::TeamCity`
In this merge request I altered the method to use the Gitlab API to retrieve the correct `web_url` instead of relying on the underlying CI that triggered the build.
I tried to write tests, please let me know if they are appropriate, I had some trouble mocking the Gitlab API.
<details>
<summary>original errors stack trace</summary>
<pre>
Exit status of command 'bundle exec danger --dangerfile=Dangerfile --fail-on-errors=true' was 1 instead of 0.
/Users/teamcity/.rvm/gems/ruby-2.6.2/gems/danger-6.0.9/lib/danger/ …

Change dangerfile_gitlab_plugin to rely on gitlab instead of the ci

---

Dockerfile

This attempts to fix the issue:
https://github.com/danger/danger/issues/1148
Of the code:
```
ADD ./Gemfile $APP_HOME/Gemfile
ADD Gemfile.lock $APP_HOME/Gemfile.lock
```
The first line goes smooth, but the second fails, which seems to confirm this comment: https://github.com/danger/danger/issues/1148#issuecomment-518532561 
This adds a relative path to the ADD command in the dockerfile

Use COPY instead of ADD, ENTRYPOINT instead of RUN, and use relative path in Github actions docker

---

spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb

```
Failures:
1) Danger::DangerfileGitLabPlugin repository_web_url should request the project
Failure/Error: project = Gitlab::ObjectifiedHash.new({:web_url => "https://gitlab.com/k0nserv/danger-test"})
NameError:
uninitialized constant Gitlab
```
not executed `require "gitlab"`
`require "gitlab"` is only here ↓
https://github.com/danger/danger/blob/597529b42e99eea06730a87137e6f3e3f009508a/lib/danger/request_sources/gitlab.rb#L31
and actually executed `require 'gitlab'` when calling `Danger::RequestSources::GitLab#client` for the first time.
If you look at the spec, you can see that it may not be executed `require "gitlab"` depending on the execution order.
https://github.com/danger/danger/blob/597529b42e99eea06730a87137e6f3e3f009508a/spec/lib/danger/danger_core/plugins/dangerfile_gitlab_p …

Fix Danger::DangerfileGitLabPlugin spec

---

CHANGELOG.md
lib/danger/ci_source/code_build.rb
spec/lib/danger/ci_sources/code_build_spec.rb

- Add spec test
- Change to allow source repo url which not ended with '.git'
- it is valiable on code build
- Change to be able to handle host which likes github enterprise

Add github enterprise support to CodeBuild

---

CHANGELOG.md
lib/danger/ci_source/azure_pipelines.rb

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables
System.PullRequest.PullRequestNumber must be used for GitHub as System.PullRequest.PullRequestId contains a different identifier
Variables are uppercased and . are replaced with _ on Unix environments

Fix wrong GitHub Pull Request identifier being used for Azure Pipelines

---

CHANGELOG.md
danger.gemspec

Ruby-Git released a new version 1.6.0 after more than year and half. There is important change in output encoding that should be included in Danger sooner than later.
Update to Ruby-Git 1.6.0 (https://github.com/ruby-git/ruby-git/releases) that fixes output encoding https://github.com/ruby-git/ruby-git/pull/405
After merging this, it would be nice to release patch version 6.2.1 and also update releases page (currently missing not only 6.2.0) - https://github.com/danger/danger/releases. :)

Update to Ruby-Git 1.6.0

---

CHANGELOG.md
lib/danger/request_sources/bitbucket_cloud.rb
lib/danger/request_sources/bitbucket_cloud_api.rb
spec/lib/danger/request_sources/bitbucket_cloud_api_spec.rb

I had renamed BitbucketCloudAPI#fetch_last_comments, but neglected to refactor its use in BitbucketCloud. And I also broke the while loop I wrote, despite having had it working at some point. A touch embarrassing - sorry for the extra work! I should've waited until today to have a quick re-test and then submit my PR, rather than pushing ahead at 9PM

Fix runtime errors in BitbucketCloud#delete_old_comment

---

CHANGELOG.md
lib/danger/ci_source/bitrise.rb

Previous regex pattern does not work if the URL consists of more than 2 subgroups. 
For example : git@git.com:xxxxx/xxxxx/project works fine.
However, if it is more than 2 subgroups then the url becomes
git@git.com:xxxxx/xxxxx/xxxxx/project in this case it fails. 
For the URL match there are 2 cases:
1. ':' after '.com' 
2. '/' after '.com'
I have added 2 if conditions that will use the appropriate RegEx pattern for each of the cases.

Updated RegEx

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb

Fixes https://github.com/danger/danger/issues/1191:
The previous logic did hide actual load error based on bad assumptions:
New error shows what (other) modules could have failed to load:
```
/app # danger
Error: cannot load such file -- bigdecimal
/app #
```

Show correct error when GitLab Gem can't be loaded

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb
spec/lib/danger/request_sources/gitlab_spec.rb

Fixes https://github.com/danger/danger/issues/1193.
include `#trivial` in the title or the body of the PR and this is skipped.
We also request that you fill in the body of your PR, a title should be tweet length, but …

Fix Danger::RequestSources::GitLab#setup_danger_branches

---

CHANGELOG.md
lib/danger/ci_source/bitrise.rb
spec/lib/danger/ci_sources/bitrise_spec.rb

If the Git Repo URL contains ".git", we get the following error
Gitlab::Error::NotFound: Server responded with code 404, message: 404 Project Not Found.
As the URL should not contain ".git" at the end.

Remove ".git" at the end of the project URL

---

CHANGELOG.md
lib/danger/ci_source/bitrise.rb

**Fix typo from environemnt -> environment**
```
danger/lib/danger/ci_source/bitrise.rb:24:25: "environemnt" is a misspelling of "environment"
```

Fix typo from environemnt -> environment

---

CHANGELOG.md
lib/danger/request_sources/bitbucket_cloud.rb
lib/danger/request_sources/bitbucket_cloud_api.rb
spec/lib/danger/danger_core/environment_manager_spec.rb
spec/lib/danger/request_sources/bitbucket_cloud_api_spec.rb
spec/lib/danger/request_sources/bitbucket_cloud_spec.rb
spec/support/bitbucket_cloud_helper.rb

Bitbucket changed its API, and now accessing `/users/<username>` returns a
404 ([here's some detail](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/#removal-of-usernames-from-user-referencing-apis) on the privacy aspect of that.
Though I think to be honest what we were doing at least where I work was a bit of a security hole in Bitbucket - we'd set up an access token with only pull_requests scope, but it used to be be able to access `/users/<username>` for its own user anyway. I think that's why this has changed before the 29th, as the above link says it's going to.
Anyway, we were only using that endpoint to find the UUID for identifying whether the user that wrote a comment was danger (to decide whether to attempt to delete it), so now we just require the …

Fix #1213 - username-related 404 on Bitbucket Cloud

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_git_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_git_plugin_spec.rb

Problem: As a developer I needed a way to check the link length of added and deleted files.
Solution: Update [`info_for_file`](https://github.com/danger/danger/blob/master/lib/danger/danger_core/plugins/dangerfile_git_plugin.rb#L138) to check against `added_files` and `deleted_files`. If the file was added, insertions would be the file size and deletions would be 0. If the file was deleted, insertions would be 0 and deletions would be the file size.
This pull request addresses issue https://github.com/danger/danger/issues/1215. Strictly having been a mobile developer my professional life and having rarely touched Ruby, I had no idea if I could address this on my own. But when my issue was labeled "You Can Do This", I thought "you know what, I can"! So thanks for the motivation! I hope …

Added support to git.info_for_file for added and deleted files.

---

CHANGELOG.md
lib/danger/danger_core/executor.rb
spec/lib/danger/danger_core/environment_manager_spec.rb
spec/lib/danger/danger_core/executor_spec.rb
spec/support/ci_helper.rb

* GitLab uses the terminology Merge Request as opposed to the commonly
known Pull Request utilized by GitHub
* This adds a method to check for GitLabCI and returns the desired
language
* Keeps Pull Request the default for the time being
* Modifies all method names that represent gitlab and ensures we utilize
the appropriate nomenclature

Improves messaging specific to GitLab

---

CHANGELOG.md
danger.gemspec

- Git has released new version 1.7 with Ruby 2.7 support and warning fixes - https://github.com/ruby-git/ruby-git/releases
I know semantically this is not required but at least there will be some change for new (minor?) release for us - Ruby 2.7 users.
Could we release new version @orta please? :)

[Ruby 2.7] Bump git subspec to new 1.7 release

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb

- fixes https://github.com/danger/danger/issues/1220
- more info: https://piechowski.io/post/last-arg-keyword-deprecated-ruby-2-7/

[Ruby 2.7] Fix warnings for Github

---

.circleci/config.yml
.rubocop.yml
.travis.yml
CHANGELOG.md
Gemfile
appveyor.yml
danger.gemspec
lib/danger/helpers/comments_helper.rb

- Fixes: https://github.com/danger/danger/issues/1189
- How: Re apply change from https://github.com/danger/danger/pull/1208 as Danger 7.0.0 doesn't have it anymore somehow
- Drops Ruby 2.3 - Circle CI dropped this version support last week and tests are not working anymore - it's dangerous to guarantee support for version that we don't have tests for, so I believe we should drop it. It's in EOL state for years anyways.
If you check the file history, the PR is not even there and the commit never made it to Danger 7.0 even tho other parts of the PR are correctly on master. This should fix the issue again for Danger 7+.
@orta I have no idea how this happened, Git history doesn't show anything. No idea how Danger 7 was released either... but the only way how to fix this is downgrade to …

Fix strike-out comments on Github for Danger 7+, drop Ruby 2.3

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb

We don't call super because in some cases the Git remote doesn't match the GitLab instance host.
In Danger::EnvironmentManager#initialize we still check that the request source is #validates_as_api_source?
so that should be sufficient to validate GitLab as request source.
See https://github.com/danger/danger/issues/1231 and https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/10069.
Fixes https://github.com/danger/danger/issues/1231.

Don't call `super` in `Danger::RequestSources::GitLab#validates_as_ci?`

---

CHANGELOG.md
lib/danger/helpers/comments_helper.rb
spec/lib/danger/helpers/comments_helper_spec.rb

This fixes https://github.com/danger/danger/issues/1235.

Fix Danger::Helpers::CommentsHelper#process_markdown so that it doesn't result in broken HTML

---

lib/danger/scm_source/git_repo.rb

If shallow clone/fetch is lower than the number of commits in a PR,
it will not be able to find the base.
For example, if the depth of clone/fetch is set to 10, and the PR has
11 commits, it will not be able to find the base. The error should
provide that hint as that could be the reason.
Related issues #913 #768

Descriptive error message on shallow clone/fetch #trivial

---

lib/danger/ci_source/gitlab_ci.rb
spec/lib/danger/ci_sources/gitlab_ci_spec.rb

`GitlabCI#project_url` is not being used anymore ever since #1157 was merged.

Remove GitlabCI#project_url #trivial

---

CHANGELOG.md
lib/danger/ci_source/gitlab_ci.rb
lib/danger/request_sources/github/github.rb
spec/lib/danger/ci_sources/gitlab_ci_spec.rb
spec/lib/danger/request_sources/request_source_spec.rb

Resolves #1044
It is common for code repos to be hosted on Github while using
Gitlab only as a CI/CD service.
Info on using Gitlab only as CI/CD service for external repos:
https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/
Current limitations:
- Unfortunately, Gitlab currently does not expose the external repo's
url, so users will have to manually set the repo's URL as an ENV var
`DANGER_PROJECT_REPO_URL` 
(for ex., `DANGER_PROJECT_REPO_URL=https://github.com/procore/blueprinter`).
- Additionally, `RequestSources::Github#validates_as_ci?` is tricky now because
the `git remote -v` returns `origin` as `gitlab.com` rather than `github.com`. The
reasoning is that even though the actual repo is on Github.com, GitlabCI maintains a
mirror on Gitlab.com and the CI checkout the code from the …

GitLab CI external repo

---

CHANGELOG.md

External Gitlab CI was actually released in 8.0.3, the actual version bump happened here: https://github.com/danger/danger/commit/db9b9ba2e1c69d70e141c3cada822d0050e81ea1

Fix changelog version numbers #trivial

---

danger.gemspec

See [CVE-2020-14001](https://github.com/advisories/GHSA-mqm2-cgpr-p4m6). This came up as a GitHub _dependabot_ alert in our repo so I guess others have this issue as well.

Bump kramdown to ~> 2.3

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb

- fixes #1250 
- implemented like https://github.com/danger/danger/pull/1222

[Ruby 2.7] Fix warnings for GitLab #1250

---

CHANGELOG.md
lib/danger/ci_source/bitrise.rb
spec/lib/danger/ci_sources/bitrise_spec.rb

This PR is fixing a bug that caused the corresponding Bitrise step to fail if a repository URL was provided with an SSH scheme and port.

Handle repository URLs with shh and port in Bitrise

---

CHANGELOG.md
lib/danger/core_ext/file_list.rb
spec/lib/danger/core_ext/file_list_spec.rb

I'd like to be able to trigger a rule when files requiring different patterns match. Currently, this can be achieved by calling `FileList#include?` multiple times.
i.e. 
```ruby
if git.modified_files.include?("pattern1") || git.modified_files.include?("pattern2")
warn("some shared warning")
end
```
`FileList#include?` is based on [`File.fnmatch`](https://rubyapi.org/2.7/o/file#method-c-fnmatch). `File.fnmatch` supports an optional syntax `{a,b}`which can match multiple patterns.
From the `File.fnmatch` documentation:
> `{a,b}`  |      Matches pattern a and pattern b if `File::FNM_EXTGLOB` flag is enabled. Behaves like a Regexp union `((?:a|b))`.
I'm initially proposing to enable this flag by default, allowing usage such as
```ruby
if git.modified_files.include?("{pattern1,pattern2}") …
```

Support matching multiple patterns `{a,b}` in FileList#include?

---

CHANGELOG.md
lib/danger/helpers/comments_helper.rb
spec/lib/danger/helpers/comments_helper_spec.rb

The default behaviour of Kramdown replaces single quote `'`/`apos` with `lsquo` and `rsquo`, and double quote `"`/`quot` with `ldquo` and `rdquo`.
This creates unexpected result when a message contains quotes in '' or "".
Fixes #1263 
This was discovered in https://gitlab.com/gitlab-org/gitlab/-/merge_requests/44004#note_422102483

Preserve single and double quotes

---

CHANGELOG.md
lib/danger/request_sources/bitbucket_server.rb
lib/danger/request_sources/code_insights_api.rb
spec/lib/danger/request_sources/code_insights_api_spec.rb
spec/support/bitbucket_server_helper.rb

This PR adds possibility to pipeline inline comments generated by Danger and plugins to use directly in Atlassian's [Code Insights](https://support.atlassian.com/bitbucket-cloud/docs/code-insights/) report generating tools.
If inline comments are present and Code Insights are properly configured, they will be added on a per-file, per-line basis as [Annotations](Annotations). As in example below (_"WCAG 2.0: Use a more descriptive alternative text"_ is an example of a Low priority Annotation).
Otherwise, default behaviour will be used (all inline comments inserted into single Danger pull request comment). 
As of this PR, Code Insights is only integrated with Bitbucket Server as this is the request source I had access to test against, however, it should be possible to adapt this code to …

Code Insights support for Bitbucket Server

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb

This corrects the fix made for Ruby 2.7 warning in this PR https://github.com/danger/danger/pull/1222.

fix ruby 2.7 warning with correct double splat usage

---

lib/danger/request_sources/gitlab.rb

Identical to #1264 but for `gitlab.rb`
Cf. https://github.com/danger/danger/issues/1250#issuecomment-686392009

fix ruby 2.7 warning with correct double splat usage for gitlab.rb

---

CHANGELOG.md
lib/danger/ci_source/github_actions.rb
spec/lib/danger/ci_sources/github_actions_spec.rb

Using GitHub actions if the event name is `pull_request_target` instead of `pull_request`, then Danger will not detect it as a valid PR and the error ```Not a GitHubActions Pull Request - skipping `danger` run.``` will be displayed when trying to run it.
Updated the check in the `github_actions` file to also check for this event name as well.
Based on https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/ this should be almost identical so hopefully the change will work as intended, I could not see anything related on how to test a GitHub action though.

Fix GitHub actions issue with pull_request_target

---

CHANGELOG.md
lib/danger/ci_source/concourse.rb
spec/lib/danger/ci_sources/ci_source_spec.rb
spec/lib/danger/ci_sources/concourse_spec.rb

This PR adds support for Concourse-CI to danger as a supported CI system
This PR uses the same ENV's as found in danger-js in this PR https://github.com/danger/danger-js/pull/658, This has been done to keep things consistent between the two for Concourse.

Add support for Concourse-CI

---

CHANGELOG.md
lib/danger/commands/dry_run.rb
lib/danger/commands/local.rb
lib/danger/commands/local_helpers/pry_setup.rb
lib/danger/commands/pr.rb
lib/danger/commands/staging.rb
spec/lib/danger/commands/local_helpers/pry_setup_spec.rb

Running `danger local --pry` was printing out
```
[!] Pry was not found, and is required for 'danger pr --pry'.
```
instead of
```
[!] Pry was not found, and is required for 'danger local --pry'.
```
which was confusing.

Fix incorrect command in error message

---

lib/danger/commands/init.rb

Replaces the missing Ruby Dangerfile link with the new JavaScript one.

Fix broken link in danger init command output #trivial

---

CHANGELOG.md
lib/danger/request_sources/gitlab.rb
spec/lib/danger/request_sources/gitlab_spec.rb

- since notes were calling merge, they are an ObjectifiedHash
and need to call to_h first as seen in the following warning:
WARNING: Please convert ObjectifiedHash object to hash before calling Hash methods on it.
which comes from https://github.com/NARKOZ/gitlab/blob/3dd41722670570069693cc9b84c73f475d95e6be/lib/gitlab/objectified_hash.rb#L40
Resolves https://github.com/danger/danger/issues/1245

Update to silence the objectified hash warnings

---

CHANGELOG.md
lib/danger/request_sources/bitbucket_cloud_api.rb

Since Ruby 3.0, `URI.escape` is obsolete. See: https://github.com/ruby/uri/pull/9
So i treated `prs_api_endpoint` method as that encodes parameters and returns a url so that Ruby 2.7 and below will behave the same behavior.
This is how i tested.
```shell
rbenv local 3.0.0
bundle exec rspec
```
- - - 
You will see that some tests about Danger::Violation class will not pass in Ruby 3.0, but the issue was already created. https://github.com/danger/danger/issues/1282

Replace URI.escape

---

CHANGELOG.md
lib/danger/danger_core/dangerfile.rb
lib/danger/plugin_support/plugin.rb
spec/lib/danger/plugin_support/plugin_spec.rb

Ruby 3.0 has separated positional arguments and keyword arguments which are already deprecated in Ruby 2.7. 
At least, I've confirmed that at least the current combination of master branch and Ruby 3 does not pass some tests due to this effect.
So specified keyword arguments explicitly to methods that pass arbitrary and keyword arguments to work as before.
Fix: https://github.com/danger/danger/issues/1282
- - -
I know danger supports ruby 2.4 and above, so I wrote it to work with them, but please let me know if it is incomplete.
See more about keyword arguments behavior: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

Delegate keyword arguments for Ruby 3.0

---

CHANGELOG.md
danger.gemspec

As of Jekyll 4.2.0, Jekyll requires terminal-table 2.0 (my motivation here is to be able to upgrade my Jekyll version). Looking at their release notes, the breaking change for terminal-table 2 is requiring ruby 2.4+, and it appears danger dropped 2.3 support in #1225.
Side note: I had unfortunately not pinned danger properly when I upgraded to Jekyll 4.2.0, so bundler rolled my danger all the way back to 0.3.0, which is presumably the most recent version of danger that didn't use terminal-table. Anyway, that's a lesson in pinning versions properly for me.

Allow terminal-table versions through 3.x

---

CHANGELOG.md
lib/danger/ci_source/support/commits.rb

We have a class name clash in GitLab where we also have a non-namespaced `Commits` class.
Namespacing the `Commits` class here seems like the right change, given that gems should always namespace their classes and that other classes in the same folder are already namespaced.

Namespace the Commits class

---

CHANGELOG.md
spec/lib/danger/danger_core/message_group_spec.rb

Fixed a test case that was not following https://github.com/danger/danger/pull/1286, which keyword arguments are treated explicitly on Ruby 3.
Sorry for the oversight!
```ruby
Failures:
1) Danger::MessageGroup#markdowns with 2 markdowns with other messages still only has both markdowns
Failure/Error:
def initialize(message, sticky, file = nil, line = nil, type: :warning)
raise ArgumentError unless VALID_TYPES.include?(type)
super(type: type, message: message, file: file, line: line)
self.sticky = sticky
end
ArgumentError:
wrong number of arguments (given 1, expected 2..4)
Finished in 38.97 seconds (files took 2.02 seconds to load)
1158 examples, 1 failure, 2 pending
Failed examples:
rspec ./spec/lib/danger/danger_core/message_group_spec.rb:240 # Danger::MessageGroup#markdowns with 2 …
```

Fix a test case for Ruby 3

---

CHANGELOG.md
lib/danger/ci_source/gitlab_ci.rb

Update gitlab_ci.rb to add support for changes in the merge_request API since Gitlab 13.8.0 release
i.e. with this release, Gitlab now returns an MR for merged or squashed commits which in case of squashed commits causes danger to error out saying, cannot find this commit, because the commit hash changes for commits when merged.
By filtering out open MRs we can ensure danger comments only on open MRs, and doesn't try to comment on merged or closed MRs where if the MR is squashed, it will not be able to find the commit hash and comment on the MR
[Related MR on gitlab](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49968/)

Comment on only open gitlab MRs for Gitlab >= 13.8.0

---

CHANGELOG.md
lib/danger/ci_source/jenkins.rb
spec/lib/danger/ci_sources/jenkins_spec.rb

GitLab now uses a `/-/` scope in its URLs as documented [here](https://gitlab.com/gitlab-org/gitlab/-/issues/214217).
The regex in the Jenkins CI class was incorrectly parsing the project URL as `https://<gitlab_host>/<project>/-/` when the URL contained the `/-/` scope, which was resulting in a 404 when trying to access the GitLab project API.
Sorry if I've missed anything, this is my first time contributing 🙂.

Handle GitLab URL containing /-/ scope on Jenkins

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
spec/lib/danger/danger_core/dangerfile_spec.rb

This checks the mergeable state of the PR JSON to determine whether a PR is a draft. This doesn't add a real proper test for the method because it didn't seem like the other methods (pr_author, pr_labels, etc.) had dedicated tests, so I figured this didn't need one.
I can add a specific test with a fixture if we want that, although I may need a bit of guidance on how to get the fixture to use. :)
Resolves #1150.

Add pr_draft? method to GitHub DSL

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin_spec.rb

I wrongly assumed it was exposed already here: https://gitlab.com/gitlab-org/gitlab-dangerfiles/-/blob/8802a22a5e18cc13abe5e2ee39377a1eb0f1597f/lib/danger/plugins/helper.rb#L419 but it's not.

Expose DangerfileGitLabPlugin#mr_changes

---

.github/workflows/CI.yml
CHANGELOG.md

Since Danger also supports Ruby 3, add Ruby 3 to CI workflow to make it easier to notice problems. 
In the Ruby setup, actions/setup-ruby was deprecated and replaced with ruby/setup-ruby: https://github.com/actions/setup-ruby#setup-ruby.

Test with Ruby 3.0

---

CHANGELOG.md
lib/danger/ci_source/xcode_cloud.rb
spec/lib/danger/ci_sources/ci_source_spec.rb
spec/lib/danger/ci_sources/xcode_cloud_spec.rb

This PR adds basic Xcode Cloud CI source support to `danger`
For reference, the documentation for all available environment variables defined by a build running on Xcode Cloud can be found [here](https://developer.apple.com/documentation/xcode/environment-variable-reference)

Adds support for Xcode Cloud as CI environment

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
lib/danger/request_sources/gitlab.rb

I didn't test this, because I don't know how, and hoped that it works, being a small change.
I did successfully test part of it using:
```ruby
project_id = gitlab.mr_json['project_id']
mr_iid = gitlab.mr_json['iid']
closing_issues = gitlab.api.merge_request_closes_issues(project_id, mr_iid)
failure('This merge request does not refer to an existing issue') if closing_issues.empty?
```
in my `Dangerfile` though.

Expose `DangerfileGitLabPlugin#mr_closes_issues`

---

CHANGELOG.md
lib/danger/ci_source/azure_pipelines.rb

Fixes issue https://github.com/danger/danger/issues/1173 
As reported in the issue above, running `danger` on AppCenter builds was broken since release 6.1.0. I had some time now to investigate and found out the problem was introduced by these changes: https://github.com/danger/danger/pull/1145
The root cause here is that `AzurePipelines` implementation is checking an env var with key `AGENT_ID` to be detected as a CI source.
Turns out that, AppCenter, a product also from Microsoft, have this same env var defined, so it was returning a false positive here when `danger` is running on AppCenter CI. You can see the full list of AppCenter's env vars in the linked issue. 
I don't have access to `AzurePipelines` to really know a proper unique env var key to replace `AGENT_ID`, so for now my …

Fix AzurePipelines giving false positive to AppCenter builds

---

CHANGELOG.md
lib/danger/helpers/comments_helper.rb

Hello! This pr adds support for a custom success message via the env var `DANGER_SUCCESS_MESSAGE`
I think it is better to handle it via an env var that adding a flag only for this

Custom success message support

---

lib/danger/ci_source/support/pull_request_finder.rb
lib/danger/request_sources/github/github.rb
spec/lib/danger/ci_sources/local_git_repo_spec.rb
spec/lib/danger/ci_sources/support/pull_request_finder_spec.rb
spec/lib/danger/request_sources/github_spec.rb

I'd like to use danger with the GitHub App.
https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps
However, currently, danger only supports Personal Access Token. 
This PR makes an internal GitHub client to enable using `bearer_token` to authenticate.
Introduce a new environment variable `DANGER_GITHUB_BEARER_TOKEN`.
when it is set, danger makes GitHub clients use this value.
Of course, you can still use an access token via `DANGER_GITHUB_API_TOKEN`.
Thanks to this patch, we can use danger with GitHub App.
- I concern about the naming of the environment variable.
- how to update documentation?

Support bearer_token for GitHub integrations

---

README.md

While going through the docs saw that the pry link was broken in the docs, this is a pr to fix that ⚡

docs: fix broken pry link #trivial

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb

This PR resolves #1338
My best guess is that there was a change in GitHub's API functionality and the mergeable state now doesn't return "draft" when the PR is a PR. In fact, now there's this dedicated API, so we should just be using it anyway 😊 
Dangerfile:
```ruby
if defined?(github) and github.pr_draft?
message("Test: skipping early")
return
else
if defined?(github)
is_github_defined = true
else
is_github_defined = false
end
if is_github_defined
is_draft_pr = github.pr_draft?
if github.pr_json['draft']
message("github.pr_json['draft'] = true")
end
end
message("Test: not skipping. is_github_defined  = #{is_github_defined}, is_draft_pr = #{is_draft_pr}")
message("#{github.pr_json['draft']}")
message("#{github.pr_json.inspect}")
```

Fix `pr_draft?` GitHub Method

---

CHANGELOG.md
lib/danger/helpers/array_subclass.rb
spec/lib/danger/helpers/array_subclass_spec.rb

`ArraySubclass#respond_to_missing?` has only one argument but `Object#respond_to_missing?` is defined to receive two arguments, according to the official API reference through 2.6.0 to 3.0.0.
So potentially it causes a bug even though I couldn't find it in a practical use case.
https://github.com/danger/danger/blob/43000055d824ca05a8c7ab63366d10e3d5c21529/lib/danger/helpers/array_subclass.rb#L22
https://docs.ruby-lang.org/en/2.6.0/Object.html#method-i-respond_to_missing-3F
> respond_to_missing?(symbol, include_all) → true or falseclick to toggle source
> respond_to_missing?(string, include_all) → true or false
- Added a spec to reproduce a bug
- Fixed `ArraySubclass#respond_to_missing?` to receive two arguments

Fix wrong arguments in ArraySubclass#respond_to_missing?

---

CHANGELOG.md
lib/danger/danger_core/dangerfile.rb
spec/lib/danger/danger_core/dangerfile_spec.rb

This addresses https://github.com/danger/danger/issues/1352.

Don't post Dangefile errors as comment on PR when the `DANGER_DO_NOT_POST_INVALID_DANGERFILE_ERROR` env var is set

---

.github/workflows/CI.yml

- Enclose 3.0 in quotes
because ruby/setup-ruby uses Ruby 3.1 unless 3.0 is enclosed in quotes.
- Add Ruby 3.1 to the CI matrix
- bundler-cache enabled, so `bundle install` is no longer needed
- Split the steps to make the build status easier to see
I wonder why `bundle exec danger --verbose` is not executed(just printed), but this PR left it as it is.

Improve GitHub Actions workflows

---

CHANGELOG.md
lib/danger/ci_source/codefresh.rb
lib/danger/ci_source/local_git_repo.rb
lib/danger/ci_source/local_only_git_repo.rb
lib/danger/ci_source/support/pull_request_finder.rb
lib/danger/request_sources/bitbucket_cloud.rb
lib/danger/request_sources/bitbucket_cloud_api.rb
lib/danger/request_sources/bitbucket_server.rb
lib/danger/request_sources/bitbucket_server_api.rb
lib/danger/request_sources/code_insights_api.rb
lib/danger/request_sources/github/github.rb
lib/danger/request_sources/gitlab.rb
lib/danger/request_sources/local_only.rb
lib/danger/request_sources/request_source.rb
lib/danger/request_sources/vsts.rb
lib/danger/request_sources/vsts_api.rb
spec/lib/danger/request_sources/bitbucket_cloud_api_spec.rb
spec/lib/danger/request_sources/github_spec.rb
spec/lib/danger/request_sources/gitlab_spec.rb

This is similar to https://github.com/danger/danger/pull/1353. I found out that there were other places where environment variables were saved as instance variables, leading to potential leakage in the case of the raising of a `DslError`.
This also redact a few more instance variables through the `#inspect` method.

Never save environment as instance variables

---

CHANGELOG.md
lib/danger/danger_core/plugins/dangerfile_git_plugin.rb
spec/lib/danger/danger_core/plugins/dangerfile_git_plugin_spec.rb

Similar to https://github.com/danger/danger/pull/788, we want to be able to get a diff for a file when it is deleted.

Fix `diff_for_file` on deleted files

---

lib/danger/scm_source/git_repo.rb
spec/lib/danger/scm_source/git_repo_spec.rb

Fixes #1359
My idea is `Danger::GitRepo#exec` (`Danger::LocalGitRepo#run_git`, `Danger::LocalOnlyGitRepo#run_git`) executes `Open3.popen2` with expanding Array parameter.

Fix Remote Code Execution vulnerability

---

CHANGELOG.md
lib/danger/commands/pr.rb
lib/danger/danger_core/dangerfile.rb
spec/lib/danger/commands/pr_spec.rb

Resolves #1364 
Action:
Run `danger pr` locally w/ a DANGER_GITHUB_API_TOKEN and a remote PR url. 
Desired:
Danger runs locally against your PR, and does not post to the PR. 
Actual Behavior:
Danger posts to the PR as your token user.

Don't report to provider on danger pr

---

CHANGELOG.md
lib/danger/request_sources/vsts.rb

On recent Ruby versions, it does not seem to be possible to directly use `gsub!` as Danger did it before in the VSTS / Azure DevOps component:
```
bundle exec danger --dangerfile=../buildtools/Dangerfile
[08:46:08]: ▸ bundler: failed to load command: danger (/Users/ci/.gem/ruby/2.6.0/bin/danger)
[08:46:08]: ▸ /Users/ci/.gem/ruby/2.6.0/gems/danger-8.6.1/lib/danger/request_sources/vsts.rb:198:in `gsub!': can't modify frozen String (FrozenError)
[08:46:08]: ▸ from /Users/ci/.gem/ruby/2.6.0/gems/danger-8.6.1/lib/danger/request_sources/vsts.rb:198:in `block in submit_inline_comments_for_kind!'
[08:46:08]: ▸ from /Users/ci/.gem/ruby/2.6.0/gems/danger-8.6.1/lib/danger/request_sources/vsts.rb:190:in `reject'
[08:46:08]: ▸ from /Users/ci/.gem/ruby/2.6.0/gems/danger-8.6.1/lib/danger/request_sources/ …
```

Fix `can't modify frozen String (FrozenError)` exception for VSTS / Azure DevOps

---

CHANGELOG.md
lib/danger/ci_source/code_build.rb
spec/lib/danger/ci_sources/code_build_spec.rb

`CODEBUILD_SOURCE_VERSION` environment variable returns commit hash(example: `6548dbc49fe57e1fe7507a7a4b815639a62e9f90`) in a batch build when triggered by a pull request.
`CODEBUILD_WEBHOOK_TRIGGER` environment variable rerurns `{event_name}/{event_variable}`(example `pr/123`) in both normal build and batch build.
> CODEBUILD_WEBHOOK_TRIGGER
Shows the webhook event that triggered the build. This variable is available only for builds triggered by a webhook. The value is parsed from the payload sent to CodeBuild by GitHub, GitHub Enterprise Server, or Bitbucket. The value's format depends on what type of event triggered the build.
For builds triggered by a pull request, it is pr/pull-request-number.
For builds triggered by creating a new branch or pushing a commit to a branch, it is …

Support batch build in AWS codebuild

---

CHANGELOG.md
lib/danger/request_sources/bitbucket_server.rb
lib/danger/request_sources/bitbucket_server_api.rb
spec/fixtures/bitbucket_server_api/pr_diff_response.json
spec/lib/danger/request_sources/bitbucket_server_spec.rb
spec/support/bitbucket_server_helper.rb

As BitBucket Server inline comments are done with the Code Insights annotations, some of the comments may get left out. As per their [API documentation](https://docs.atlassian.com/bitbucket-server/rest/7.18.2/bitbucket-code-insights-rest.html#idp10) only the annotations that are on lines changed in the unified diff will be displayed.
This PR makes a change in how the "rest of the violations" are gathered after the inline comments have been posted.
If environment variable `DANGER_BITBUCKETSERVER_INCLUDE_OUT_OF_RANGE_MESSAGES` is set to true, instead of rejecting all inline comments, it checks for the PR diff and compares the violations against it to determine if the violation should be included in the final comment message.
And thanks to @vassilevsky for doing the ground work for this …

Improve how violations are handled with inline commenting on Bitbucket Server 

---

.github/workflows/CI.yml
CHANGELOG.md

Use GitHub Actions matrix to run checks on macOS, Ubuntu and Windows.
- Use GitHub Actions matrix with OS
- Cancel concurrent GitHub Actions workflow run
- Check only pull requests to `master` branch
- Reformat code

Run GitHub Actions workflow on macOS, Ubuntu and Windows

---

.circleci/config.yml
.rubocop.yml
.travis.yml
CHANGELOG.md
appveyor.yml
danger.gemspec

Require Ruby version 2.7+. Ruby 2.6 has reached end of life: https://www.ruby-lang.org/en/downloads/branches. This change is a prerequisite to https://github.com/danger/danger/pull/1377.
Changes:
- Use Ruby 2.7
- Use bundler 2.3.20
AppVeyor project configuration needs to be changed to use Visual Studio 2022 (or at least 2019) to support Ruby 2.7 (https://www.appveyor.com/docs/windows-images-software/#ruby).

Drop support for Ruby 2.4, support Ruby 2.7+

---

CHANGELOG.md
danger.gemspec

Danger relies on Octokit gem dependency version `~> 4.7`, which makes it impossible to use Octokit version 5.0 and above when dependencies are resolved with Bundler.

Update Octokit gem dependency to version 5.x

---

.rubocop.yml

The following error occurred when currently running the RuboCop, so this PR is fixed this error.
```
bundle exec rubocop
.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
.rubocop.yml: Style/FileName has the wrong namespace - should be Naming
/Users/yudai.takada/ydah/danger/.rubocop.yml: Warning: no department given for PercentLiteralDelimiters.
Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentHash` cop has been renamed to `Layout/FirstHashElementIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentHeredoc` cop has been renamed to `Layout/HeredocIndentation`.
(obsolete configuration found in .rubocop.yml, …
```

Fix RuboCop runtime errors #trivial

---

.rubocop.yml
lib/danger/danger_core/dangerfile.rb
spec/lib/danger/helpers/comments_helper_spec.rb

The following warnings occurred when currently running the RuboCop, so this PR is fixed this warnings.
```
/ydah/danger/lib/danger/danger_core/dangerfile.rb: Warning: no department given for Eval. Run `rubocop -a --only Migration/DepartmentName` to fix.
spec/lib/danger/helpers/comments_helper_spec.rb: Metrics/LineLength has the wrong namespace - should be Layout
spec/lib/danger/helpers/comments_helper_spec.rb: Metrics/LineLength has the wrong namespace - should be Layout
spec/lib/danger/helpers/comments_helper_spec.rb: Metrics/LineLength has the wrong namespace - should be Layout
spec/lib/danger/helpers/comments_helper_spec.rb: Metrics/LineLength has the wrong namespace - should be Layout
spec/lib/danger/helpers/comments_helper_spec.rb: Metrics/LineLength has the wrong namespace - should …
```

Fix RuboCop runtime warnings #trivial

---

Dockerfile

According to DockerFile reference `MAINTAINER` is now deprecated. 
- https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
We would therefore replace it with `LABEL`.
Ref: https://togithub.com/WerWolv/ImHex/pull/767

Replaces the deprecated `MAINTAINER` for Dockerfile #trivial

---

CHANGELOG.md
lib/danger/commands/plugins/plugin_json.rb
lib/danger/commands/plugins/plugin_lint.rb
lib/danger/commands/plugins/plugin_readme.rb

Close https://github.com/danger/danger/issues/1397
All of `Danger::PluginJSON`, `Danger::PluginLint` and `Danger::PluginReadme` classes have 2 `self.summary` assignments.
Only the latter is effective but it is not suitable message for `Danger::PluginLint` and `Danger::PluginReadme`.
In `Danger::PluginJSON`
- https://github.com/danger/danger/blob/99bc6c7a50628fc0a8b70854b9faed08050f57ed/lib/danger/commands/plugins/plugin_json.rb#L6
- https://github.com/danger/danger/blob/99bc6c7a50628fc0a8b70854b9faed08050f57ed/lib/danger/commands/plugins/plugin_json.rb#L18
In `Danger::PluginLint`
- https://github.com/danger/danger/blob/99bc6c7a50628fc0a8b70854b9faed08050f57ed/lib/danger/commands/plugins/plugin_lint.rb#L7
- https://github.com/danger/danger/blob/99bc6c7a50628fc0a8b70854b9faed08050f57ed/lib/d …

Remove unintended overrides of self.summary to fix help comments

---

.github/workflows/CI.yml

This PR is add Ruby 3.2 to the CI matrix
Because Ruby 3.2.0 is now in general release, it makes sense to add Ruby 3.2 to the CI matrix.
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

Add Ruby 3.2 to the CI matrix #trivial

---

.github/dependabot.yml

How about using dependabot in this way?
When this works, a PullRequest is created as follows:
- ruby/bigdecimal#242
It was created with reference to the following:
- ruby/csv#265

Added dependabot for GitHub Actions #trivial

---

danger.gemspec

Updating to allow Faraday 2.0.0. 
Locking between versions of ">= 0.9.0", "< 2.0" was causing new projects to have dependency conflicts.
Related: https://github.com/danger/danger/issues/1349

Remove `< 2.0` Faraday version restriction

---

CHANGELOG.md
spec/lib/danger/request_sources/bitbucket_cloud_api_spec.rb

Resolve the following warning on `bundle exec rspec spec/lib/danger/request_sources/bitbucket_cloud_api_spec.rb`.
```
WARNING: Using the `raise_error` matcher without providing a specific error or
message risks false positives, since `raise_error` will match when Ruby raises a
`NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the
expectation to pass without even executing the method you are intending to call.
Actual error raised was #<WebMock::NetConnectNotAllowedError: Real HTTP
connections are disabled. Unregistered request: GET h... => 200, :body => "",
:headers => {})
============================================================>. Instead consider
providing a specific error class or message. This message can be suppressed by
setting: …
```

Add missing error types to raise_error matcher

---

CHANGELOG.md
spec/lib/danger/ci_sources/local_git_repo_spec.rb
spec/lib/danger/ci_sources/local_only_git_repo_spec.rb
spec/lib/danger/danger_core/environment_manager_spec.rb
spec/lib/danger/danger_core/executor_spec.rb
spec/lib/danger/danger_core/plugins/dangerfile_git_plugin_spec.rb
spec/lib/danger/scm_source/git_repo_spec.rb
spec/spec_helper.rb

Some specs always fail if `init.defaultBranch` is not `master` in `~/.gitconfig`.
Those spec call `git init` and it determines the initial branch name by global git config since [git 2.28](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch).
I replaced every `git init` with `git init -b master` to set the initial branch.

Explicitly specify initial branch to avoid being affected by global git config

---

CHANGELOG.md
danger.gemspec

Addresses https://nvd.nist.gov/vuln/detail/CVE-2022-47318
> ruby-git versions prior to v1.13.0 allows a remote authenticated attacker to execute an arbitrary ruby code by having a user to load a repository containing a specially crafted filename to the product. This vulnerability is different from CVE-2022-46648.
I think this issue doesn't affect on users in a regular use case.
But for someone who uses Danger and exposes internet-facing API that uses ruby-git, this PR could be helpful.

Security update: ruby-git

---

.github/workflows/CI.yml
CHANGELOG.md
Gemfile

add Ruby 3.2 to GitHub Actions test matrix and fix failed specs to ensure that Danger works with Ruby 3.2 on CI
it seems https://github.com/danger/danger/pull/1411 has been reverted, this is a restore of it
On Ruby 3.2, some tests using WebMock fail like the one below.
<details>
<summary> Result of a test case using WebMock </summary>
```ruby
$ bundle rspec spec/lib/danger/request_sources/gitlab_spec.rb:147
Run options: include {:locations=>{"./spec/lib/danger/request_sources/gitlab_spec.rb"=>[147]}}
Randomized with seed 60974
Danger::RequestSources::GitLab
valid server response
set its mr_json (FAILED - 1)
Failures:
1) Danger::RequestSources::GitLab valid server response set its mr_json
Failure/Error: WebMock.stub_request(:get, url).with(headers: expected_headers).to_return(raw_file) …
```

Add Ruby 3.2 to test matrix

---

danger.gemspec

This PR updates the `octokit` dependency from `~> 5.0` to `~> 6.0`. The latest version of `octokit` is [`6.1.1`](https://github.com/octokit/octokit.rb/releases/tag/v6.1.1). This change allows projects that use `danger` to keep up-to-date with the latest `octokit` changes. 
This is technically a breaking change because it's jumping from `5.x` to `6.x`. The `octokit` `6.0.0` release states: 
> We're releasing v6.0.0 because https://github.com/octokit/octokit.rb/pull/1494 and https://github.com/octokit/octokit.rb/pull/1495 are technically breaking changes although the APIs that underlie this functionalilty have been not operational for some time.
I ran the `danger` tests locally after upgrading to `6.1.1` and they all passed successfully. 
I also searched the `danger` codebase for any uses …

Update `octokit` to `6.0`

---

CHANGELOG.md

This PR adds a changelog entry for https://github.com/danger/danger/pull/1437. Sorry, I realized I forgot to commit this before submitting that PR. 
Also fixed the markdown link syntax for the #1435 entry.

Add CHANGELOG.md entry for PR #1437

---

CHANGELOG.md
danger.gemspec
lib/danger/scm_source/git_repo.rb
spec/lib/danger/scm_source/git_repo_spec.rb

In this PR https://github.com/danger/danger/pull/1419, the gemspec for runtime dependency on `git` was bumped to `~> 1.13.0`. 
When updating Danger to 9.3.0 today, I noticed the dependency-resolving issue. In my project, bundler has already fixed `git` at version `1.18.0`, so installing danger v9.3.0 means we need to downgrade `git`. Bundler didn't allows me to do that by default. (I needed to delete Gemfile.lock and re-run bundle install) 
<details>
This is what we got when updating `danger` via Renovate.
```
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies............
Bundler could not find compatible versions for gem "git":
In snapshot (Gemfile.lock):
git (>= 1.17.2)
In Gemfile:
danger (= 9.3.0) was resolved to 9.3.0, which depends on
git (~> 1.13.0) …
```

Fix dependency constraint on ruby-git

---

CHANGELOG.md
README.md

- I substituted GitHub Actions badge for Travis CI, which is no longer used
- I removed link to Spectrum chat because it returns 404

Update README badges

---

lib/danger/ci_source/azure_pipelines.rb
lib/danger/ci_source/ci_source.rb
lib/danger/ci_source/custom_ci_with_github.rb
lib/danger/ci_source/support/pull_request_finder.rb
lib/danger/request_sources/bitbucket_cloud.rb
spec/lib/danger/ci_sources/custom_ci_with_github_spec.rb

This PR suppresses the following new RuboCop offenses:
```console
% bundle exec rubocop
(snip)
Offenses:
lib/danger/ci_source/azure_pipelines.rb:32:1: C: [Correctable] Layout/EmptyLinesAroundClassBody: Extra empty line detected at class body beginning.
lib/danger/ci_source/azure_pipelines.rb:33:1: C: [Correctable] Layout/EmptyLines: Extra blank line detected.
lib/danger/ci_source/custom_ci_with_github.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
require "danger/request_sources/github/github"
^
lib/danger/ci_source/custom_ci_with_github.rb:33:5: W: Lint/MissingSuper: Call super to initialize state of the parent class.
def initialize(env) ...
^^^^^^^^^^^^^^^^^^^
lib/danger/ci_source/support/pull_request_finder.rb:149:1: C: [Correctable] …
```

Suppress new RuboCop offenses #trivial

---

.github/workflows/publish_package.yml
CHANGELOG.md

[[dangergem.slack.com context](https://dangergem.slack.com/archives/C0BHS23PG/p1688132250783649)]
Fixes https://github.com/danger/danger/issues/1110
This PR adds a workflow similar to [danger/swift](https://github.com/danger/swift/blob/master/.github/workflows/publish_package.yml), [danger/kotlin](https://github.com/danger/kotlin/blob/master/.github/workflows/publish_package.yml), and [danger/danger-js](https://github.com/danger/danger-js/blob/main/.github/workflows/publish_package.yml), but has been updated to make use of new `github` context variables for easier setup (see https://github.com/docker/build-push-action#usage + https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages). If this PR is accepted, I'd be happy to port …

Release to GitHub Container Registry

---

Gemfile

The current required_ruby_version is specified as ">= 2.7.0", so there is no need to consider Ruby version "< 2.7.0".
It seems that the minimum Ruby version was changed to 2.5 in gitlab gem 4.14.1, so special handling was required.

No need to install gitlab for less than Ruby 2.5.0 #trivial

---

danger.gemspec

We've [agreed](https://github.com/danger/danger/pull/1469#issuecomment-1834074314) that we don't need to pin the upper version limit for octokit.

Don't pin octokit dependency

---

CHANGELOG.md
danger.gemspec

I'm working with Danger on an older project that can't upgrade to Octokit v6 or greater yet but is on v4. Since none of Danger's functionality seems to need things from v6 or greater, we can lower the requirements a bit and hopefully soon I can stop vendoring a local version. :smile:

Lower the minimum Octokit version required

---

CHANGELOG.md
lib/danger/danger_core/message_aggregator.rb

This fixes #1465
Context: [Changes to the splat operator's behavior were introduced in Ruby 3](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/)
It passes the dummy "Replicate Crash" test case mentioned in the issue (not sure if I should add it in this PR as well):

Add keyword arguments in MessageAggregator.aggregate for Ruby 3.X

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb
spec/lib/danger/danger_core/executor_spec.rb
spec/lib/danger/request_sources/github_spec.rb

I've stumbled upon this bug that specially showed when using https://github.com/ashfurrow/danger-rubocop.
Very easy to reproduce:
1. Create a PR with RuboCop violations and `danger-rubocop` configured to report violations inline.
2. **Danger runs** -> Violations are added as PR comments
3. Fix some violations in the code
4. **Danger runs** -> Inline PR comments of the removed violations are correctly gone
5. Fix all violations in the code
6. **Danger runs** -> Inline PR comments of the remaining violations aren't deleted 😞 
I went ahead and tried to see if there was something in the code that could point to a misuse on my side, but it didn't look like it.
After some investigation, I saw that the method `submit_inline_comments` was removing the old violations only when there were new …

Delete stale violations when there are no new ones

---

CHANGELOG.md
lib/danger/request_sources/github/github.rb
spec/lib/danger/request_sources/github_spec.rb

Close https://github.com/danger/danger/issues/1475
Currently Danger cannot post an inline comment when it is installed with Octokit >= 8.
It is because that Octokit has changed the method signature of `create_pull_request_comment()` (https://github.com/octokit/octokit.rb/commit/918af86021bbbe2c3883c934ea45c174c51aced5).
This PR fixes this issue by changing arguments depends on Octokit version.
I added 2 specs to confirm that Danger changes its behavior depends on Octokit version.
And I also confirmed that this PR fixes the issue in other repository.
https://github.com/manicmaniac/danger-issue-1475/pull/6
The branch name of this PR is wrong. The change of method signature was introduced in Octokit v8, not v7.

Fix compatibility issue with Octokit >= 8

---

CHANGELOG.md
lib/danger/danger_core/environment_manager.rb
spec/lib/danger/danger_core/environment_manager_spec.rb
spec/support/ci_helper.rb

This PR should fix an issue that happens in my project.
We are running `danger dry_run` on master branch (no PR) on Bitrise CI machines.
After upgrading ruby version from 2.7.6 to 3.1.4 we started to get following error:
`/Users/vagrant/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/danger-9.3.1/lib/danger/request_sources/bitbucket_cloud_api.rb:125:in `fetch_json': Credentials not available. Provide DANGER_BITBUCKETCLOUD_USERNAME, DANGER_BITBUCKETCLOUD_UUID, and DANGER_BITBUCKETCLOUD_PASSWORD as environment variables. (RuntimeError)`
Even though we use Github.com repos and the same Danger version (9.3.1) as before.
The `CI.available_ci_sources` is a set and `local_ci_source` method in `environment_manager.rb` uses a find function to search for **the first valid source** in that set. A …

fix: always use `LocalOnlyGitRepo` source with `dry_run` command

---

danger.gemspec
lib/danger/commands/pr.rb

This gem was only needed to fix [a bug in Ruby 2.4](https://github.com/ruby/ruby/pull/1513), but since the required Ruby version of this gem is 2.7.0 we do not need this patch.

Drop no_proxy_fix gem

---

CHANGELOG.md
README.md

Close https://github.com/danger/danger/issues/1451

Update "What is Danger?" in README

---

CHANGELOG.md
lib/danger/ci_source/bitbucket_pipelines.rb
lib/danger/request_sources/bitbucket_cloud.rb
lib/danger/request_sources/bitbucket_cloud_api.rb
spec/lib/danger/danger_core/environment_manager_spec.rb
spec/lib/danger/request_sources/bitbucket_cloud_api_spec.rb

Close https://github.com/danger/danger/issues/1463
I added some specs and did integration test on https://bitbucket.org/manicmaniac/danger-examples/pull-requests/1

Support repository access token on Bitbucket Cloud

---

.yardopts
CHANGELOG.md
docs/yard_support.rb
lib/danger/ci_source/azure_pipelines.rb
lib/danger/ci_source/bitrise.rb
lib/danger/ci_source/code_build.rb
lib/danger/ci_source/local_git_repo.rb
lib/danger/danger_core/plugins/dangerfile_github_plugin.rb
lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb
lib/danger/danger_core/plugins/dangerfile_messaging_plugin.rb
lib/danger/helpers/comments_helper.rb
lib/danger/helpers/comments_parsing_helper.rb

Close #1483 
Currently API document hosted in https://rubydoc.info/gems/danger/ looks broken.
- All comments are written in GitHub-Flavored Markdown but YARD recognizes them as RDoc
- There's some typos, misindentations and misused tags
This PR fixes those problems.
before|after
---|---

Fix broken YARD documents

---

CHANGELOG.md

@ydah Thank you for your recent contributions. Could I add them to the change log?

Update CHANGELOG entries

---

CHANGELOG.md
danger.gemspec

Close #1496
I added `base64` and `pstore` gem to runtime dependencies because they will be removed from future Ruby stdlib.
```
$ OCTOKIT_SILENT=1 bundle exec danger --version
/Users/manicmaniac/Projects/danger/danger/lib/danger/commands/local.rb:1: warning: pstore was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add pstore to your Gemfile or gemspec to silence this warning.
/Users/manicmaniac/Projects/danger/danger/lib/danger/request_sources/vsts.rb:2: warning: base64 was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add base64 to your Gemfile or gemspec to silence this warning.
9.5.0
```
```
$ OCTOKIT_SILENT=1 bundle exec danger --version
9.5.0
``` …

Add gems ejected from future stdlib

---

CHANGELOG.md
danger.gemspec

A v4.0.0 [terminal-table](https://github.com/tj/terminal-table/releases/tag/v4.0.0) was released on Jan 27th, which can't be updated since `danger` blocks it. This PR aims to relax the `terminal-table` rule set 4 years ago by this [PR](https://github.com/danger/danger/pull/1292). I'm actually trying to bump the `unicode-display_width` gem, but only v4.x supports it, so `danger` is the current blocker.

Support terminal-table 4.x versions

---

CHANGELOG.md
danger.gemspec

Hey all, first of all thank you for an amazing gem, love it!
In my team we just tried running Rails app using `RUBYOPT=--enable-frozen-string-literal` and got a green CI, except danger failed at the very end:
```
Results:
bundler: failed to load command: danger (/usr/local/bundle/bin/danger)
/usr/local/bundle/gems/colored2-3.1.2/lib/colored2/ascii_decorator.rb:67:in 'Colored2::AsciiDecorator#decorate': can't modify frozen String: "" (FrozenError)
from /usr/local/bundle/gems/colored2-3.1.2/lib/colored2.rb:26:in 'String#surround_with_color'
from /usr/local/bundle/gems/colored2-3.1.2/lib/colored2.rb:51:in 'block (3 levels) in String#included'
from /usr/local/bundle/gems/danger-9.4.3/lib/danger/danger_core/dangerfile.rb:223:in 'block (2 levels) in Danger::Dangerfile#print_results'
from …
```

Support v4 of `colored2` gem to make danger compatible with --enable-frozen-string-literal RUBYOPT

---

CHANGELOG.md
lib/danger/ci_source/local_git_repo.rb
lib/danger/ci_source/support/find_repo_info_from_url.rb
lib/danger/ci_source/support/pull_request_finder.rb
lib/danger/commands/mr.rb
lib/danger/commands/runner.rb
spec/lib/danger/ci_sources/support/find_repo_info_from_url_spec.rb
spec/lib/danger/commands/mr_spec.rb

- Add GitLab Merge Request support with a new 'mr' command
- Improve URL parsing for GitLab URLs with the '-/' pattern, example:
- https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/42 versus
- https://gitlab.com/gitlab-org/gitlab-foss/merge_requests/42
- Add tests for the new functionality
- I opted to not rewrite some functionality for language due to the reuse of various parts of bitbucket using similar method names
I did have goofy issues with testing and the client, so I have what I thought would be unnecessary changes, I'm looking for feedback on this, I wasn't entirely sure how to approach those.  And later rubocop finally came around and told me I made things too complex.  Which was true, so I did a hint of refactoring, but only relied on rspec to tell me things were fine.

Add GitLab Merge Request support

---

.rubocop.yml
lib/danger/request_sources/github/github.rb
lib/danger/request_sources/gitlab.rb
lib/danger/request_sources/vsts.rb

Addressed FIXME comments in .rubocop.yml .

Resolve FIXME comments for `Metrics/BlockLength` in .rubocop.yml #trivial
